type Aug18Topic = {
  slug: string;
  title: string;
  keyword: string;
  audience: string;
  unit: string;
  inputs: string;
  output: string;
  risk: string;
  review: string;
  boundary: string;
  example: string;
  measure: string;
  decision: string;
};

const topics: Aug18Topic[] = [
  { slug: 'real-estate-showing-request-admin-assistant-guide-2026', title: 'Real estate showing request administration: build a reviewable scheduling queue', keyword: 'real estate showing request assistant', audience: 'a real estate office handling online showing requests', unit: 'one showing request record', inputs: 'the property reference, requester details, preferred windows, and access notes', output: 'a dated queue with confirmed facts, missing details, and the next owner action', risk: 'double-booking a property or implying that a showing is confirmed', review: 'the licensed agent or designated coordinator', boundary: 'availability, access permissions, pricing, and client promises', example: 'a buyer asks about two properties and supplies only one preferred time', measure: 'complete records, returned records, and requests waiting on agent judgment', decision: 'whether the queue needs a clearer field or a tighter response window' },
  { slug: 'medical-office-lab-result-routing-assistant-guide-2026', title: 'Medical office lab-result routing: organize messages without clinical interpretation', keyword: 'medical office lab result routing assistant', audience: 'a medical office receiving digital laboratory messages', unit: 'one incoming result message', inputs: 'patient identifiers permitted by office policy, message metadata, and the source record', output: 'a restricted routing entry showing receipt, destination, and unresolved administrative fields', risk: 'delaying an urgent message or paraphrasing a result as medical advice', review: 'the authorized clinical or office team', boundary: 'diagnosis, triage, treatment advice, and patient-facing interpretation', example: 'a result arrives without the ordering clinician selected in the routing list', measure: 'accurate routing, missing-field flags, and items escalated within the office rule', decision: 'which administrative field should be required before routing' },
  { slug: 'home-services-materials-request-assistant-guide-2026', title: 'Home services materials requests: keep job supplies visible before purchase approval', keyword: 'home services materials request assistant', audience: 'a local home-services operator coordinating supplies across jobs', unit: 'one materials request', inputs: 'job identifier, requested item, quantity, needed-by note, and source message', output: 'a prioritized request record ready for an operator to approve or question', risk: 'ordering the wrong item or turning a request into an unauthorized purchase', review: 'the job manager or owner', boundary: 'technical specification, vendor selection, purchase approval, and field diagnosis', example: 'a technician sends a photo and shorthand description for a replacement part', measure: 'requests with complete references, clarification loops, and approved versus held items', decision: 'whether the intake form needs a photo, model, or urgency field' },
  { slug: 'law-firm-conflict-check-admin-assistant-guide-2026', title: 'Law firm conflict-check administration: prepare facts without giving legal advice', keyword: 'law firm conflict check assistant', audience: 'a small law firm collecting prospective-client information', unit: 'one conflict-check intake', inputs: 'names supplied by the caller, related parties, matter description, and contact channel', output: 'a consistently formatted record for the firm’s conflict-review process', risk: 'missing a related name or implying that the firm accepted representation', review: 'the attorney or authorized intake lead', boundary: 'legal advice, conflict conclusions, engagement decisions, and urgency judgments', example: 'a caller uses a company name but omits an individual opposing party', measure: 'complete fields, follow-up questions, and matters awaiting attorney review', decision: 'which names and relationships must be mandatory' },
  { slug: 'ecommerce-return-photo-intake-assistant-guide-2026', title: 'Ecommerce return-photo intake: sort evidence before a remedy decision', keyword: 'ecommerce return photo intake assistant', audience: 'an online store reviewing customer-submitted return evidence', unit: 'one return evidence packet', inputs: 'order reference, customer explanation, photos, product identifier, and received timestamp', output: 'an indexed packet that lets the store owner compare evidence with policy', risk: 'promising a refund or losing evidence needed for an exception review', review: 'the store owner or returns lead', boundary: 'refund authorization, warranty interpretation, fraud conclusions, and policy exceptions', example: 'a customer sends three images but none show the product label', measure: 'packets indexed, missing evidence requests, and cases held for a decision', decision: 'whether a new photo instruction would prevent repeat exchanges' },
  { slug: 'agency-creative-brief-intake-assistant-guide-2026', title: 'Agency creative brief intake: separate client facts from open creative decisions', keyword: 'agency creative brief assistant', audience: 'a small agency receiving requests from several client accounts', unit: 'one incoming creative brief', inputs: 'approved request text, deliverable type, audience, source links, and due-date request', output: 'a brief that distinguishes known requirements, assumptions, and questions', risk: 'turning an unapproved idea into a client commitment', review: 'the account lead or creative director', boundary: 'strategy approval, scope promises, copy claims, and final creative sign-off', example: 'a client asks for a campaign “next week” without supplying format or reviewer', measure: 'briefs accepted, questions answered, and tasks blocked by missing approval', decision: 'which intake question removes the most avoidable rework' },
  { slug: 'bookkeeping-bank-statement-intake-assistant-guide-2026', title: 'Bookkeeping bank-statement intake: make monthly source collection easy to audit', keyword: 'bookkeeping bank statement intake assistant', audience: 'a small business bookkeeping team collecting monthly source records', unit: 'one account-period packet', inputs: 'account label, covered dates, statement file, source location, and missing-period note', output: 'a dated collection log that a bookkeeper can inspect before reconciliation', risk: 'classifying transactions or treating an incomplete statement as complete', review: 'the bookkeeper or accountable owner', boundary: 'accounting treatment, tax advice, reconciliation approval, and payment decisions', example: 'a statement covers 28 days while the monthly checklist expects the full period', measure: 'periods received, files rejected for incompleteness, and questions resolved', decision: 'whether the checklist should require opening and closing dates' },
  { slug: 'property-manager-lease-file-intake-assistant-guide-2026', title: 'Property manager lease-file intake: organize documents before an authorized review', keyword: 'property manager lease file assistant', audience: 'a property management team maintaining digital lease records', unit: 'one property or tenant file update', inputs: 'unit reference, document type, effective date, sender, and file version', output: 'a named and indexed file set with gaps clearly marked', risk: 'overwriting a current document or interpreting a lease provision', review: 'the property manager or qualified administrator', boundary: 'legal interpretation, eviction decisions, rent changes, and tenant promises', example: 'two versions of an addendum arrive with similar filenames', measure: 'files indexed, duplicates flagged, and records awaiting manager comparison', decision: 'whether version naming or an effective-date field needs repair' },
  { slug: 'nonprofit-grant-deadline-research-assistant-guide-2026', title: 'Nonprofit grant deadline research: build a source-linked opportunity queue', keyword: 'nonprofit grant research assistant', audience: 'a nonprofit team screening public grant opportunities', unit: 'one opportunity record', inputs: 'official funder page, deadline, stated eligibility, program focus, and source date', output: 'a source-linked note that separates published facts from fit questions', risk: 'calling an opportunity a fit without checking eligibility or current guidance', review: 'the program director or grant lead', boundary: 'eligibility determination, funding promises, application strategy, and representations to a funder', example: 'a search result shows a deadline but the funder page has a newer notice', measure: 'records with primary sources, stale pages found, and opportunities awaiting fit review', decision: 'which source field should be checked again before drafting' },
  { slug: 'executive-travel-itinerary-research-assistant-guide-2026', title: 'Executive travel itinerary research: prepare options while the traveler keeps the choice', keyword: 'executive travel research assistant', audience: 'an executive assistant supporting business travel planning', unit: 'one itinerary option set', inputs: 'approved dates, meeting constraints, traveler preferences, and policy limits', output: 'clearly labeled options with source links, open assumptions, and hold instructions', risk: 'booking a nonrefundable option or hiding a schedule conflict', review: 'the traveler or executive’s designated approver', boundary: 'purchases, passport or visa advice, policy exceptions, and final itinerary approval', example: 'a lower-cost connection arrives after the first meeting begins', measure: 'options checked, constraints surfaced, and selections awaiting approval', decision: 'whether the travel brief needs a buffer or cancellation field' },
  { slug: 'customer-onboarding-access-request-assistant-guide-2026', title: 'Customer onboarding access requests: track setup without granting permissions', keyword: 'customer onboarding access assistant', audience: 'a service team coordinating new-customer workspace setup', unit: 'one access request', inputs: 'customer name, workspace, requested role, approver, and due date', output: 'a traceable request record that the authorized administrator can execute', risk: 'granting excessive access or telling a customer that setup is complete too early', review: 'the workspace administrator or account owner', boundary: 'permission grants, security exceptions, customer commitments, and technical diagnosis', example: 'a request names a team but not the least-privilege role required', measure: 'requests complete, returned for clarification, and confirmed by the administrator', decision: 'whether role labels are understandable to the requesting team' },
  { slug: 'restaurant-catering-inquiry-admin-assistant-guide-2026', title: 'Restaurant catering inquiry administration: capture event facts before a quote', keyword: 'restaurant catering inquiry assistant', audience: 'a restaurant handling online catering and private-event questions', unit: 'one catering inquiry', inputs: 'event date, guest estimate, service style, location, dietary questions, and contact preference', output: 'a concise inquiry record with unanswered questions and assigned follow-up', risk: 'promising availability, menu, or a price before the restaurant reviews the request', review: 'the events manager or restaurant owner', boundary: 'availability, menu commitments, pricing, contracts, and allergy assurances', example: 'a host asks for a menu recommendation before sharing the venue address', measure: 'inquiries complete, follow-up questions sent, and proposals awaiting owner review', decision: 'which event field should be added to reduce back-and-forth' },
  { slug: 'professional-services-research-source-log-assistant-guide-2026', title: 'Professional services research source logs: make client-facing claims traceable', keyword: 'professional services research assistant', audience: 'a consulting or advisory team preparing source-backed client work', unit: 'one claim-and-source note', inputs: 'client question, source URL, relevant passage summary, publication date, and confidence note', output: 'a review-ready source log that distinguishes evidence from interpretation', risk: 'presenting an outdated or weak source as a verified conclusion', review: 'the consultant or subject-matter professional', boundary: 'professional advice, conclusions, client promises, and unsupported extrapolation', example: 'two sources report different definitions for the same market term', measure: 'notes with primary links, unresolved conflicts, and claims approved for drafting', decision: 'whether the source log needs a definition or date column' },
  { slug: 'membership-renewal-exception-assistant-guide-2026', title: 'Membership renewal exceptions: prepare account notes before a policy response', keyword: 'membership renewal assistant', audience: 'a membership organization handling renewal questions', unit: 'one renewal exception', inputs: 'member reference, renewal date, message, account context, and requested remedy', output: 'a neutral exception note for an authorized staff decision', risk: 'changing status or offering an exception without policy authority', review: 'the membership manager', boundary: 'policy interpretation, refunds, status changes, and promises about eligibility', example: 'a member reports a duplicate charge but the account history is incomplete', measure: 'exceptions documented, records requested, and decisions returned to staff', decision: 'whether the intake needs a payment-reference field' },
  { slug: 'field-service-job-photo-indexing-assistant-guide-2026', title: 'Field service job-photo indexing: organize visual evidence for local review', keyword: 'field service photo intake assistant', audience: 'a field-service company receiving job photos from technicians', unit: 'one job-photo set', inputs: 'job number, image timestamp, technician note, location within the job, and missing context', output: 'an indexed set that a local manager can review beside the job record', risk: 'diagnosing a problem or treating an unclear image as proof of completed work', review: 'the technician, supervisor, or local manager', boundary: 'safety diagnosis, scope changes, customer promises, and work authorization', example: 'a photo shows a component but does not identify the property or stage of work', measure: 'sets matched to jobs, context requests, and images awaiting supervisor review', decision: 'whether technicians need a standard photo naming convention' },
  { slug: 'recruiting-interview-feedback-admin-assistant-guide-2026', title: 'Recruiting interview feedback administration: standardize notes without ranking candidates', keyword: 'recruiting interview feedback assistant', audience: 'a hiring team collecting interviewer feedback', unit: 'one completed feedback packet', inputs: 'candidate identifier, interview stage, interviewer, submitted form, and missing response fields', output: 'a complete packet ready for the hiring panel’s review', risk: 'changing an interviewer’s meaning or making a selection recommendation', review: 'the hiring manager or panel chair', boundary: 'candidate ranking, employment decisions, compensation discussion, and reference conclusions', example: 'one interviewer submits a score but leaves the evidence field blank', measure: 'packets complete, missing forms, and items waiting for panel discussion', decision: 'whether the form should require an example for every rating' },
  { slug: 'insurance-claim-document-intake-assistant-guide-2026', title: 'Insurance claim document intake: organize submitted evidence before licensed review', keyword: 'insurance claim document assistant', audience: 'an insurance-related operations team collecting claim documents', unit: 'one claim document packet', inputs: 'claim reference, document type, incident date, sender, and received date', output: 'an indexed packet with missing items and source provenance visible', risk: 'interpreting coverage, estimating settlement, or losing a document version', review: 'the insurer or authorized claims professional', boundary: 'coverage opinions, liability findings, settlement decisions, and legal advice', example: 'a customer sends a repair estimate without identifying the claim reference', measure: 'documents matched, duplicate versions, and packets awaiting licensed review', decision: 'whether the request template needs a claim-reference reminder' },
  { slug: 'course-enrollment-records-assistant-guide-2026', title: 'Course enrollment records: keep learner questions and status changes reviewable', keyword: 'course enrollment assistant', audience: 'an education business managing online course registrations', unit: 'one enrollment record update', inputs: 'learner reference, course, request type, received message, and supporting record', output: 'a status note and question queue for the authorized education team', risk: 'changing access or promising an exception without checking policy', review: 'the program administrator or instructor', boundary: 'grading, refund decisions, accessibility determinations, and policy exceptions', example: 'a learner asks for an extension but the course and deadline are not stated', measure: 'records updated, questions clarified, and exceptions awaiting a decision', decision: 'whether every request should carry a course and cohort field' },
  { slug: 'vendor-certificate-intake-assistant-guide-2026', title: 'Vendor certificate intake: track documents without approving compliance', keyword: 'vendor certificate tracking assistant', audience: 'a business collecting vendor insurance or compliance documents', unit: 'one vendor document receipt', inputs: 'vendor name, document type, expiration date shown, source, and related project', output: 'a dated register that flags missing or apparently expired records', risk: 'declaring a vendor compliant or overlooking a document mismatch', review: 'the risk, operations, or project owner', boundary: 'legal sufficiency, coverage interpretation, vendor approval, and contract decisions', example: 'the certificate names a related entity rather than the project vendor', measure: 'documents logged, questions raised, and records awaiting qualified review', decision: 'whether entity-name matching needs a dedicated field' },
  { slug: 'saas-renewal-preparation-assistant-guide-2026', title: 'SaaS renewal preparation: assemble account facts without making a renewal promise', keyword: 'SaaS renewal preparation assistant', audience: 'a software team preparing account-owner renewal conversations', unit: 'one renewal brief', inputs: 'account name, renewal date, product usage fields, open support items, and owner notes', output: 'a factual brief with unresolved questions and a named account owner', risk: 'promising a term, discount, feature, or renewal outcome', review: 'the account executive or customer owner', boundary: 'commercial negotiation, product commitments, pricing, and churn decisions', example: 'usage data is available but a support issue remains open', measure: 'briefs complete, facts needing confirmation, and conversations ready for owner review', decision: 'whether a support-status field belongs before usage metrics' },
  { slug: 'home-care-schedule-note-assistant-guide-2026', title: 'Home-care schedule notes: organize changes without making care decisions', keyword: 'home care schedule assistant', audience: 'a home-care office coordinating administrative schedule messages', unit: 'one schedule-change note', inputs: 'client reference, caregiver, stated change, time window, and message source', output: 'a time-stamped note routed to the responsible office or care lead', risk: 'altering care coverage or treating a health statement as a scheduling fact', review: 'the authorized scheduler or care manager', boundary: 'clinical judgment, care-plan changes, staffing commitments, and urgent-care advice', example: 'a family message combines a time request with a concern about a client’s condition', measure: 'notes routed, urgent language escalated by office rule, and changes confirmed by staff', decision: 'whether the intake needs a separate safety-escalation flag' },
  { slug: 'construction-subcontractor-document-intake-assistant-guide-2026', title: 'Construction subcontractor document intake: route project paperwork before approval', keyword: 'construction subcontractor document assistant', audience: 'a construction office collecting digital subcontractor paperwork', unit: 'one subcontractor document packet', inputs: 'project, subcontractor, document type, version, received date, and missing-field note', output: 'an indexed packet for the project manager’s review', risk: 'approving work, interpreting contract requirements, or losing a current version', review: 'the project manager or authorized contract administrator', boundary: 'safety decisions, payment approval, scope changes, and contract interpretation', example: 'a revised document arrives without a clear superseded version', measure: 'packets complete, duplicate versions, and project questions awaiting review', decision: 'whether a revision reason should be required in the intake' },
];

// One literal campaign-date binding per accepted route for repository auditability.
const aug18PublicationRecords = [
  { slug: 'real-estate-showing-request-admin-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'medical-office-lab-result-routing-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'home-services-materials-request-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'law-firm-conflict-check-admin-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'ecommerce-return-photo-intake-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'agency-creative-brief-intake-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'bookkeeping-bank-statement-intake-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'property-manager-lease-file-intake-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'nonprofit-grant-deadline-research-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'executive-travel-itinerary-research-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'customer-onboarding-access-request-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'restaurant-catering-inquiry-admin-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'professional-services-research-source-log-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'membership-renewal-exception-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'field-service-job-photo-indexing-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'recruiting-interview-feedback-admin-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'insurance-claim-document-intake-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'course-enrollment-records-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'vendor-certificate-intake-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'saas-renewal-preparation-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'home-care-schedule-note-assistant-guide-2026', published: '2026-08-18' },
  { slug: 'construction-subcontractor-document-intake-assistant-guide-2026', published: '2026-08-18' },
] as const;

const sectionHeadings = ['Define the work unit', 'Capture facts before action', 'Make the handoff inspectable', 'Handle the exception path', 'Protect judgment and access', 'Use a first-batch scorecard', 'Review the operating fit'];

function makePost(topic: Aug18Topic) {
  const paragraphs = [
    `${topic.audience} can use a Philippines-based remote assistant when ${topic.unit} is digital, repeatable, and reviewed by someone who understands the underlying work. The useful question is not whether an assistant can “help” in the abstract. It is whether the source information can be handled safely, the finished record can be recognized, and an exception can stop at the right person.`,
    `Start by writing the unit in plain language: ${topic.unit}. That definition gives the assistant a countable piece of work instead of a vague responsibility. It also lets the owner compare the written request with the record that came back. If several kinds of requests arrive, keep them as separate lanes until their rules are understood.`,
    `The first intake should collect ${topic.inputs}. Those fields are not a substitute for professional judgment; they are the minimum context needed to prevent a reviewer from searching through scattered messages. Mark unknown information as missing rather than filling it from guesswork. A visible gap is safer than a confident but unsupported value.`,
    `The finished item should be ${topic.output}. Put the source message or file beside the record, use a consistent date and owner field, and name the next action. A reviewer should be able to answer three questions quickly: what arrived, what was done, and what still requires an accountable decision.`,
    `The most important stop rule addresses ${topic.risk}. When that condition appears, the assistant should preserve the source, note the uncertainty, and route it to ${topic.review}. The handoff should say what is known and what is not known. It should never convert a request for preparation into an approval, diagnosis, promise, or conclusion.`,
    `Consider this ordinary case: ${topic.example}. A useful record would show the received information, the missing fact, the person who owns the question, and the time when it should be revisited. That structure keeps the assistant productive without asking the assistant to improvise a decision that belongs to the local team or a qualified professional.`,
    `Access should follow the work unit. Give the assistant the queue, source material, and named account needed to prepare ${topic.output}; keep ${topic.boundary} with the accountable owner. Prefer individual accounts, limited permissions, and a clear way to revoke access. The owner should also decide how sensitive records are redacted before examples are shared.`,
    `A narrow first batch makes quality visible. The reviewer can compare the submitted record with the source, mark a correction, and update the instruction when the same question returns. If the assistant repeatedly encounters a missing field, repair the intake or example before increasing volume. More activity does not fix an unclear workflow.`,
    `The scorecard should count ${topic.measure}. Do not treat raw volume as the goal. A queue that is fast but incomplete creates work for the person who must repair it. Pair completed units with returned items, unanswered questions, aging records, and access exceptions. These measures show whether the handoff is becoming easier to supervise.`,
    `Keep local and remote responsibilities separate. The remote assistant can organize online records, draft neutral notes, and surface missing information. The local operator may still need to speak with a customer, inspect a property, assess a situation, or make a regulated decision. Stating that boundary protects the business and gives the assistant a fair description of the job.`,
    `At the weekly review, select a few completed records and one exception. Ask whether the source is traceable, the fields are accurate, and the next owner action is obvious. Ask the assistant which instruction caused hesitation. The review is a conversation about the system as well as the person; recurring questions usually point to a process gap.`,
    `Do not hide policy in a shortcut phrase such as “handle as usual.” Replace it with an example, a stop rule, and an escalation destination. For this workflow, the owner should decide ${topic.decision}. That decision can be recorded in the operating note so a future reviewer sees why the field, queue, or boundary exists.`,
    `A first-month handoff can stay deliberately small: prepare the records, review them daily at first, and add only one adjacent task after the original lane is stable. If a new task changes the risk, source data, or approval owner, treat it as a new lane. That prevents a useful assistant role from quietly becoming an undefined catch-all position.`,
    `The practical test is simple. Can a new reviewer open the source, understand the record, see the unresolved question, and identify who decides next? If yes, the workflow is ready for measured use. If not, improve the brief before blaming the worker. Clear work, limited access, and an explicit escalation path are the foundation of dependable remote assistant support.`,
  ];
  return {
    slug: topic.slug,
    mainKeyword: topic.keyword,
    title: topic.title,
    excerpt: `Plan ${topic.keyword} around a defined work unit, source-linked records, and an approval boundary that keeps judgment with the accountable team.`,
    published: aug18PublicationRecords.find((record) => record.slug === topic.slug)!.published,
    richPublished: true,
    minutes: 10,
    image: '/images/calendar-assistant.jpg',
    imageAlt: `${topic.title} workflow planning at a remote desk`,
    takeaways: [`Start with ${topic.unit}.`, `Capture ${topic.inputs}.`, `Escalate ${topic.risk}.`, `Measure ${topic.measure}.`],
    detail: {
      revision: `2026-08-18-${topic.slug}-r1`,
      directAnswer: [paragraphs[0], paragraphs[3]],
      bodyLinks: [{ href: '/blog/virtual-assistant-security-checklist', label: 'review the remote assistant security checklist' }, { href: '/blog/local-vs-remote-administrative-assistant-benchmark-2026', label: 'compare local and remote task fit' }],
      sections: sectionHeadings.map((heading, index) => ({ heading, paragraphs: [paragraphs[index * 2 + 1], paragraphs[index * 2 + 2]] })),
      decisionRows: [{ need: 'Online preparation and record keeping', fit: 'Philippines-based remote assistant', reason: 'The output can be defined, sourced, and reviewed.' }, { need: 'Physical or regulated judgment', fit: 'Local or qualified owner', reason: 'The work depends on presence, authority, or professional judgment.' }, { need: 'Unclear exception', fit: 'Pause and escalate', reason: 'The assistant preserves facts and waits for the named reviewer.' }, { need: 'Mixed workflow', fit: 'Split the lanes', reason: 'Separate preparation from approval and field work.' }],
      planningNumbers: [{ value: '1 unit', label: 'First scope', note: topic.unit }, { value: '1 reviewer', label: 'Decision owner', note: topic.review }, { value: '1 stop rule', label: 'Main risk', note: topic.risk }, { value: '7 days', label: 'First review', note: 'Inspect a small batch before adding volume.' }],
      scripts: [{ title: 'Role brief', text: `Prepare ${topic.unit} from the approved queue. Record ${topic.inputs}, link the source, and escalate ${topic.risk} to ${topic.review}.` }, { title: 'Review question', text: `Can we verify ${topic.output} from the source, and is the next decision clearly assigned to ${topic.review}?` }],
      scenario: { title: `Sample workflow: ${topic.keyword}`, intro: 'Use this sequence to turn an incoming request into a checkable first task lane.', steps: [{ step: '1', title: 'Receive', body: `Save the source for ${topic.unit} and note when it arrived.` }, { step: '2', title: 'Record', body: `Enter ${topic.inputs} without guessing at missing information.` }, { step: '3', title: 'Check', body: `Compare the record with the example and flag ${topic.risk}.` }, { step: '4', title: 'Route', body: `Send the completed item or exception to ${topic.review}.` }, { step: '5', title: 'Learn', body: `Use the review to decide ${topic.decision}.` }] },
      faqs: [{ question: `What is the first unit for ${topic.keyword}?`, answer: `Start with ${topic.unit}, using ${topic.inputs} as the minimum source context.` }, { question: 'What should the remote assistant never decide?', answer: `Keep ${topic.boundary} with the accountable owner or qualified professional.` }, { question: 'How should exceptions be handled?', answer: `Preserve the source, describe the missing or conflicting fact, and route it to ${topic.review}.` }, { question: 'What should the first review measure?', answer: `Measure ${topic.measure}, along with corrections and items waiting on a decision.` }, { question: 'Where are assistants recruited?', answer: 'This service recruits and hires assistants in the Philippines for remote work.' }],
      relatedLinks: [{ href: '/blog/virtual-assistant-security-checklist', label: 'Set access rules before handoff' }, { href: '/blog/local-vs-remote-administrative-assistant-benchmark-2026', label: 'Compare local and remote task fit' }, { href: '/blog', label: 'Browse all hiring guides' }, { href: '/contact-us', label: 'Prepare a role brief' }],
      sources: [{ name: 'CISA, Turn on Multifactor Authentication', url: 'https://www.cisa.gov/secure-our-world/turn-mfa', note: 'Account sign-in guidance.' }, { name: 'FTC Business Guidance', url: 'https://www.ftc.gov/business-guidance', note: 'General business and data-handling guidance.' }],
    },
  };
}

export const aug18BlogPosts = topics.map(makePost);
