type Topic = {
  slug: string; title: string; focus: string; artifact: string; owner: string;
  boundary: string; mistake: string; example: string; signal: string; image: string; imageAlt: string;
  published: '2026-08-20';
};

const sourceLinks = [{ name: 'CISA, Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'Practical account and access guidance.' }, { name: 'FTC Business Guidance', url: 'https://www.ftc.gov/business-guidance', note: 'General business and data-handling guidance.' }, { name: 'U.S. Bureau of Labor Statistics', url: 'https://www.bls.gov/ooh/office-and-administrative-support/secretaries-and-administrative-assistants.htm', note: 'Administrative work context.' }];

const topics: Topic[] = [
  { slug: 'owner-inbox-triage-without-unauthorized-replies', title: 'Owner inbox triage without unauthorized replies', focus: 'owner inbox triage', artifact: 'a labeled morning queue with source links and draft-only next steps', owner: 'the business owner', boundary: 'sending a reply, making a promise, or interpreting a sensitive relationship', mistake: 'treating a full inbox as permission to answer every message', example: 'a supplier asks for a change while a customer asks for a deadline', signal: 'the reviewer can see why each message is waiting, drafted, or escalated', image: '/images/aug20-blog-inbox-triage.png', imageAlt: 'Remote assistant organizing an owner inbox into reviewable lanes', published: '2026-08-20' },
  { slug: 'calendar-conflict-preparation-for-remote-assistants', title: 'Calendar conflict preparation for remote assistants', focus: 'calendar conflict preparation', artifact: 'a conflict brief showing the event source, constraints, and options', owner: 'the calendar owner', boundary: 'moving a priority meeting or committing an attendee without approval', mistake: 'solving a conflict by guessing which meeting matters more', example: 'two invitations overlap while one has an unclear attendee list', signal: 'every proposed change has a visible reason and an approval owner', image: '/images/aug20-blog-calendar-conflicts.png', imageAlt: 'Remote assistant comparing calendar conflicts and meeting constraints', published: '2026-08-20' },
  { slug: 'crm-cleanup-evidence-before-record-merges', title: 'CRM cleanup: gather evidence before record merges', focus: 'CRM cleanup and duplicate review', artifact: 'a merge-candidate list with matched fields and a hold reason', owner: 'the sales or operations lead', boundary: 'merging records, deleting history, or deciding which customer identity is correct', mistake: 'equating similar names with proof that two records are the same', example: 'two contacts share a domain but have different phone numbers and notes', signal: 'a reviewer can approve or reject each candidate from the cited evidence', image: '/images/aug20-blog-crm-cleanup.png', imageAlt: 'Assistant reviewing CRM records and duplicate evidence on a laptop', published: '2026-08-20' },
  { slug: 'research-source-ledger-for-daily-content-routines', title: 'A research source ledger for daily content routines', focus: 'research source registration', artifact: 'a claim ledger that maps each draft point to a reachable source', owner: 'the editorial reviewer', boundary: 'turning an unverified claim into published advice', mistake: 'saving links without recording which sentence each link supports', example: 'a benchmark appears in a draft but the source period is missing', signal: 'the reviewer can distinguish source fact, inference, and open question', image: '/images/aug20-blog-source-ledger.png', imageAlt: 'Editorial assistant building a source ledger for a daily research routine', published: '2026-08-20' },
  { slug: 'customer-support-escalation-notes-for-small-teams', title: 'Customer-support escalation notes for small teams', focus: 'customer-support escalation preparation', artifact: 'a concise case brief with the customer request, history, and decision needed', owner: 'the support lead', boundary: 'offering compensation, admitting fault, or changing a policy', mistake: 'writing a confident answer before the account history is checked', example: 'a customer cites an earlier promise that is not visible in the current ticket', signal: 'the support lead receives a neutral packet instead of a guessed resolution', image: '/images/aug20-blog-support-escalations.png', imageAlt: 'Assistant preparing a customer support escalation brief', published: '2026-08-20' },
  { slug: 'appointment-reminder-queues-with-clear-stop-rules', title: 'Appointment reminder queues with clear stop rules', focus: 'appointment reminder preparation', artifact: 'a reminder queue with confirmed details, channel, and exception status', owner: 'the scheduling owner or qualified practice team', boundary: 'giving medical advice, changing care instructions, or resolving an uncertain identity', mistake: 'treating a reminder task as permission to answer a care question', example: 'a patient asks a clinical question inside a scheduling reply', signal: 'the reminder is separated from the question that needs a qualified response', image: '/images/aug20-blog-reminder-queues.png', imageAlt: 'Remote assistant organizing appointment reminders and escalation flags', published: '2026-08-20' },
  { slug: 'invoice-follow-up-records-before-finance-escalation', title: 'Invoice follow-up records before finance escalation', focus: 'invoice follow-up record preparation', artifact: 'an aging list with invoice source, last contact, and owner action', owner: 'the finance owner', boundary: 'changing terms, threatening collection, or marking a balance as settled', mistake: 'assuming an old invoice is still owed because a spreadsheet says so', example: 'a payment note exists in one system but not in the aging export', signal: 'each follow-up has a source, date, channel, and explicit approval state', image: '/images/aug20-blog-invoice-followup.png', imageAlt: 'Assistant reviewing invoice follow-up records and payment notes', published: '2026-08-20' },
  { slug: 'real-estate-listing-admin-source-checks', title: 'Real-estate listing administration with source checks', focus: 'real-estate listing administration', artifact: 'a listing change sheet that preserves supplied facts and missing fields', owner: 'the agent or broker responsible for the listing', boundary: 'interpreting a listing, changing a price, or making a client representation', mistake: 'copying an old listing detail into a new record without a current source', example: 'a listing request names a room count that differs from the approved sheet', signal: 'the accountable professional can approve the exact change from its source', image: '/images/aug20-blog-listing-admin.png', imageAlt: 'Assistant checking real-estate listing details against source documents', published: '2026-08-20' },
  { slug: 'ecommerce-order-exception-queues-for-remote-support', title: 'Ecommerce order-exception queues for remote support', focus: 'ecommerce order-exception preparation', artifact: 'an exception card with order evidence, customer request, and next decision', owner: 'the store operations owner', boundary: 'issuing a refund, changing fulfillment priority, or promising delivery', mistake: 'using a tracking status as proof that a customer outcome is settled', example: 'a parcel shows movement while the customer reports a missing delivery', signal: 'the owner sees the evidence and the unresolved operational choice', image: '/images/aug20-blog-order-exceptions.png', imageAlt: 'Remote assistant organizing ecommerce order exception records', published: '2026-08-20' },
  { slug: 'meeting-notes-that-preserve-decisions-and-open-questions', title: 'Meeting notes that preserve decisions and open questions', focus: 'meeting-note preparation', artifact: 'a source-linked note separating decisions, owners, and unresolved questions', owner: 'the meeting chair', boundary: 'inventing consensus, assigning a commitment, or rewriting a decision', mistake: 'turning a conversational possibility into an agreed action', example: 'three people discuss a launch date but nobody accepts ownership', signal: 'the chair can confirm what was decided without trusting a polished summary', image: '/images/aug20-blog-meeting-notes.png', imageAlt: 'Assistant separating meeting decisions and open questions in structured notes', published: '2026-08-20' },
  { slug: 'vendor-onboarding-checklists-with-approval-boundaries', title: 'Vendor onboarding checklists with approval boundaries', focus: 'vendor onboarding preparation', artifact: 'a readiness checklist showing supplied documents and missing approvals', owner: 'the procurement or operations owner', boundary: 'approving a vendor, accepting legal terms, or sharing broad internal access', mistake: 'treating document collection as approval to start the relationship', example: 'insurance evidence is present while the agreement is still under review', signal: 'readiness and approval are displayed as different states', image: '/images/aug20-blog-vendor-onboarding.png', imageAlt: 'Assistant tracking vendor onboarding documents and approval states', published: '2026-08-20' },
  { slug: 'content-calendar-handoffs-for-consistent-daily-publishing', title: 'Content-calendar handoffs for consistent daily publishing', focus: 'content-calendar handoff preparation', artifact: 'a publish packet with brief, sources, status, and reviewer questions', owner: 'the editorial lead', boundary: 'publishing unsupported claims, changing an approved angle, or declaring review complete', mistake: 'mistaking a finished draft for a finished editorial decision', example: 'a draft has a strong headline but one supporting statistic lacks a period', signal: 'the next reviewer knows exactly what is ready and what is blocked', image: '/images/aug20-blog-content-calendar.png', imageAlt: 'Editorial assistant organizing a daily content calendar and review packet', published: '2026-08-20' },
];

const sectionNames = ['Name the work unit', 'Preserve the source', 'Design the handoff', 'Write the stop rule', 'Use a reviewable queue', 'Limit access', 'Pilot with exceptions', 'Read the signals', 'Improve one instruction'];

function makePost(topic: Topic, index: number) {
  const paragraphs = [
    `On August 20, 2026, ${topic.focus} is a useful first lane for a Philippines-based remote assistant only when the finished result is explicit: ${topic.artifact}. The role is not a broad promise to manage every related request. It is a defined preparation service that makes online work easier for ${topic.owner} to inspect. Start by naming the event that creates the work, the record the assistant prepares, and the person who decides what happens next.`,
    `The first design question is what evidence must travel with the record. Preserve the original message, file, form response, or calendar entry, then record its received date and location. A normalized name or date may be helpful when the rule is written, but normalization must not erase the source. If information is absent, say that it is absent. A missing field tells the reviewer where uncertainty lives; an invented field hides it.`,
    `For this lane, the output is a handoff rather than an outcome. ${topic.artifact} should show what arrived, what was checked, what remains unknown, and what ${topic.owner} must decide. Keep source fact, assistant observation, open question, and owner decision in separate labels. That vocabulary helps a daily blog and research routine remain dependable because a neat note cannot be mistaken for proof, approval, or a business result.`,
    `${topic.example} illustrates why the boundary matters. The assistant can gather the supplied details, attach the original source, identify the gap, and prepare a neutral question. The assistant should stop before ${topic.boundary}. The stop is not a failure to help. It is the moment when the work changes from organizing evidence to exercising authority that belongs to ${topic.owner}.`,
    `A useful queue has states that describe reality: new, source checked, prepared for review, waiting for clarification, returned, and closed by the accountable person. Do not use closed merely because a draft exists. A closed item has a recorded decision or an explicit instruction that no further action is needed. State names should be short enough for daily use and precise enough that a new reviewer can understand them without private chat history.`,
    `Write one ordinary example, one incomplete example, and one boundary example before assigning the work. The ordinary example demonstrates the expected fields. The incomplete example shows how to preserve uncertainty. The boundary example demonstrates ${topic.mistake}. Examples are more useful than a sentence such as “use good judgment,” because they let the assistant and reviewer discuss a real record and identify the missing rule.`,
    `Access should match the smallest unit that produces ${topic.artifact}. Give the assistant the approved queue, source folder, or account view needed for preparation. Keep recovery controls, broad exports, private notes, payments, external commitments, and professional judgment with ${topic.owner}. Use named accounts, limited permissions, and a revocation path. Review the map after the first batch and remove anything that was convenient but not necessary.`,
    `Pilot the lane with varied work rather than a string of easy examples. Include a normal item, an incomplete item, and a case that reaches the stop rule. Review the source beside the prepared record. Count completed units, returned units, waiting items, missing fields, and corrections caused by unclear instructions. These are workflow observations, not promises about revenue, speed, or customer outcomes.`,
    `The daily check should ask whether the source is reachable, whether the record is traceable, whether the status matches the real state, and whether the next action has the right owner. ${topic.signal}. If the same question returns twice, improve one field definition, example, or permission before adding volume. A bigger queue amplifies ambiguity; it does not solve it.`,
    `Keep physical work, regulated interpretation, sensitive approvals, and outside promises in the accountable lane. A remote assistant can prepare digital information and route a question, but cannot become an on-site worker, licensed professional, or substitute decision-maker. If one request mixes routine preparation and judgment, split it into linked records so the evidence and decision remain visibly separate.`,
    `At the first weekly review, inspect one ordinary record, one returned record, and one escalation. Ask whether another reviewer could locate the source, distinguish fact from observation, see the unresolved question, and identify the next owner action. Record the reason for each correction. The goal is a teachable operating note, not a flattering scorecard.`,
    `At day 30, choose one of three changes: keep the lane narrow, clarify one rule, or add one adjacent duty. Do not add work merely because the original queue looks busy. A new task deserves its own source, output, access map, examples, and stop rule when its risk or decision owner changes. This keeps a Philippines-based remote assistant role fair and keeps the manager's review burden visible.`,
    `A route-specific handoff should be understandable without the private conversation that preceded it. Put the source link beside the normalized value, retain the original wording when it affects meaning, and label every unresolved item. For ${topic.focus}, the reviewer should identify the trigger, the prepared artifact, the exception state, and the decision owner in one pass. This matters when a daily routine crosses time zones or several people touch one queue. A clear record prevents the next assistant from mistaking familiarity with a process for permission to widen it.`,
    `Use a return reason that teaches the next pass. “Needs review” is too vague; name whether the source is missing, two records disagree, a required field is blank, or the request crosses ${topic.boundary}. The assistant can then correct the record or route a precise question. The owner can distinguish an instruction problem from an exceptional case. Over time, return reasons become a practical curriculum for hiring and training remote assistants who prepare digital work for HireAssistantNearMe readers and clients.`,
    `The safest completion signal is evidence plus disposition. A source-checked item has a reachable origin. A prepared item has the requested fields and clearly marked gaps. An escalated item states the unresolved decision and names ${topic.owner}. A closed item records what the owner decided or why the item was intentionally stopped. These distinctions keep ${topic.focus} from becoming a vague promise of “handling” work. They also give the editorial team a concrete way to explain a bounded assistant role in a daily blog article.`,
    `When the queue grows, preserve the same review order instead of hiding uncertainty in a larger spreadsheet. Sample early, inspect exceptions, and update the role brief only when the accountable owner accepts the new rule. Keep access changes separate from content changes so a convenient shortcut does not silently expose unrelated records. The central question remains simple: can another person verify the source, understand the assistant's preparation, and see where authority stops? For ${topic.focus}, that question is the quality control that makes an online handoff dependable.`,
  ];
  const sourceExpansion = [
    `Scope ${topic.focus} as a named queue, not as a general promise. The trigger is the approved message, record, invitation, request, or draft that enters the lane. The prepared result is ${topic.artifact}. The reviewer is ${topic.owner}. Write those three facts at the top of the role note so the assistant can tell a new item from an adjacent task. A queue that accepts every request creates hidden work, inconsistent judgment, and unclear ownership. A narrow queue gives the manager a practical way to compare the source with the prepared record and decide whether the instruction is complete.`,
    `For each ${topic.focus} item, preserve the source before extracting values. Record where the source came from, when it was received, and which person or system supplied it. Copying a value into a clean table is useful only when the original remains reachable. If two sources disagree, retain both, describe the disagreement, and place the item in a waiting or escalation state. Do not resolve the conflict by choosing the value that makes the queue look complete. The purpose of ${topic.artifact} is to make uncertainty visible to ${topic.owner}.`,
    `A practical record separates four kinds of information: source fact, assistant check, open question, and owner decision. For ${topic.focus}, source fact might be the exact request or date supplied. The assistant check might confirm that a required field is present or that two records refer to the same stated item. The open question names what cannot be established from the approved material. The owner decision records what ${topic.owner} authorized. Keeping these labels distinct prevents a prepared note from being mistaken for approval or a business commitment.`,
    `Use the boundary as an operating instruction. When a request reaches ${topic.boundary}, the assistant should stop the affected step, preserve the relevant source, state the unresolved fact, and route a concise question to ${topic.owner}. The stop rule should be visible in the queue rather than hidden in a private conversation. This protects the business from accidental commitments and gives the remote worker a fair answer to the question of what to do when the normal pattern breaks. A careful escalation is a completed preparation step, even when the final outcome is not yet known.`,
    `Design examples around the actual decisions in ${topic.focus}. An ordinary example shows a complete source and a normal ${topic.artifact}. An incomplete example shows a blank, conflicting, expired, or unreachable field and demonstrates the correct waiting state. A boundary example shows ${topic.mistake} and makes the escalation language explicit. Ask the assistant to explain which evidence supports each field. This turns training into a reviewable exercise and helps the owner discover whether an instruction is ambiguous before the queue grows.`,
    `The first access map should follow the artifact. The assistant needs only the approved source location and the queue or document where ${topic.artifact} is prepared. ${topic.owner} should retain recovery controls, broad exports, sensitive notes, external commitments, and the final decision. Use individual accounts, a named review owner, and a removal path. If the process requires a new permission, record why the existing access cannot produce the artifact and obtain approval before adding it. Convenience is not evidence that broader access is necessary.`,
    `Review a varied pilot for ${topic.focus}: one ordinary item, one item with missing information, and one item that reaches the stop rule. Compare each prepared record with its source. Note whether the assistant found the right source, preserved the original wording, used the expected status, and routed the unresolved question to ${topic.owner}. Track returned records and recurring clarification questions. Those observations reveal where the role brief needs a better example or field definition; they do not justify claims about revenue, speed, or customer outcomes.`,
    `At the daily review, inspect the oldest waiting item, one recently prepared item, and one exception. Confirm that every item has a source, a current status, and a next owner action. For ${topic.focus}, ${topic.signal}. If the same correction appears more than once, update one instruction and test it on a new sample before increasing volume. Keep the review small enough that the manager can read the evidence. A large unchecked queue hides the exact problem the handoff was meant to expose.`,
    `At the weekly review, ask whether a person who did not attend the original conversation could understand ${topic.artifact} from the record alone. If not, identify the missing source link, field definition, example, or ownership label. Keep changes to the role brief separate from changes to access. When the lane becomes reliable, expand only to an adjacent task with the same decision owner and similar risk. If the owner, evidence, or boundary changes, write a new lane instead of quietly broadening ${topic.focus}.`,
  ];
  const sourceBody = [...paragraphs, ...sourceExpansion].join(' ');
  const sections = sectionNames.map((heading, sectionIndex) => ({ heading, paragraphs: [paragraphs[(sectionIndex + index) % paragraphs.length], paragraphs[(sectionIndex + index + 4) % paragraphs.length]] }));
  return {
    slug: topic.slug, title: topic.title, mainKeyword: `${topic.focus} remote assistant`, excerpt: `A practical August 20, 2026 guide to ${topic.focus}, with a source-linked output, review path, and clear role boundary.`, published: topic.published, richPublished: true, minutes: 11, image: topic.image, imageAlt: topic.imageAlt,
    sourceBody, takeaways: [`Define ${topic.artifact}.`, `Keep source fact separate from owner decision.`, `Stop before ${topic.boundary}.`, `Review exceptions before expanding the lane.`],
    detail: { revision: `2026-08-20-${topic.slug}-r1`, directAnswer: paragraphs.slice(0, 2), bodyLinks: [{ href: '/blog', label: 'browse hiring guides' }], sections, decisionRows: [{ need: 'Repeatable online preparation', fit: 'Philippines-based remote assistant', reason: 'The source and finished record can be reviewed.' }, { need: 'Final approval or judgment', fit: topic.owner, reason: 'The accountable person retains the decision.' }, { need: 'Unclear exception', fit: 'Pause and escalate', reason: 'The assistant preserves evidence and questions.' }], planningNumbers: [{ value: '1 lane', label: 'First scope', note: topic.focus }, { value: '3 samples', label: 'Pilot set', note: 'Normal, incomplete, and boundary case.' }, { value: '1 owner', label: 'Decision path', note: topic.owner }, { value: '30 days', label: 'Review point', note: 'Clarify before expanding.' }], scripts: [{ title: 'Role brief', text: `Prepare ${topic.artifact}. Preserve the source and stop before ${topic.boundary}.` }, { title: 'Review question', text: `Which items are ready, returned, waiting, or blocked by a missing rule?` }], scenario: { title: `A bounded ${topic.focus} workflow`, intro: 'Use a small sequence that keeps evidence and authority visible.', steps: [{ step: '1', title: 'Receive', body: 'Preserve the original approved source.' }, { step: '2', title: 'Prepare', body: `Create ${topic.artifact}.` }, { step: '3', title: 'Check', body: 'Mark missing information and apply the stop rule.' }, { step: '4', title: 'Route', body: `Send the unresolved decision to ${topic.owner}.` }, { step: '5', title: 'Review', body: 'Change one instruction before adding scope.' }] }, faqs: [{ question: 'What should the assistant prepare?', answer: `The defined output: ${topic.artifact}.` }, { question: 'What stays with the owner?', answer: `${topic.owner} keeps ${topic.boundary}.` }, { question: 'How should the first scope be measured?', answer: 'Track completed, returned, waiting, and escalated records rather than making a result promise.' }, { question: 'Where are assistants recruited?', answer: 'This service recruits and hires assistants in the Philippines for remote work.' }, { question: 'When should the lane expand?', answer: 'Only after the owner reviews ordinary and exception cases and clarifies recurring questions.' }], relatedLinks: [{ href: '/blog', label: 'Browse all hiring guides' }, { href: '/research', label: 'Read the research hub' }, { href: '/contact-us', label: 'Prepare a role brief' }], sources: sourceLinks }
  };
}

export const aug20BlogPosts = topics.map(makePost);
