import * as data from './data';
const dataAny = data as any;
const site = dataAny.site || {};
const domain = site.domain || 'this site';
const year = new Date().getFullYear();

export function JsonLd({data}:{data: any}) { return <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(data)}}/>; }
export function LogoMark() { return <span className="logo-mark-wrap"><img className="logo-img" src="/logo.svg" alt="" aria-hidden="true"/><span className="logo-name"><b>Hire Assistant</b><small>Near Me</small></span></span>; }
export function Header() { return <header className="nav"><div className="nav-inner"><a className="logo" href="/" aria-label={`${site.brand || domain} home`}><LogoMark/></a><nav className="links" aria-label="Main navigation"><a href="/#roles">Assistant roles</a><a href="/compare/local-vs-remote-assistant">Local vs remote</a><a href="/blog">Hiring guides</a></nav><a className="btn nav-cta" href="/contact">Build my role brief</a></div></header>; }
export function Footer() { return <footer className="legit-footer"><div className="footer-grid"><div className="footer-brand"><a className="footer-logo" href="/" aria-label={`${site.brand || domain} home`}><LogoMark/></a><p>Sort out what the assistant should do, where the work can happen, and how you will check it.</p><p className="footer-note">We recruit and hire talent only in the Philippines. This is an independent informational website. Submitted requests may be routed to a suitable staffing team or service partner for follow-up.</p></div><div><h3>Plan the role</h3><div className="footer-links"><a href="/#roles">Assistant roles</a><a href="/compare/local-vs-remote-assistant">Local vs remote</a><a href="/blog/virtual-assistant-vs-employee">VA vs employee</a><a href="/contact">Contact</a></div></div><div><h3>Read and review</h3><div className="footer-links"><a href="/blog">Hiring guides</a><a href="/privacy">Privacy Policy</a><a href="/terms">Terms & Conditions</a><a href="/cancellation-policy">Cancellation Policy</a></div></div></div><div className="footer-bottom"><span>© {year} {site.brand || domain}. All rights reserved.</span><span>{domain}</span></div></footer>; }
export function CTA() { return <section className="final-cta"><p className="eyebrow">Start with the work</p><h2>Write the role before you hire.</h2><p>Tell us what keeps piling up, which tools it touches, and what the assistant must never approve alone.</p><a className="btn primary" href="/contact">Build my role brief</a></section>; }
