export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[] };

export const fleetServices: readonly FleetService[] = [
  { slug: 'executive-assistance', title: 'Executive Assistance', desc: 'Build a Philippines-based executive assistance workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring remote assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'calendar-and-inbox-support', title: 'Calendar and Inbox Support', desc: 'Build a Philippines-based calendar and inbox support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring remote assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'customer-service-assistance', title: 'Customer Service Assistance', desc: 'Build a Philippines-based customer service assistance workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring remote assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'sales-administrative-support', title: 'Sales Administrative Support', desc: 'Build a Philippines-based sales administrative support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring remote assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'ecommerce-assistance', title: 'Ecommerce Assistance', desc: 'Build a Philippines-based ecommerce assistance workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring remote assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'real-estate-assistance', title: 'Real Estate Assistance', desc: 'Build a Philippines-based real estate assistance workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring remote assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'marketing-coordination', title: 'Marketing Coordination', desc: 'Build a Philippines-based marketing coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring remote assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'bookkeeping-administration', title: 'Bookkeeping Administration', desc: 'Build a Philippines-based bookkeeping administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring remote assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'recruitment-assistance', title: 'Recruitment Assistance', desc: 'Build a Philippines-based recruitment assistance workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring remote assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'project-coordination', title: 'Project Coordination', desc: 'Build a Philippines-based project coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring remote assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

// Add reviewed, source-backed original research here. The templates and sitemap update automatically.
export const researchPosts: readonly ResearchPost[] = [];
export const postsPerPage = 20;
