import { Header, Footer, CTA } from './components';
import { site, roles, stats, blogPosts, faqs, compareRows, sourcePlaceholders, localMarkets, proofCards } from './data';

export default function Home() {
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((faq) => ({ '@type': 'Question', name: faq.question, acceptedAnswer: { '@type': 'Answer', text: faq.answer } })) };
  const serviceSchema = { '@context': 'https://schema.org', '@type': 'Service', name: 'Assistant hiring planning', provider: { '@type': 'Organization', name: site.brand, url: site.url }, areaServed: 'United States', serviceType: 'Virtual assistant hiring guidance' };

  return <><Header/><main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([serviceSchema, faqSchema]) }} />
    <section className="hero"><div className="container grid"><div><p className="eyebrow">hire assistant near me</p><h1>Hire an assistant near you without guessing.</h1><p className="lead">Get clear help comparing local assistants, U.S.-remote assistants, overseas virtual assistants, and managed assistant services.</p><p>This site is for busy local owners who need admin help, call support, inbox cleanup, scheduling, CRM updates, or follow-up work, but do not want a messy first hire.</p><div className="button-row"><a className="btn" href="/contact">Build my assistant plan</a><a className="btn secondary" href="/compare/local-vs-remote-assistant">Compare local vs remote</a></div></div><div className="hero-visual card"><img src="https://images.unsplash.com/photo-1551836022-deb4988cc6c0?auto=format&fit=crop&w=900&q=80" alt="Small business owner planning assistant coverage with a remote team"/><div className="map-card"><span className="pin">●</span><div><b>Near-me assistant plan</b><p>Local trust, remote coverage, simple first week.</p></div></div><div className="mini-grid"><span>Austin</span><span>Phoenix</span><span>Tampa</span><span>Charlotte</span></div></div></div></section>
    <section className="section" id="services"><div className="container"><p className="eyebrow">Services</p><h2>Assistant roles people compare most</h2><div className="cards">{roles.map((r)=><div className="card" key={r}><h3>{r}</h3><p>Good for repeatable work with a clear checklist, tool access, examples, and owner review.</p><span className="pill">SOP ready</span><span className="pill">Remote friendly</span></div>)}</div></div></section>
    <section className="section local-section"><div className="container"><div className="section-head"><div><p className="eyebrow">Local search guide</p><h2>Pick the right assistant path for your city.</h2></div><p>Owners search "assistant near me" because they want quick replies and local trust. These city examples show how to turn that search into a safer first role.</p></div><div className="location-grid">{localMarkets.map((market)=><article className="location-card" key={market.city}><div className="city-dot" aria-hidden="true"></div><h3>{market.city}</h3><p><b>Good fit:</b> {market.focus}</p><p><b>First tasks:</b> {market.tasks}</p><a className="text-link" href="/contact">Plan this role →</a></article>)}</div></div></section>
    <section className="section proof-section"><div className="container"><div className="cards">{proofCards.map((card)=><div className="card stat" key={card.label}><h3>{card.value}</h3><b>{card.label}</b><p>{card.note}</p></div>)}</div><p className="source-note">Source: U.S. Bureau of Labor Statistics, Occupational Employment and Wage Statistics, Secretaries and Administrative Assistants, May 2025.</p></div></section>
    <section className="section"><div className="container two"><div><p className="eyebrow">Near-me hiring</p><h2>“Near me” usually means trust, speed, and clear hours.</h2><p>You may not need someone sitting in your office. You may need someone who answers during your business day, knows the task, protects customer data, and asks before making a risky choice.</p><p>Use the comparison path to decide what should stay local, what can be remote, and what should wait until your instructions are stronger.</p><a className="text-link" href="/compare/local-vs-remote-assistant">Read the local vs remote guide →</a></div><div className="task-card card"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=800&q=80" alt="Local business team reviewing assistant tasks around a desk"/><h3>Best first assistant tasks</h3><ul className="list"><li>Inbox sorting and calendar cleanup</li><li>Lead follow-up and CRM updates</li><li>Call answering and appointment setting</li><li>Customer support replies</li><li>Simple reports, research, and admin</li></ul><p className="quote small">"Start small, measure weekly, then add more work."</p></div></div></section>
    <section className="section" id="pricing"><div className="container"><p className="eyebrow">Costs and timing</p><h2>Realistic ranges before you talk to providers</h2><div className="cards">{stats.map((s)=><div className="card stat" key={s.label}><h3>{s.value}</h3><b>{s.label}</b><p>{s.note}</p></div>)}</div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Comparison</p><h2>Four ways to hire assistant support</h2><div className="table"><div className="row"><b>Option</b><b>Best for</b><b>Watch out for</b></div>{compareRows.map((row)=><div className="row" key={row.option}><span>{row.option}</span><span>{row.bestFor}</span><span>{row.watch}</span></div>)}</div></div></section>
    <section className="section"><div className="container two"><div><p className="eyebrow">First-week plan</p><h2>Make the first week boring on purpose.</h2><p>A good first week is not about handing over everything. It is about proving the assistant can follow a checklist, ask good questions, and fix small mistakes fast.</p><ol className="list"><li>Pick 5 to 10 repeat tasks.</li><li>Record one example for each task.</li><li>Give limited tool access.</li><li>Review work daily for five days.</li><li>Score accuracy, speed, and communication.</li></ol></div><div className="card"><h3>Quote brief you can copy</h3><p className="quote small">“I need 10 to 20 hours a week for inbox cleanup, scheduling, CRM updates, and lead follow-up. I want a clear first-week plan, limited tool access, and weekly quality checks.”</p><a className="text-link" href="/contact">Send a planning request →</a></div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">FAQs</p><h2>Quick answers before you hire</h2><div className="cards">{faqs.slice(0,3).map((faq)=><div className="card" key={faq.question}><h3>{faq.question}</h3><p>{faq.answer}</p></div>)}</div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Guides</p><h2>Start with these hiring guides</h2><div className="cards">{blogPosts.slice(0,3).map((p)=><a className="card" href={`/blog/${p.slug}`} key={p.slug}><h3>{p.title}</h3><p>{p.excerpt}</p><span className="pill">{p.minutes} min read</span></a>)}</div></div></section>
    <section className="section"><div className="container"><div className="card"><p className="eyebrow">Source placeholders</p><h2>Claims to verify before paid launch</h2><p>These references are included as editorial placeholders so future updates can verify wage, worker-classification, and business-guidance claims.</p><ul className="list">{sourcePlaceholders.map((source)=><li key={source.url}><a className="text-link" href={source.url}>{source.name}</a> — {source.note}</li>)}</ul></div></div></section>
    <CTA />
  </main><Footer/></>;
}
