import type { ResearchPost } from './fleet-data';

const published = '2026-09-22';
const checked = 'September 22, 2026';

type Study = {
  slug:string; title:string; excerpt:string; image:string; lane:string; serviceHref:string;
  question:string; decision:string; sample:string; finding:string; risks:string; sourceUse:string;
  sources:readonly (readonly [string,string])[];
};

const studies:readonly Study[] = [
  {
    slug:'executive-assistant-inbox-account-recovery-boundary',
    title:'Executive inbox access: where should an assistant stop around account recovery?',
    excerpt:'A least-privilege decision map for inbox preparation, authentication prompts, recovery settings, and executive-only messages.',
    image:'/images/assistant-maya.jpg', lane:'Executive assistance', serviceHref:'/services/executive-assistance',
    question:'How can a small business delegate routine executive inbox preparation without giving a remote assistant control of account recovery, authentication factors, private personnel messages, or business commitments?',
    decision:'Separate message work from identity administration. An assistant may label, summarize, and draft from approved examples, but recovery methods, password resets, multifactor enrollment, mailbox-wide exports, security alerts, private staff matters, and final commitments should remain with named accountable owners.',
    sample:'twenty-two fictional inbox events: ordinary newsletters, meeting requests, customer follow-ups, an invoice change, three password-reset notices, a multifactor prompt, a suspected phishing message, a private staff concern, and a request to export the mailbox',
    finding:'The clearest boundary used both a message category and an allowed verb. A label such as routine did not authorize sending, deleting, exporting, changing security settings, or resolving a warning.',
    risks:'sharing a recovery factor, approving an unexpected sign-in, deleting evidence of a security event, exposing private personnel content, treating a draft as permission to send, and letting broad mailbox access become account-administration authority',
    sourceUse:'NIST guidance explains multifactor authentication and limiting access to job need. CISA guidance supplies the stop-and-report rationale for suspected phishing. NIST SP 800-53 AC-6 supplies the least-privilege principle used to separate mailbox preparation from account administration.',
    sources:[['NIST, Multi-Factor Authentication for Small Business','https://www.nist.gov/itl/smallbusinesscyber/guidance-topic/multi-factor-authentication'],['CISA, Recognize and Report Phishing','https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'],['NIST SP 800-53 Rev. 5, AC-6 Least Privilege','https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final']]
  },
  {
    slug:'calendar-assistant-booking-authority-record',
    title:'Calendar support: what should a booking-authority record contain?',
    excerpt:'A practical record for separating available time, proposed time, approved time, and commitments across local and Philippines work hours.',
    image:'/images/calendar-assistant.jpg', lane:'Calendar and inbox support', serviceHref:'/services/calendar-and-inbox-support',
    question:'Which evidence lets a Philippines-based calendar assistant coordinate meetings while keeping sensitive priorities, attendee promises, exceptions, and final conflict decisions with the owner?',
    decision:'Record the named time zone, source of availability, attendee constraints, meeting purpose, approval state, and exception owner for every booking. Availability is an input, not authority to commit a person, disclose a private calendar entry, or override an owner rule.',
    sample:'twenty fictional meeting requests spanning four IANA time zones, daylight-saving changes, tentative holds, private blocks, travel buffers, double-booking conflicts, an urgent customer request, and a request to reveal another attendee’s calendar details',
    finding:'A proposed slot remained reconstructable when its zone, source, approval state, and constraint were preserved. A bare time or an apparently empty calendar cell did not show who could commit the slot.',
    risks:'converting a tentative hold into a promise, dropping the time-zone identifier, revealing private event details, ignoring travel or preparation buffers, choosing between conflicting priorities, and silently changing an executive’s scheduling rule',
    sourceUse:'The IANA database establishes named time-zone rules and updates. NIST log guidance informs preservation of timestamps and event context. The NIST Privacy Framework supplies the purpose-and-risk vocabulary used to minimize calendar details in handoffs.',
    sources:[['IANA Time Zone Database','https://www.iana.org/time-zones'],['NIST SP 800-92, Guide to Computer Security Log Management','https://csrc.nist.gov/pubs/sp/800/92/final'],['NIST Privacy Framework','https://www.nist.gov/privacy-framework']]
  },
  {
    slug:'customer-support-complaint-evidence-handoff',
    title:'Customer support complaints: what evidence should an assistant preserve before escalation?',
    excerpt:'A complaint-handoff method that keeps the customer’s words, order or account evidence, prior promises, and decision owner visible.',
    image:'/images/assistant-elena.jpg', lane:'Customer service assistance', serviceHref:'/services/customer-service-assistance',
    question:'How can a remote customer-service assistant prepare a complaint for fast review without changing the customer’s meaning, inventing a remedy, suppressing criticism, or closing a dispute beyond delegated authority?',
    decision:'Preserve the customer’s material statement, channel, receipt time, related record, prior promises, requested outcome, safety or legal signal, and current owner. The assistant may acknowledge receipt and organize evidence from approved systems; refunds, admissions, review moderation, policy exceptions, and final resolution stay with authorized owners.',
    sample:'twenty-six fictional complaints covering delayed orders, duplicate charges, service dissatisfaction, a safety allegation, an accessibility request, abusive language, an online review, conflicting account notes, and demands for refunds outside the published policy',
    finding:'A short neutral summary was useful only when it remained linked to the original message and prior business record. Removing emotional language sometimes removed facts about urgency, harm, or the remedy the customer requested.',
    risks:'rewriting a complaint into a more convenient category, promising a refund, deleting negative feedback, copying sensitive data into a broad queue, losing earlier promises, closing an unresolved case, and treating response speed as proof of resolution',
    sourceUse:'FTC review guidance informs truthful handling of consumer feedback and transparency about moderation practices. NIST privacy guidance informs purpose-limited handling of complaint data. NIST incident guidance supports escalating safety or security signals through a named response path rather than improvising a remedy.',
    sources:[['Federal Trade Commission, Featuring Online Customer Reviews: A Guide for Platforms','https://www.ftc.gov/business-guidance/resources/featuring-online-customer-reviews-guide-platforms'],['NIST Privacy Framework','https://www.nist.gov/privacy-framework'],['NIST SP 800-61 Rev. 3, Incident Response Recommendations and Considerations','https://csrc.nist.gov/pubs/sp/800/61/r3/final']]
  },
  {
    slug:'real-estate-assistant-listing-data-source-control',
    title:'Real-estate listing administration: which source should control each field?',
    excerpt:'A source-to-field worksheet for preparing listing records while licensed, contractual, pricing, and disclosure decisions stay local.',
    image:'/images/assistant-elena.jpg', lane:'Real estate assistance', serviceHref:'/services/real-estate-assistance',
    question:'How can a real-estate team delegate digital listing preparation without asking a remote assistant to infer property facts, interpret agreements, choose price, make disclosures, or decide what a client has authorized?',
    decision:'Map every prepared field to a supplied source, observation date, permitted transformation, reviewer, and conflict rule. An assistant may transfer and format approved facts; a broker, agent, client, or other accountable professional must decide disputed facts, price, representation, disclosures, contract meaning, and publication approval.',
    sample:'eighteen fictional listing packets containing owner-supplied facts, public-record extracts, photographs, conflicting room counts, an outdated description, a proposed price change, a missing disclosure, accessibility language, and an instruction to copy claims from another listing',
    finding:'Field-level provenance exposed conflicts that a polished listing draft concealed. The worksheet did not determine which source was legally controlling; it made the unresolved choice visible to the responsible reviewer.',
    risks:'copying an unsupported property claim, changing a price without approval, treating a public record as current truth, editing disclosure language, reusing copyrighted media, adding discriminatory audience language, and publishing before the licensed or accountable owner reviews the record',
    sourceUse:'HUD fair-housing advertising guidance informs the boundary around discriminatory preferences. NARA naming guidance supports consistent identifiers and version context for supplied files. FTC advertising guidance supplies the general requirement that objective claims have a reasonable basis before dissemination.',
    sources:[['HUD, Advertising and Marketing under the Fair Housing Act','https://www.hud.gov/helping-americans/fair-housing-act-overview'],['National Archives, Bulletin 2015-01 Appendix B: File and Folder Naming','https://www.archives.gov/records-mgmt/bulletins/2015/2015-01-appendix-b.html'],['Federal Trade Commission, Advertising and Marketing Basics','https://www.ftc.gov/business-guidance/advertising-marketing']]
  },
  {
    slug:'marketing-assistant-testimonial-substantiation-handoff',
    title:'Marketing coordination: what must accompany a testimonial before publication?',
    excerpt:'A substantiation and approval handoff for testimonials, reviews, material connections, edits, and performance claims.',
    image:'/images/local-team.jpg', lane:'Marketing coordination', serviceHref:'/services/marketing-coordination',
    question:'What record should a marketing assistant prepare before a business republishes a customer testimonial or review, especially when the text is edited, incentivized, or paired with a performance claim?',
    decision:'Keep the original statement, permission record, identity and experience checks defined by the business, material-connection disclosure, edit history, claim substantiation, placement, expiration or recheck date, and final approver together. An assistant may assemble this record but should not invent permission, suppress material context, or approve the public claim.',
    sample:'twenty fictional testimonial candidates including unsolicited praise, incentivized reviews, staff and family comments, edited quotations, extraordinary outcome claims, anonymous feedback, expired permission, missing source links, and one negative review proposed for deletion',
    finding:'The publication decision became reviewable when the original, edits, connection, permission, and claim evidence traveled together. A polished quotation alone concealed the facts the approver needed most.',
    risks:'changing the meaning while shortening a quotation, omitting an incentive or relationship, presenting an unusual result as typical, fabricating permission, publishing unsupported performance claims, exposing customer data, and deleting legitimate criticism to improve a rating',
    sourceUse:'The FTC Endorsement Guides establish principles for endorsements, material connections, and consumer interpretation. FTC review guidance addresses collection and moderation practices. FTC advertising materials inform the substantiation boundary for objective claims.',
    sources:[['Federal Trade Commission, Endorsement Guides','https://www.ftc.gov/business-guidance/advertising-marketing/endorsements-influencers-reviews'],['Federal Trade Commission, Featuring Online Customer Reviews: A Guide for Platforms','https://www.ftc.gov/business-guidance/resources/featuring-online-customer-reviews-guide-platforms'],['Federal Trade Commission, Advertising and Marketing Basics','https://www.ftc.gov/business-guidance/advertising-marketing']]
  }
];

function makePost(s:Study):ResearchPost {
  const sourceNames=s.sources.map(([name])=>name).join('; ');
  return {slug:s.slug,title:s.title,excerpt:s.excerpt,published,image:s.image,imageAlt:`Decision worksheet for ${s.title.toLowerCase()}`,
    keyStats:[{value:'1',label:'Named decision owner required',source:'Study method'},{value:'3',label:'Authoritative sources checked',source:'Source ledger'},{value:'0',label:'Customer or worker outcomes measured',source:'Study boundary'}],
    takeaways:[s.decision,'Test both ordinary work and exceptions before expanding access or authority.','Keep source facts, analysis, owner decisions, and uncertainty visibly separate.'],
    sections:[
      {heading:'Research question and buyer decision',body:`${s.question} This report addresses that narrow buyer decision for a local business considering ${s.lane.toLowerCase()} from a Philippines-based remote assistant. It does not ask whether remote work is universally effective or whether a particular person is qualified. The operational conclusion is: ${s.decision} This is a source-informed analysis and bounded fictional exercise, not a promise about a candidate, service, tool, compliance posture, or business result.`},
      {heading:'Methodology, sample, and observation window',body:`The unit of analysis was one task decision within ${s.sample}. We reviewed the constructed cases on ${checked}. Before examining each case, we recorded the controlling source, permitted verb, expected evidence, stop condition, decision owner, and minimum handoff. The set deliberately mixed ordinary work with missing information, conflicts, urgency, sensitive information, and requests outside the proposed role. We asked whether a second reviewer could reconstruct what the assistant saw, what the rule allowed, what remained uncertain, and who owned the next action. No Hire Assistant Near Me customer, candidate, employee, assistant, private record, production account, revenue result, or service outcome was observed. We calculated no rate, productivity gain, effect size, statistical significance, or causal relationship.`},
      {heading:'What the authoritative sources establish',body:`The source set was checked on ${checked}: ${sourceNames}. ${s.sourceUse} The publishers did not study Hire Assistant Near Me, compare staffing providers, endorse remote assistance, or validate this workflow. Their materials establish definitions, duties, risks, or control principles only within their stated scope. Applying those principles to the task lane is our analysis. A later editor should open each linked source, confirm its status and scope, record a new checked date, and revise any conclusion affected by a changed rule or definition.`},
      {heading:'Observed finding in the constructed cases',body:`${s.finding} Across the sample, access to information never created authority to make every decision involving that information. Familiar-looking work changed character when a source was missing, contradictory, sensitive, or tied to an external commitment. A stopped case with a precise handoff was more reviewable than a polished output that hid an assumption. The owner response path also mattered: an escalation rule without an available decision owner merely moved uncertainty into an aging queue. These observations describe the fictional cases only. They are hypotheses for a protected pilot, not evidence of prevalence, worker performance, customer satisfaction, legal compliance, cost savings, or commercial value.`},
      {heading:'Define the lane by verbs, not job title',body:`Write the role as observable verbs: view, collect, copy, label, standardize, draft, edit, send, delete, export, approve, pay, publish, or administer. Attach each permitted verb to an approved source and completion record. Then name the prohibited or owner-held action beside it. A broad title such as ${s.lane.toLowerCase()} cannot show whether the person may change a field, communicate externally, resolve an exception, or alter access. Examples help only when they include near-boundary cases. The instructions should state what to do when the supplied example and the live record differ, rather than rewarding a guess that happens to look tidy.`},
      {heading:'Build the minimum evidence handoff',body:`A useful handoff identifies the work item without copying unnecessary sensitive information. It records the source location, observation time and named time zone, last permitted action, exact missing or conflicting fact, decision requested, current owner, and due time. When a change needs review, preserve the prior value and the proposed value. Link to the approved system of record when possible instead of building a shadow database in comments. Apply the business’s retention and access rules, and keep credentials, authentication secrets, payment data, and unrelated personal information out of general notes. Another reviewer should understand the stop without requiring the assistant to reconstruct events from memory.`},
      {heading:'Pilot with routine and exception cases',body:`Start with a small representative sample and deliberately include ordinary items, incomplete inputs, conflicting records, an urgent request, sensitive information, and an action beyond authority. Freeze the instruction version and review rubric for one comparison window. Score source fidelity, correct action, correct stop, evidence preservation, and handoff completeness separately. Count false stops as well as unsafe continuation. Excessive escalation can make a lane unusable, while continuing through uncertainty can create larger business risk. Review disagreements at the rule level: determine whether the source, example, wording, tool permission, or owner response path needs correction before granting broader access.`},
      {heading:'Risks and safeguards',body:`The principal risks in this lane are ${s.risks}. Address them with named accounts, least-privilege permissions, multifactor authentication where available, approved systems of record, examples that include stop cases, and a decision owner available during agreed working hours. Separate quality review from blame. A correction log should identify the evidence gap and instruction revision, not encourage quiet rework that erases the history. Do not measure success only by item count or response speed. Include unsafe continuations, unnecessary escalations, unresolved queue age, evidence completeness, and owner review time so one favorable number does not conceal transferred work or risk.`},
      {heading:'Buyer checklist before hiring',body:`Before hiring, list the recurring work and the systems it touches. Mark actions that create commitments, alter money or access, expose sensitive information, interpret policy, or communicate publicly. Choose which of those stay with the local owner. Prepare representative examples and counterexamples, confirm the source of truth for each field, and name the reviewer for every stop condition. Ask a candidate to explain uncertainty and prepare a handoff, not merely finish the happy-path task. Confirm overlap hours and time-zone notation. Decide how access will be granted, reviewed, and removed. A strong work sample demonstrates restraint, provenance, and clear escalation as well as accurate routine execution.`},
      {heading:'Limitations and uncertainty',body:`This exercise used fictional records, a designed sample, and one analytical framework. It cannot estimate how often these exceptions occur, whether another reviewer would classify them the same way, how a particular software product enforces permissions, or whether a live business has met legal, contractual, professional, security, privacy, accessibility, employment, or records obligations. The cited guidance may change, and jurisdiction-specific rules may add duties not discussed here. Source authority does not guarantee source fit. A real pilot must use appropriately protected data, qualified review where needed, and an accountable owner who can pause the lane when the evidence is inadequate.`},
      {heading:'Conclusion and next decision',body:`For ${s.lane.toLowerCase()}, the practical hiring question is not whether an assistant can touch the tool. It is whether the business can define a permitted action, trustworthy source, completion record, stop condition, and reachable owner. ${s.decision} The constructed cases suggest testing this boundary before widening permissions or output volume. Preserve disagreements and false stops, revise the written rule, and retest on a fresh sample. Expansion should follow demonstrated evidence fidelity and recoverable handoffs, not a job title, a fast first batch, or confidence unsupported by the record.`}
    ],
    tables:[{caption:'Task authority and evidence boundary',columns:['Element','Assistant preparation','Owner decision'],rows:[['Source','Link the approved record and checked time','Decide conflicts or source authority'],['Action','Use only the permitted verb','Approve commitments and exceptions'],['Handoff','State evidence, uncertainty, and next owner','Resolve or pause the case'],['Expansion','Supply pilot evidence and correction notes','Change access, policy, or authority']]}],
    sources:s.sources.map(([name,url])=>({name,url})),related:[{label:`${s.lane} service`,href:s.serviceHref},{label:'Research library',href:'/research'},{label:'Build a role brief',href:'/contact-us'}]
  };
}

export const sep22Hira92ResearchPosts:ResearchPost[]=studies.map(makePost);
