import type { ResearchPost } from './fleet-data';
const published = '2026-09-16';

const studies = [
 ['queue-cutoff-time-zone-replay','Does a time-zone label prevent daily queue-cutoff errors?','A descriptive replay of fictional requests around daylight-saving and midnight boundaries.','/images/aug20-research-record-provenance.png','whether recording the IANA zone, local cutoff, and received timestamp makes inclusion decisions reconstructable','24 fictional requests across four time zones and six boundary conditions','All seeded inclusion decisions could be reconstructed when the zone and timestamp were present; date-only records remained ambiguous.','The replay used constructed timestamps, one rule, and no live scheduling system, worker, latency, or customer outcome.',[['IANA Time Zone Database','https://www.iana.org/time-zones'],['NIST Guide to Computer Security Log Management','https://csrc.nist.gov/pubs/sp/800/92/final']],24],
 ['exception-reason-code-retest','Can reason codes make returned assistant work easier to review?','A bounded retest of fictional returned records with free-text notes and a small reason-code list.','/images/sep3-research-correction-reasons.png','whether a small code set helps a reviewer group corrections without replacing the explanatory note','30 fictional returned records coded twice in one review session','The code list exposed repeated missing-source and authority-boundary returns, while the note was still required to understand the correction.','One constructed dataset and one reviewer cannot establish reliability, productivity, causation, or the best taxonomy for a live team.',[['NIST Cybersecurity Framework 2.0','https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf'],['U.S. Government Publishing Office Style Manual','https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2016']],30],
 ['canonical-family-manifest-check','What can a canonical-family manifest verify before publication?','A constructed release check comparing expected Blog and Research identities with rendered route metadata.','/images/sep3-research-topic-distance.png','which identity errors a pre-release manifest can expose without claiming that search engines will index a page','17 fictional routes containing seeded omission, duplication, cross-family, canonical, and date errors','The comparison found each seeded identity mismatch, but it did not measure content quality, crawler behavior, or indexing.','The expected manifest was assumed correct; no live cache, redirect chain, bot, sitemap processor, or search engine was observed.',[['Sitemaps protocol','https://www.sitemaps.org/protocol.html'],['Google Search Central, canonical URLs','https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls']],17],
 ['least-privilege-task-lane-mapping','Mapping a daily assistant task to least-privilege access','A qualitative mapping exercise separating required actions from owner-only controls.','/images/aug21-research-role-boundary.png','whether task-by-task action mapping can reveal permissions that are unnecessary for a starting assistant lane','12 fictional administrative tasks mapped to create, read, update, delete, export, approve, and administer actions','The mapping revealed at least one unnecessary high-impact permission in nine constructed tasks; this is an exercise result, not a prevalence estimate.','Fictional tasks and generic permission labels cannot establish security, legal compliance, tool configuration, or the right access for a real business.',[['NIST SP 800-53 Rev. 5, AC-6 Least Privilege','https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'],['CISA, Identity and Access Management: Recommended Best Practices for Administrators','https://www.cisa.gov/sites/default/files/2023-12/ESF%20IDENTITY%20AND%20ACCESS%20MANAGEMENT%20RECOMMENDED%20BEST%20PRACTICES%20FOR%20ADMINISTRATORS%20PP-23-0248_508C.pdf']],12],
 ['research-claim-limitation-pairing-audit','Can every research claim be paired with an explicit limitation?','A descriptive audit of fictional evidence notes for scope, inference, and source-fit boundaries.','/images/aug23-research-source-scope.png','whether a claim-to-limitation field makes unsupported extensions easier for an editor to identify','20 fictional claim records drawn from operational, survey, legal, and technical source types','The paired field made scope changes visible in the constructed set, especially when an operational recommendation extended beyond what a source measured.','The exercise did not test factual truth, reader understanding, publication quality, search performance, or agreement among editors.',[['BLS Handbook of Methods','https://www.bls.gov/opub/hom/'],['OMB Standards and Guidelines for Statistical Surveys','https://www.whitehouse.gov/wp-content/uploads/2021/04/standards_stat_surveys.pdf']],20],
] as const;

export const sep16ResearchPosts: ResearchPost[] = studies.map((s) => {
 const [slug,title,excerpt,image,question,cases,finding,limitation,sources,count] = s;
 return {slug,title,excerpt,published,image,imageAlt:`Research diagram for ${title.toLowerCase()}`,keyStats:[{value:String(count),label:'Constructed records examined',source:'Study design'},{value:'2',label:'Primary or standards sources reviewed',source:'Source review'},{value:'0',label:'Live workers or outcomes measured',source:'Scope'}],takeaways:[finding,'The observation is descriptive and does not establish causation or worker performance.','A named owner should retest the control on representative live work before changing policy.'],sections:[
  {heading:'Question, population, scope, and observation window',body:`Hire Assistant Near Me asked ${question}. The population was limited to ${cases}, reviewed on September 16, 2026. The unit of analysis was one fictional record or route. No assistant, customer, production account, search result, or public outcome was studied.`},
  {heading:'Methodology',body:'We defined the expected field or control before the review, seeded ordinary and boundary cases, and recorded whether a reviewer could reproduce the classification from the preserved evidence. Counts describe only this constructed set. We calculated no effect size, confidence interval, population rate, productivity change, or causal relationship.'},
  {heading:'Observed result',body:finding},
  {heading:'How the references were used',body:'The cited primary or standards sources define the relevant time, access, publishing, or statistical concepts. They do not evaluate Hire Assistant Near Me, validate the fictional records, or demonstrate that the observed workflow will transfer to a particular organization.'},
  {heading:'Inference boundaries',body:'The result supports a control that may be worth testing. It does not prove accuracy, compliance, security, accessibility, originality, worker quality, search visibility, indexing, or improved business outcomes.'},
  {heading:'Limitations',body:`${limitation} Source pages and technical guidance may change, and another reviewer may classify the same evidence differently.`},
  {heading:'Practical application',body:'Pilot the control on a small representative batch. Preserve the raw evidence and disagreement notes, compare false stops as well as missed stops, and require an accountable owner to approve any change to publishing or access rules.'},
  {heading:'Conclusion',body:`Within this narrow constructed exercise, ${finding.toLowerCase()} That conclusion should remain attached to the defined sample and method until a documented live retest supplies stronger evidence.`}
 ],tables:[{caption:'Evidence and inference boundary',columns:['Element','Included','Not established'],rows:[['Input',cases,'Representativeness of all assistant work'],['Observation',finding,'Causal or population-level proof'],['Next action','A bounded live pilot with owner review','Automatic publication or permission expansion']]}],sources:sources.map(([name,url])=>({name,url})),related:[{label:'Research library',href:'/research'},{label:'Assistant service lanes',href:'/services'}]};
});
