import type { ResearchPost } from './fleet-data';
const published = '2026-09-09';

const studies = [
 ['exception-reason-codes-editorial-handoff','Do reason codes make editorial exceptions easier to review?','A constructed comparison of free-text holds and a small, defined reason-code set in daily publishing handoffs.','/images/sep3-research-correction-reasons.png','whether reason codes expose recurring handoff failures without hiding the original note','twelve fictional article exceptions split across missing source, date conflict, asset failure, and owner decision','Reason codes made repeated failure types easier to count, while retaining free text was necessary to preserve case-specific context.','The records were fictional, one reviewer applied the codes, and no publication-speed or quality outcome was measured.',[['NIST, Information Quality Standards','https://www.nist.gov/nist-information-quality-standards'],['W3C PROV Overview','https://www.w3.org/TR/prov-overview/']],12],
 ['timezone-labels-content-cutoff-study','What does an explicit time-zone label add to a content cutoff?','A bounded desk test of publication handoffs that showed a clock time with and without a named time zone.','/images/aug21-research-calendar-context.png','whether a named time zone reduces ambiguity in a daily release record','eight fictional handoffs spanning UTC, Eastern, and Philippine time references','The named-zone records made the intended instant reproducible; a clock time alone remained ambiguous across locations and daylight-saving rules.','This was a document comparison, not a live scheduling trial, and it did not evaluate every civil-time edge case.',[['IANA Time Zone Database','https://www.iana.org/time-zones'],['W3C, Date and Time Formats','https://www.w3.org/TR/NOTE-datetime']],8],
 ['hero-og-image-parity-release-check','Can a hero-to-OG image parity check strengthen a release audit?','A constructed route audit comparing rendered hero images, Open Graph metadata, and direct asset responses.','/images/aug20-research-record-provenance.png','whether checking three image surfaces catches failures missed by inspecting the article page alone','ten fictional route records with missing metadata, broken assets, mismatched URLs, and complete image pairs','The three-surface check exposed broken or inconsistent image evidence, but visual parity did not prove relevance, accessibility, or licensing.','No social platform crawler was tested, and the exercise used constructed route records rather than a live campaign.',[['Open Graph protocol','https://ogp.me/'],['WHATWG HTML Living Standard, Images','https://html.spec.whatwg.org/multipage/images.html']],10],
 ['self-canonical-slug-manifest-comparison','Testing self-canonical URLs against an approved slug manifest','A qualitative release test of canonical tags when routes, manifest slugs, and redirects disagree.','/images/sep3-research-source-change.png','whether direct comparison with an approved manifest identifies canonical identity conflicts','nine fictional pages covering exact matches, cross-canonicals, redirected slugs, and missing tags','The manifest comparison identified identity conflicts that a 200-status check alone would accept; it did not show how search engines would index the pages.','The study did not observe crawling or ranking, and redirect behavior was represented rather than deployed.',[['Google Search Central, Canonical URLs','https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls'],['RFC 9110: HTTP Semantics','https://www.rfc-editor.org/rfc/rfc9110']],9],
 ['body-fingerprint-daily-article-identity','Can body fingerprints detect accidental reuse in a daily article batch?','A constructed comparison of exact hashes and normalized text similarity for distinct, duplicated, and lightly altered drafts.','/images/sep3-research-counterevidence.png','which checks reveal reused article identity without treating every shared phrase as duplication','fifteen fictional drafts containing exact copies, boilerplate, reordered paragraphs, and genuinely distinct articles','Exact hashes found identical bodies, while normalized comparison surfaced lightly altered reuse for human review; neither method independently established editorial originality.','Thresholds were selected for the exercise, the corpus was small, and no plagiarism or authorship conclusion was attempted.',[['NIST, Secure Hash Standard','https://csrc.nist.gov/pubs/fips/180-4/upd1/final'],['U.S. Copyright Office, Copyright Basics','https://www.copyright.gov/circs/circ01.pdf']],15],
] as const;

export const sep9ResearchPosts: ResearchPost[] = studies.map((s) => {
 const [slug,title,excerpt,image,question,cases,finding,limitation,sources,count] = s;
 return {slug,title,excerpt,published,image,imageAlt:`Research illustration for ${title.toLowerCase()}`,keyStats:[{value:String(count),label:'Constructed records examined',source:'Study design'},{value:'2',label:'Reputable context sources',source:'Source review'},{value:'0',label:'Live workers or ranking outcomes measured',source:'Scope'}],takeaways:[finding,'The observation is a workflow hypothesis, not a causal or performance claim.','A release owner should repeat the check on representative live work.'],sections:[{heading:'Research question and scope',body:`Hire Assistant Near Me asked ${question}. The exercise used ${cases} in the context of a proper daily blog and research routine. The record or draft was the unit of analysis; no assistant, editor, customer, or search result was evaluated.`},{heading:'Methodology',body:'We held the underlying case facts constant, prepared the comparison states described above, and recorded what a reviewer could verify, what remained ambiguous, and which decision still needed an accountable owner. The review was qualitative and descriptive. No statistical effect, causal relationship, productivity change, or general population estimate was calculated.'},{heading:'Observed result',body:finding},{heading:'How the sources were used',body:'The cited materials provide standards, protocol, or operating context for the fields being compared. They do not study Hire Assistant Near Me, validate the constructed sample, or establish that this result transfers to a different workflow.'},{heading:'Inference limits',body:'The observation supports testing a release control. It does not establish worker quality, legal compliance, accessibility, originality, search indexing, ranking, security, or the correct policy for a particular organization.'},{heading:'Limitations',body:`${limitation} Source pages and technical behavior can change, and a later editor may classify the same evidence differently.`},{heading:'Practical implication',body:'Pilot the check on a small representative batch. Preserve the underlying evidence, record disagreements, and require a named publication owner to resolve exceptions before changing access or release policy.'},{heading:'Conclusion',body:`Within this narrow constructed exercise, ${finding.toLowerCase()} Further live testing with documented review criteria is required.`}],tables:[{caption:'Study boundary',columns:['Element','Included','Not established'],rows:[['Input',cases,'Representativeness of all publishing work'],['Observation',finding,'Causal or statistical proof'],['Next decision','A control to test on a real batch','Final publication or permission policy']]}],sources:sources.map(([name,url])=>({name,url})),related:[{label:'Research library',href:'/research'},{label:'Content support services',href:'/services/content-support'}]};
});
