import type { ResearchPost } from './fleet-data';

const published = '2026-09-02';
const image = '/images/aug21-research-evidence-map.png';
const related = [{label:'Research library',href:'/research'},{label:'Executive assistance',href:'/services/executive-assistance'}];
const commonSources = [{name:'W3C PROV Overview',url:'https://www.w3.org/TR/prov-overview/'},{name:'NIST SP 800-53 Rev. 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'}];
type Study = {slug:string;title:string;excerpt:string;question:string;unit:string;signal:string;risk:string;method:string;finding:string;boundary:string;rows:string[][]};
const studies: Study[] = [
  {slug:'review-owner-clarity-in-daily-editorial-work',title:'Review-owner clarity in daily editorial work: a responsibility-state model',excerpt:'A desk study of how named ownership changes the interpretability of evidence, copy, and release queues.',question:'What record distinguishes a named reviewer from a person who is merely available?',unit:'one article gate linked to an accountable owner, requested decision, response window, and current evidence',signal:'whether a reviewer can identify who must decide and when the item becomes an exception',risk:'assigning several watchers while leaving final authority ambiguous',method:'The analysis compares unowned, group-owned, delegated, and explicitly accepted review states.',finding:'Ownership is operational only when the decision, person, evidence, and response window appear together.',boundary:'An assistant may maintain assignments; the accountable editor accepts or reassigns authority.',rows:[['Name only','Potential contact','Accepted responsibility'],['Decision requested','Needed judgment','Decision quality'],['Response window','Expected timing','Business priority'],['Acceptance record','Owner acknowledged','Future availability']]},
  {slug:'version-lineage-for-fast-moving-article-drafts',title:'Version lineage for fast-moving article drafts',excerpt:'A provenance analysis of draft identity, reviewer decisions, and the risk of restoring rejected claims.',question:'Which minimum fields let an editor trace a live-ready draft through substantive revisions?',unit:'one immutable draft version connected to its author, change reason, evidence state, and reviewer decision',signal:'the ability to reconstruct why current wording replaced the prior version',risk:'overwriting drafts or separating comments from the version they evaluated',method:'The study follows four revisions through copy, factual, scope, and release changes.',finding:'A version number becomes useful only when it preserves the decision and evidence that produced the next version.',boundary:'The assistant records lineage; editors approve factual meaning and the release candidate.',rows:[['Version ID','Artifact identity','Whether wording is correct'],['Change reason','Why revision began','Whether it should be accepted'],['Evidence state','Support available then','Future validity'],['Decision link','Recorded review','New publication authority']]},
  {slug:'index-discoverability-as-a-publication-control',title:'Index discoverability as a publication control for daily article batches',excerpt:'A route-level study of how landing pages and sitemaps complement canonical identity without replacing it.',question:'What does index and sitemap coverage prove about a new article, and what remains unproven?',unit:'one canonical route compared with its content-type index link, sitemap location, response, and rendered identity',signal:'agreement among manifest, route, canonical, landing page, and sitemap',risk:'treating discovery coverage as proof that the correct unique body rendered',method:'The analysis compares missing-link, wrong-index, alias, duplicate-body, and complete-route cases.',finding:'Discovery links prove findability only when route identity, response, metadata, and unique content also agree.',boundary:'A checker reports discrepancies but does not create aliases, move content types, or waive a failed route.',rows:[['Landing link','Human discovery path','Unique body'],['Sitemap loc','Machine discovery path','HTTP success'],['HTTP 200','Route response','Correct identity'],['Self-canonical','Preferred identity','Index coverage']]},
  {slug:'late-edit-risk-in-daily-publication-batches',title:'Late-edit risk in daily publication batches: a gate-impact framework',excerpt:'A qualitative comparison of post-review changes and the checks each change invalidates.',question:'How can a team decide which release checks must repeat after a late edit?',unit:'one change request linked to affected claims, metadata, routes, assets, build output, and reviewer',signal:'the set of prior gates invalidated by the changed field',risk:'assuming a small textual diff has small evidentiary or technical impact',method:'The study maps typo, factual, title, slug, date, and asset changes to their downstream controls.',finding:'The safe recheck scope follows the dependency changed, not the apparent size of the edit.',boundary:'An assistant can map impact and rerun approved checks; the editor approves meaning and release.',rows:[['Typo only','Copy review','No factual change'],['Factual wording','Evidence and copy','Approval remains valid'],['Title or slug','Canonical, index, sitemap','Route migration'],['Date or asset','Schema, visible page, build','Policy exception']]},
  {slug:'handoff-reproducibility-for-daily-content-operations',title:'Handoff reproducibility for daily content operations',excerpt:'A desk study of whether another work window can continue from recorded state instead of reconstructing context.',question:'Which handoff fields make daily blog and research work reproducible across time zones?',unit:'one dated handoff naming the artifact, inspected evidence, completed gate, exception, next action, owner, and zone',signal:'whether the receiver can locate the evidence and perform the next action without guessing',risk:'using “done,” “review,” or “blocked” without a verifiable state transition',method:'The analysis tests minimal and expanded handoffs across research, editing, build, and route-review scenarios.',finding:'Continuity depends on explicit artifact state and ownership rather than message length or assumed availability.',boundary:'The outgoing assistant records state; the receiving owner confirms acceptance and retains publication authority.',rows:[['Artifact','Object to inspect','Whether it is correct'],['Completed gate','Last verified state','Next approval'],['Exception','Known uncertainty','Resolution'],['Owner and zone','Who acts and when','Continuous coverage']]}
];

export const sep2ResearchPosts: ResearchPost[] = studies.map((s) => ({slug:s.slug,title:s.title,excerpt:s.excerpt,published,image,imageAlt:`Evidence map illustration for ${s.title}`,keyStats:[{value:'1',label:'Reviewable unit',source:'Study method'},{value:'4',label:'States compared',source:'Analysis model'},{value:'1',label:'Named decision owner',source:'Control boundary'}],takeaways:[s.finding,'Recorded activity must be interpreted beside a defined state.','Preparation is delegable while evidence and publication authority remain named.'],sections:[
  {heading:'Research question and scope',body:`${s.question} This desk study examines ${s.unit} in a daily blog and research operation such as HireAssistantNearMe. It does not measure a live workforce, establish a universal performance target, or claim that the control improves traffic, sales, or trust. The analysis separates observed record state from recommendations and preserves final editorial judgment for a named owner.`},
  {heading:'Method and comparison',body:`${s.method} Each example is classified as ready for review, returned for a specific correction, waiting for identified information, or stopped at an authority boundary. The comparison records ${s.signal}. This qualitative control exercise asks whether another reviewer can reproduce the state from stored evidence rather than relying on memory or a general status label.`},
  {heading:'Evidence interpretation',body:`The W3C PROV overview describes relationships among entities, activities, and agents. NIST SP 800-53 provides broad control language for accountability, access, and records. Applied narrowly, these sources support keeping artifacts, actions, evidence, and responsible people connected. Neither source prescribes HireAssistantNearMe’s editorial workflow or proves that a recorded decision is correct.`},
  {heading:'Finding and operating model',body:`${s.finding} A practical record exposes the starting input, inspected evidence, latest meaningful action, state, exception reason, and next named owner. The principal signal is ${s.signal}. Reviewers should sample ordinary passes and failures because incorrect approvals can disappear from a tidy exception queue. Changes to claims, wording, canonical identity, legacy content, or release state follow the authority assigned in the publishing process.`},
  {heading:'Limitations, risks, and role boundary',body:`The main failure risk is ${s.risk}. Timestamps can be inaccurate, integrations can omit work, and complete fields can still describe a poor decision. This model does not settle privacy, employment, intellectual-property, security, accessibility, or local legal obligations. ${s.boundary} Use named accounts, retain prior states, and stop when evidence conflicts or a public commitment needs approval.`},
  {heading:'Conclusion',body:`The defensible conclusion is narrow: ${s.finding} Test the record with one ordinary item, one incomplete item, and one authority-boundary item. A reviewer should be able to explain every pass and correction from stored evidence. If context must be reconstructed, the handoff is incomplete; if the record is clear but the decision remains consequential, routing it to the accountable owner is the intended result.`}
],tables:[{caption:'Control interpretation table',columns:['Record','What it can show','What it cannot decide'],rows:s.rows}],sources:commonSources,related}));
