import type { ResearchPost } from './fleet-data';

const published = '2026-09-24';
const checked = 'September 24, 2026';

type Study = {
  slug:string; title:string; excerpt:string; image:string; imageAlt:string; lane:string; serviceHref:string;
  question:string; decision:string; sample:string; finding:string; boundary:string; risks:string;
  sources:readonly (readonly [string,string])[];
};

const studies:readonly Study[] = [
  {
    slug:'executive-assistant-board-packet-version-control',
    title:'Board packets: how should an executive assistant control versions before distribution?',
    excerpt:'A version-controlled handoff for agenda items, source documents, late edits, approvals, and final distribution.',
    image:'/images/assistant-elena.jpg', imageAlt:'Executive assistant reviewing a version-controlled board packet', lane:'Executive assistance', serviceHref:'/services/executive-assistance',
    question:'How can an executive delegate board-packet preparation while keeping approval, confidential distribution, late changes, and governance decisions with accountable owners?',
    decision:'Give the assistant an approved source list, version convention, cutoff, recipient list, and named approver. The assistant may assemble and compare materials; the chair, executive, or governance owner decides content, late exceptions, confidentiality, and release.',
    sample:'twenty-four fictional packet items covering draft reports, duplicate files, a late correction, a confidential appendix, an unsigned resolution, an outdated chart, a recipient change, and a document received after cutoff',
    finding:'A polished PDF did not prove that its contents were approved or current. A reviewable release required source lineage, version, cutoff status, approver, recipient scope, and a retained final copy.',
    boundary:'NIST guidance supports access control and information integrity, while SEC materials describe governance disclosure context; neither source defines a private company’s board process, approval authority, or confidentiality rules.',
    risks:'distributing an unapproved draft, omitting a late correction, exposing a confidential appendix, merging inconsistent versions, using an obsolete recipient list, or presenting assembly work as governance approval',
    sources:[['NIST SP 800-53 Rev. 5, AC-3 Access Enforcement','https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'],['NIST SP 800-92, Guide to Computer Security Log Management','https://csrc.nist.gov/pubs/sp/800/92/final'],['SEC, Corporate Governance','https://www.sec.gov/resources-small-businesses/capital-raising-building-blocks/corporate-governance']]
  },
  {
    slug:'calendar-assistant-travel-change-approval-handoff',
    title:'Travel changes: what can a calendar assistant prepare before approval?',
    excerpt:'A time-zone-aware handoff for itinerary changes, fare conditions, traveler preferences, conflicts, and purchase approval.',
    image:'/images/aug20-blog-order-exceptions.png', imageAlt:'Calendar assistant preparing a travel-change approval handoff', lane:'Calendar and inbox support', serviceHref:'/services/calendar-and-inbox-support',
    question:'Which parts of a business-travel change can a remote assistant prepare without purchasing, accepting a fare restriction, moving a protected meeting, or promising an itinerary on the traveler’s behalf?',
    decision:'The assistant may collect current itinerary records, change options, stated fare conditions, calendar conflicts, time zones, and approval deadlines. The traveler or named owner decides purchases, cancellations, exceptions, and commitments.',
    sample:'twenty fictional travel changes involving a cancellation, overnight connection, airport change, visa uncertainty, nonrefundable fare, calendar conflict, traveler preference, and an option that expired before review',
    finding:'The shortest itinerary was not always decision-ready. A usable handoff preserved observation time, named time zones, fare conditions, unresolved entry requirements, meeting impact, option expiry, and the person authorized to buy.',
    boundary:'IANA supplies authoritative time-zone data and the U.S. State Department publishes travel information; neither source verifies a private itinerary, guarantees entry, interprets a fare contract, or authorizes a purchase.',
    risks:'buying without approval, dropping a time zone, treating an expiring option as confirmed, overlooking a calendar conflict, copying passport data into general notes, or presenting public travel guidance as individualized clearance',
    sources:[['IANA Time Zone Database','https://www.iana.org/time-zones'],['U.S. Department of State, Travel Advisories','https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories.html'],['U.S. Department of State, International Travel','https://travel.state.gov/content/travel/en/international-travel.html']]
  },
  {
    slug:'content-research-assistant-ai-source-verification',
    title:'AI-assisted research: how should a content assistant verify sources before drafting?',
    excerpt:'A claim-level source record for generated leads, primary evidence, checked dates, contradictions, and editorial decisions.',
    image:'/images/aug20-blog-invoice-followup.png', imageAlt:'Content research assistant verifying sources behind an AI-assisted draft', lane:'Content research', serviceHref:'/services/content-research',
    question:'How can a content research assistant use generative tools for discovery without treating generated citations, summaries, quotations, or confidence as verified evidence?',
    decision:'Treat generated output as an unverified lead. Open the primary source, record publisher, title, URL, date and scope, map each factual claim to supporting text, preserve counterevidence, and leave thesis and publication approval with the editor.',
    sample:'eighteen fictional research claims including a fabricated citation, a real title with the wrong URL, an outdated statistic, a secondary summary, conflicting definitions, a paywalled source, an ambiguous date, and a claim with no primary evidence',
    finding:'A plausible citation was not evidence. The recoverable record showed which source was opened, what it actually established, where the draft went beyond it, what uncertainty remained, and which editor accepted or removed the claim.',
    boundary:'NIST AI RMF describes trustworthy-risk characteristics and the GPO Style Manual supports precise editorial practice; neither source certifies a generated answer, verifies a citation, or chooses a publisher’s editorial position.',
    risks:'citing a source that was never opened, quoting generated text as source text, hiding contradictory evidence, using a current URL for an outdated claim, conflating analysis with fact, or publishing before an editor reviews the evidence map',
    sources:[['NIST, Artificial Intelligence Risk Management Framework','https://www.nist.gov/itl/ai-risk-management-framework'],['NIST AI 600-1, Generative AI Profile','https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence'],['U.S. Government Publishing Office, Style Manual','https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2016']]
  },
  {
    slug:'project-coordinator-decision-register-evidence',
    title:'Meeting decisions: what should a project coordinator record before work proceeds?',
    excerpt:'An evidence-led register for proposals, decisions, dissent, owners, due dates, changes, and unresolved questions.',
    image:'/images/aug21-research-calendar-context.png', imageAlt:'Project coordinator reviewing a meeting decision register', lane:'Project coordination', serviceHref:'/services/project-coordination',
    question:'What evidence lets a project coordinator distinguish a proposal, discussion point, decision, assigned action, and later change without inventing consensus or authority?',
    decision:'Record the meeting source, exact decision language, decision owner, affected work, action owner, due date with time zone, dissent or uncertainty, and supersession link. The accountable owner confirms ambiguous or high-impact decisions.',
    sample:'twenty-two fictional meeting records across four time zones, including a proposal mistaken for approval, two conflicting owners, a revised deadline, recorded dissent, an absent stakeholder, a superseded decision, and an action with no due date',
    finding:'A concise action list lost important distinctions when discussion became decision by implication. A reliable register preserved who decided what, the evidence source, unresolved objections, ownership, timing, and links to later changes.',
    boundary:'IANA supplies time-zone data and NIST logging guidance explains why timestamps, identity, and event context matter. Neither source determines organizational authority, validates meeting notes, or creates consensus.',
    risks:'converting discussion into approval, assigning an absent person, deleting dissent, losing the original record, carrying forward a superseded decision, dropping a time zone, or changing scope without the decision owner',
    sources:[['IANA Time Zone Database','https://www.iana.org/time-zones'],['NIST SP 800-92, Guide to Computer Security Log Management','https://csrc.nist.gov/pubs/sp/800/92/final'],['NIST, Cybersecurity Framework 2.0','https://www.nist.gov/cyberframework']]
  },
  {
    slug:'sales-assistant-lead-source-consent-provenance',
    title:'Lead-source provenance: what should a sales assistant verify before follow-up?',
    excerpt:'A contact-level record for acquisition source, consent evidence, channel, purpose, suppression state, and owner review.',
    image:'/images/assistant-daniel.jpg', imageAlt:'Sales assistant reviewing lead-source and consent provenance', lane:'Sales administrative support', serviceHref:'/services/sales-administrative-support',
    question:'How can a sales assistant prepare follow-up when imported leads have incomplete source, consent, channel, or suppression evidence without treating possession of an address as permission to contact it?',
    decision:'Preserve acquisition source, capture time, disclosed purpose, channel-specific permission evidence, applicable campaign, identity match, suppression state, and owner. Hold records with missing or conflicting provenance for the designated owner.',
    sample:'twenty-six fictional leads including a web form, event scan, partner referral, purchased list, shared mailbox, duplicate CRM record, prior opt-out, unclear checkbox, role address, stale export, and a contact whose employer changed',
    finding:'A populated email field did not establish source or permission. The durable handoff connected each contact to acquisition evidence, stated purpose, allowed channel, suppression history, identity conflicts, and an accountable release decision.',
    boundary:'FTC CAN-SPAM guidance addresses commercial email and business responsibility, while FTC privacy guidance addresses truthful data practices. Neither source establishes consent for a particular contact or resolves every channel and jurisdiction.',
    risks:'treating a purchased record as permission, losing acquisition history during import, contacting a suppressed identifier, merging different people, broadening purpose silently, inventing consent from silence, or allowing the assistant to resolve legal ambiguity',
    sources:[['FTC, CAN-SPAM Act: A Compliance Guide for Business','https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business'],['FTC, Privacy and Security Guidance','https://www.ftc.gov/business-guidance/privacy-security'],['NIST Privacy Framework','https://www.nist.gov/privacy-framework']]
  }
];

function makePost(s:Study):ResearchPost {
  const sourceNames=s.sources.map(([name])=>name).join('; ');
  return {slug:s.slug,title:s.title,excerpt:s.excerpt,published,image:s.image,imageAlt:s.imageAlt,
    keyStats:[{value:'1',label:'Named decision owner required',source:'Study method'},{value:String(s.sources.length),label:'Authoritative sources checked',source:'Source ledger'},{value:'0',label:'Customer or worker outcomes measured',source:'Study boundary'}],
    takeaways:[s.decision,'Test ordinary items, conflicts, missing information, and stop cases before expanding the lane.','Keep original evidence, analysis, owner decisions, and uncertainty visibly separate.'],
    sections:[
      {heading:'Research question and buyer decision',body:`${s.question} This report addresses that narrow decision for a local business considering ${s.lane.toLowerCase()} from a Philippines-based remote assistant. The operational conclusion is: ${s.decision} The conclusion is source-informed analysis, not a claim that one workflow fits every business, jurisdiction, tool, worker, customer, or transaction. It does not evaluate a Hire Assistant Near Me candidate or promise speed, savings, accuracy, compliance, revenue, or another business result. The useful buying question is not whether an assistant can touch the record. It is whether the role has a defined source, permitted action, stop condition, evidence trail, and available owner for the decisions that remain.`},
      {heading:'Methodology and constructed sample',body:`We performed a qualitative desk review and a bounded walkthrough on ${checked}. The unit of analysis was one task decision within ${s.sample}. Before reviewing each fictional case, we recorded the approved source, permitted verb, minimum evidence, stop rule, owner, and completion state. We then asked whether a second reviewer could reconstruct what was known, what action was allowed, what remained uncertain, and who controlled the next step. The cases deliberately included ordinary work, missing inputs, conflicting records, urgency, sensitive information, and requests outside the proposed role. No customer, applicant, assistant, employee, private account, production system, payment, revenue result, or service outcome was observed. We calculated no rate, benchmark, effect size, statistical significance, or causal relationship. The sample tests whether a proposed instruction is reviewable; it does not estimate how often any condition occurs.`},
      {heading:'What the sources establish',body:`The source set was checked on ${checked}: ${sourceNames}. These primary or authoritative publishers supply definitions, duties, risk concepts, or control guidance within their own stated scope. ${s.boundary} The publishers did not study Hire Assistant Near Me, compare staffing providers, endorse Philippines-based assistance, validate these fictional cases, or guarantee this proposed control. Connecting their material to a remote administrative lane is our analysis. A future editor should reopen each link, confirm that the material remains current and responsive, record a new checked date, and revise any affected conclusion. A working URL is not enough: the source must support the proposition for which it is used, and adjacent guidance must not be stretched into proof of a company-specific result.`},
      {heading:'Finding from the walkthrough',body:`${s.finding} Across the constructed sample, access to a record never created authority to make every decision involving that record. Familiar work changed character when evidence was missing, contradictory, sensitive, late, or tied to an external commitment. A precise stop with a recoverable handoff was more useful than a polished output that concealed an assumption. The owner response path mattered as much as the assistant’s instruction: an escalation rule without an available decision owner moved uncertainty into an aging queue. These observations apply only to the fictional cases. They are hypotheses to test in a protected pilot, not evidence about prevalence, employee performance, customer satisfaction, legal compliance, cost, or commercial value.`},
      {heading:'Define the role with sources and verbs',body:`Write the lane as observable verbs such as view, collect, copy, label, compare, draft, route, change, send, delete, approve, publish, or pay. Attach each permitted verb to an approved source and completion record, then name the owner-held action beside it. A broad title such as ${s.lane.toLowerCase()} cannot show whether a person may alter a field, communicate externally, resolve an exception, or administer access. Examples should include a clean case, a missing-source case, a conflict, sensitive information, urgency, and a request beyond authority. State what to do when an example and the live record differ. The assistant should return uncertainty in a defined format instead of being rewarded for a tidy guess. Role design becomes fairer when quality can be evaluated against supplied evidence rather than unstated owner expectations.`},
      {heading:'Build the minimum evidence handoff',body:`A useful handoff identifies the work item without copying unrelated sensitive information. It records the source location, observation time with a named time zone, last permitted action, exact missing or conflicting fact, decision requested, current owner, and due or recheck time. When a change needs review, preserve the prior and proposed values. Link to the approved system of record instead of building a shadow database in chat or comments. Apply the business’s retention and access rules. Keep credentials, authentication secrets, full payment details, and unrelated personal information out of general notes. Another reviewer should understand the stop without asking the assistant to reconstruct events from memory. The record supports judgment; it does not transfer responsibility to the person who assembled it.`},
      {heading:'Pilot and review method',body:`Start with a small representative batch and deliberately include routine items, incomplete inputs, conflicting records, one urgent request, sensitive information, and an action beyond authority. Freeze the instruction version and review rubric for one comparison window. Score source fidelity, permitted action, correct stop, evidence preservation, and handoff completeness separately. Count false stops as well as unsafe continuation: excessive escalation can make a lane unusable, while proceeding through uncertainty can create larger business risk. Review disagreements at the rule level. Ask whether the approved source, example, wording, permission, system state, or owner response path needs repair before granting broader access. Do not change the rubric halfway through and then present unlike samples as a trend. The purpose is to decide whether this specific lane is ready, not to manufacture a favorable performance story.`},
      {heading:'Risks and safeguards',body:`The principal risks are ${s.risks}. Address them with named accounts, least-privilege permissions, multifactor authentication where available, approved systems of record, examples containing stop cases, and a decision owner available during agreed working hours. Separate correction from blame. A correction log should show the evidence gap and instruction revision rather than encourage quiet rework that erases history. Do not measure success only by volume or response speed. Include unsafe continuations, unnecessary escalations, unresolved queue age, evidence completeness, owner review time, and reversals so one favorable number does not conceal transferred work or risk. Where law, contract, regulated advice, money movement, account security, or sensitive personnel judgment is involved, route the decision to a qualified accountable person.`},
      {heading:'Buyer checklist before hiring',body:`List the recurring work and the systems it touches. Mark actions that create commitments, alter money or access, expose sensitive information, interpret policy, or communicate publicly. Choose which remain with the owner or qualified team member. For the proposed assistant lane, write the input, permitted actions, finished output, stop reasons, evidence fields, expected response window, reviewer, and escalation route. Confirm that the tools can implement the stated permission boundary rather than relying on a policy that broad access makes impossible. Prepare representative practice cases without private data and agree how corrections will be recorded. Ask how a Philippines-based schedule overlaps with the owner who must answer exceptions. If no owner can respond, narrow the lane or change the handoff timing before hiring.`},
      {heading:'Limitations and evidence-led conclusion',body:`This analysis uses public guidance and constructed cases, not field observation. It cannot establish the right policy for a particular jurisdiction, industry, contract, system, transaction, applicant, customer, or worker. Source pages can change, and a general framework cannot verify private facts or replace legal, security, accounting, HR, or other specialist advice. The conclusion is therefore deliberately narrow: ${s.decision} A buyer should test that design with protected records and accountable review before expanding access. If errors cluster around one source, state, or exception, repair the workflow rather than assuming more volume will solve it. If the task cannot be separated from owner judgment or implemented with appropriate permissions, keep it with the accountable team. A smaller, observable lane is a stronger starting brief than a broad promise of assistance.`}
    ],
    tables:[{caption:`${s.lane} decision record`,columns:['State','Assistant output','Owner boundary'],rows:[['Prepared','Source-linked draft or indexed evidence','No implied approval'],['Held','Conflict, missing fact, or risk signal','Named owner decides'],['Completed','Recorded permitted action and evidence','Owner retains policy and exception authority']]}],
    sources:s.sources.map(([name,url])=>({name:`${name} (checked ${checked})`,url})),
    related:[{label:`Review ${s.lane.toLowerCase()} services`,href:s.serviceHref},{label:'Browse the Research library',href:'/research'}]
  };
}

export const sep24Hira96ResearchPosts:readonly ResearchPost[] = studies.map(makePost);
