import type { ResearchPost } from './fleet-data';
const published = '2026-09-10';

const studies = [
 ['source-access-date-claim-ledger-test','Does recording a source access date improve claim-ledger review?','A constructed comparison of claim ledgers with URLs alone and with URL, access date, quoted field, and reviewer status.','/images/aug23-research-claim-provenance.png','whether an access date and field-level trail help a reviewer reconstruct what supported a daily article claim','ten fictional claim records containing stable pages, revised pages, missing fields, and conflicting notes','Records with access dates and named fields made the review trail easier to reconstruct, but they did not prove that a source was accurate when consulted.','The exercise used fictional records, one reviewer, and no archived-page service. It did not measure editorial accuracy or publication speed.',[['W3C PROV-O: The PROV Ontology','https://www.w3.org/TR/prov-o/'],['NIST Information Quality Standards','https://www.nist.gov/nist-information-quality-standards']],10],
 ['structured-publication-date-parity-test','Testing visible and structured publication-date parity','A bounded route audit comparing visible dates, HTML time values, and Article structured data.','/images/aug21-research-evidence-map.png','whether checking three date surfaces exposes release inconsistencies that a visual review can miss','twelve constructed article pages with matching, missing, and conflicting date states','The parity check found conflicts hidden from a visual-only review. Matching fields still did not establish when a page first became publicly available.','No search crawler, cache, feed reader, or historical index was observed. The pages were constructed examples rather than a live release.',[['Schema.org Article','https://schema.org/Article'],['WHATWG HTML Living Standard: the time element','https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-time-element']],12],
 ['family-index-membership-release-control','Can family-index membership work as a release control?','A constructed comparison of published routes against separate Blog and Research index manifests.','/images/sep3-research-topic-distance.png','whether an explicit family manifest catches routes placed in the wrong content collection','seventeen fictional routes covering correct membership, omissions, duplicates, and cross-family placement','The manifest comparison exposed omitted and cross-family routes, but membership alone said nothing about the quality or identity of the content.','The exercise did not test crawler discovery, ranking, navigation usability, or a content-management system with concurrent editors.',[['W3C, Data on the Web Best Practices','https://www.w3.org/TR/dwbp/'],['Sitemaps protocol','https://www.sitemaps.org/protocol.html']],17],
 ['image-asset-response-and-metadata-audit','What does a two-layer article image audit catch?','A constructed audit of direct image responses and the page metadata that refers to each image.','/images/aug20-research-record-provenance.png','whether checking both asset delivery and page references reveals failures missed by either check alone','fourteen fictional pages containing broken assets, valid assets with wrong metadata, missing alt text, and complete records','The two-layer audit separated delivery failures from metadata failures. It did not determine whether an image was licensed, relevant, or visually effective.','No social crawler, assistive-technology user study, image-license review, or performance test was conducted.',[['WHATWG HTML Living Standard: Images','https://html.spec.whatwg.org/multipage/images.html'],['Open Graph protocol','https://ogp.me/']],14],
 ['normalized-title-body-collision-screen','Screening a daily batch for title and body collisions','A constructed comparison using exact title checks, normalized body fingerprints, and editorial review.','/images/sep3-research-counterevidence.png','which collision checks can flag likely reuse while leaving the originality decision to an editor','seventeen fictional articles with distinct drafts, exact duplicates, punctuation-only title changes, and shared template language','Exact and normalized checks surfaced likely collisions for review. Shared phrases also produced false signals, so a human editor still had to judge article identity.','The sample was small and fictional, normalization rules were selected for this exercise, and the screen cannot establish authorship, plagiarism, or legal originality.',[['NIST Secure Hash Standard','https://csrc.nist.gov/pubs/fips/180-4/upd1/final'],['U.S. Copyright Office, Copyright Basics','https://www.copyright.gov/circs/circ01.pdf']],17],
] as const;

export const sep10ResearchPosts: ResearchPost[] = studies.map((s) => {
 const [slug,title,excerpt,image,question,cases,finding,limitation,sources,count] = s;
 return {slug,title,excerpt,published,image,imageAlt:`Research illustration for ${title.toLowerCase()}`,keyStats:[{value:String(count),label:'Constructed records examined',source:'Study design'},{value:'2',label:'Primary or standards sources reviewed',source:'Source review'},{value:'0',label:'Live workers or search outcomes measured',source:'Scope'}],takeaways:[finding,'The result is a workflow observation, not a causal or performance claim.','Repeat the check on representative live work before changing release policy.'],sections:[{heading:'Research question and scope',body:`Hire Assistant Near Me asked ${question}. The study used ${cases} for a proper daily blog and research routine. The unit of analysis was one route, record, or draft. We did not evaluate an assistant, editor, customer, or search result.`},{heading:'Methodology',body:'We held the underlying case facts constant, prepared the comparison states named in the study design, and recorded what a reviewer could verify, what remained ambiguous, and which decision required an accountable owner. The analysis was qualitative and descriptive. We calculated no statistical effect, causal relationship, productivity change, or population estimate.'},{heading:'Observed result',body:finding},{heading:'How the sources were used',body:'The references supply protocol, provenance, publishing, or legal context for the fields under review. They do not study Hire Assistant Near Me, validate the fictional sample, or show that the observation transfers to another publishing system.'},{heading:'Inference boundaries',body:'The finding supports a release check worth testing. It does not establish worker quality, legal compliance, accessibility, originality, indexing, ranking, security, or the correct policy for a specific organization.'},{heading:'Limitations',body:`${limitation} Standards and source pages can change, and another reviewer may classify the same evidence differently.`},{heading:'Practical implication',body:'Pilot the control on a small representative batch. Keep the underlying evidence, record disagreements, and require a named publication owner to resolve exceptions before release rules or permissions change.'},{heading:'Conclusion',body:`Within this narrow constructed exercise, ${finding.toLowerCase()} A live test with documented review criteria is still required.`}],tables:[{caption:'Study boundary',columns:['Element','Included','Not established'],rows:[['Input',cases,'Representativeness of all publishing work'],['Observation',finding,'Causal or statistical proof'],['Next decision','A release control to test','Final publication or access policy']]}],sources:sources.map(([name,url])=>({name,url})),related:[{label:'Research library',href:'/research'},{label:'Content support services',href:'/services/content-support'}]};
});
