// Local-only explicit Research replacements for the expanded HIRA-102 audit.
// Each study has its own method, evidence path, case analysis, and conclusion.

export const oct2IndependentResearchContent = {
  'inbox-assistant-business-email-compromise-payment-change': {
    sections: [
      {heading:'The narrow question this study answers',body:'How should an inbox assistant handle a message that changes payment instructions without deciding that the sender or bank account is genuine? The answer is narrower than fraud detection. The assistant can preserve the message, identify the requested financial action, compare observable details with approved records, and open the business verification route. Only the financial owner may change vendor master data, accept new bank details, or release money. That division keeps message handling separate from payment authority.'},
      {heading:'Why a familiar thread can still mislead',body:'One constructed case placed the change request inside a real-looking history of ordinary invoice messages. The display name, writing style, and prior subject line all looked familiar. The new elements were urgency, a replacement account in a PDF, and a callback number supplied in the same message. Thread continuity did not establish control of the mailbox or authority to change payment details. The assistant recorded those differences and used contact information already held in the approved vendor record.'},
      {heading:'Twenty-four messages in the comparison set',body:'The exercise included ordinary invoices, a legitimate contact update, display-name impersonation, a one-character lookalike domain, changed reply-to fields, executive urgency, gift-card requests, an unexpected attachment, a compromised thread, and an ambiguous request from a known supplier. Each message was assessed against sender evidence, financial action requested, independent contact path, current vendor record, access required, stop condition, and decision owner. No live inbox, customer, employee, transaction, or loss was used.'},
      {heading:'What the cited authorities support',body:'The FBI describes business email compromise as a fraud pattern involving trusted relationships and payment requests. CISA guidance supports protective controls and preparation for common cyber risks. NIST identity guidance explains why identity evidence and assurance need deliberate processes. Together, those sources support skepticism, least privilege, and independent verification. They do not authenticate a particular email, certify bank information, prescribe the company’s exact approval chain, or prove that one callback is safe.'},
      {heading:'The observable fields worth preserving',body:'The exception record should retain sender address, display name, received time, thread identifier, reply-to difference where visible, requested action, affected vendor or customer, attachment names, stated deadline, and the approved record used for comparison. Links can be described without opening unsafe destinations. The record should not copy complete bank details into a general ticket. Preserving message provenance matters because a polished summary can otherwise remove the discrepancy that caused the stop.'},
      {heading:'Independent verification means a separate route',body:'Calling a phone number printed in the suspicious email only repeats evidence from the same source. The business should define an approved channel drawn from records established before the request, such as a verified vendor contact or account owner. The assistant records who was contacted, through which approved channel, at what time, and who accepted the case. Even a successful contact does not give the assistant permission to edit vendor data. The authorized owner completes the financial control.'},
      {heading:'Freeze the current state while the question is open',body:'A payment-change exception should not overwrite the known vendor record. Keep the current instructions unchanged until the owner records a decision. Avoid adding the proposed account as an inactive alternative if that exposes it to later selection. The ticket can link the source message and show pending verification. This design protects ordinary payment work from a premature update and leaves a clear comparison between prior value, proposed value, verifier, decision, and completion time.'},
      {heading:'Stop conditions for the inbox lane',body:'New bank details, requests for secrecy, unusual urgency, changed authentication factors, gift cards, lookalike domains, unfamiliar reply-to addresses, unexpected files, or instructions to bypass the normal approver all stop routine processing. The absence of those clues does not prove safety. Stop as well when the independent contact record is missing, the apparent executive is unavailable, or the requested action falls outside the sender’s usual role. The assistant should not reply simply to test whether the sender answers.'},
      {heading:'A paid work sample that rewards restraint',body:'Give candidates normal invoices beside obvious spoofs, thread compromise, legitimate contact changes, executive impersonation, and two uncertain cases. Ask them to create exception records and choose the approved route. Score preservation of evidence, recognition of the financial action, use of an independent channel, minimum exposure, and correct owner assignment. Measure unsafe continuation separately from unnecessary holds. Fast processing is not a positive result if the assistant makes the payment exception harder to see.'},
      {heading:'Permissions for an inbox support role',body:'The assistant needs the assigned inbox, approved vendor directory fields, safe evidence procedure, exception form, and escalation contacts. The role does not need payment release, bank-field editing, mailbox administration, authentication recovery, broad exports, or complete financial records. A named account and multifactor authentication help make actions reviewable. Permission removal should be tested before launch, not discovered after a staffing change.'},
      {heading:'Separate the people who request, verify, and release',body:'The strongest version of this workflow assigns three different acts: receiving the request, verifying the vendor through an established route, and approving the resulting financial change. A small business may not have three employees available, but it can still avoid letting one inbox handler complete the whole chain. For example, the assistant can open the exception, the vendor owner can conduct the callback, and the payment approver can review the recorded result. If one person must cover two roles, the exception should show that overlap instead of implying independent review. The study treated unclear ownership as a workflow failure even when the proposed bank data later proved legitimate.'},
      {heading:'A decision log should answer reconstructive questions',body:'After the case closes, a reviewer should be able to tell what arrived, what differed from the approved record, who verified the request, which pre-existing contact route was used, what decision was made, and when the ordinary payment process resumed. That does not require storing every sensitive value. A redacted comparison and controlled link can preserve the reasoning while limiting exposure. Free-form notes alone performed poorly in the exercise because they often omitted the prior state or mixed observations with conclusions. Structured fields made it easier to identify a missing callback, an unassigned owner, or a bank change entered before approval.'},
      {heading:'Response language should avoid accidental assurance',body:'An acknowledgment can say that the requested change was received and is undergoing the company’s standard review. It should not say the new account is verified, that payment will arrive on a particular date, or that the sender passed security checks. When the sender presses for urgency, the assistant can repeat the review state and route the deadline to the payment owner. Using a neutral message protects the business from turning an intake response into a promise. It also gives genuine vendors a consistent explanation without revealing which specific discrepancies were observed.'},
      {heading:'What to measure in a protected pilot',body:'Review whether messages were preserved, requested actions were identified, known records were used correctly, independent routes were followed, and financial owners accepted decisions. Track links opened outside policy, sensitive data copied unnecessarily, vendor fields changed early, unsupported fraud labels, and cases left without ownership. Also count harmless messages held for review. The balance matters: a control that stops everything may be safe in one sense but unusable for the business.'},
      {heading:'Limits and conclusion',body:'This is a workflow analysis using fictional messages, not a forensic method or estimate of fraud frequency. Headers, authentication results, phone calls, documents, and historical behavior can each be incomplete or manipulated. The conclusion is operational: an assistant can preserve, compare, and route a payment-change message, while the business’s authorized financial owner verifies the change and controls payment. If independent contact data or owner response is unavailable, the request should remain stopped.'},
    ],
  },
  'customer-support-assistant-account-recovery-identity-boundary': {
    sections: [
      {heading:'Account recovery is an access decision',body:'A support assistant can collect an approved recovery request without deciding that the claimant is the account holder. The role explains the published process, keeps the conversation in an approved channel, requests only the evidence listed by policy, records risk signals, and routes the case. A security or account owner decides whether identity evidence is sufficient, changes recovery factors, resets authentication, revokes sessions, or restores access.'},
      {heading:'The cases used in this inquiry',body:'Twenty fictional cases covered a lost device, changed phone number, inaccessible email, departed employee, shared mailbox, family-member request, urgent travel, mismatched billing name, suspected takeover, repeated failed attempts, and a claimant asking to move the conversation. Each case separated claimant statements, system observations visible to support, approved evidence, prohibited data, channel history, risk flags, owner decision, and customer communication. No real account or identity document was examined.'},
      {heading:'Why knowledge of the account proves little by itself',body:'One claimant knew an invoice number that also appeared in an old forwarded email. Another knew colleague names but requested recovery for a former employee’s mailbox. A third controlled the registered phone while the system showed a recent recovery-factor change. These facts may be relevant, but none independently settles identity or authority. The intake record preserves the contradiction. It does not convert a convincing story, job title, family relationship, or familiar detail into access.'},
      {heading:'The dangerous convenience of a new channel',body:'A locked-out person may ask support to send a reset to a new email address or phone number supplied during the same conversation. Urgency can make that request sound reasonable. The assistant should not move recovery to a claimant-selected channel unless the documented process and decision owner authorize it. Keep the original channel, registered-channel status, requested change, and reason visible. The security owner decides whether another route, waiting period, or review is required.'},
      {heading:'What NIST and FTC guidance contributes',body:'NIST digital identity guidance treats identity proofing, authentication, and recovery as risk-managed functions rather than a single knowledge test. FTC business guidance emphasizes collecting only needed personal information and protecting it. Those sources support controlled evidence, minimum data, and explicit ownership. They do not identify a claimant, set the right assurance level for every service, or authorize an assistant to override private account controls.'},
      {heading:'A minimum-data recovery record',body:'Use a non-sensitive case identifier, incoming channel, claimed account, recovery reason, approved evidence requested, evidence received status, timestamps, prior attempts visible to the role, risk flags, policy route, and current owner. Do not place passwords, one-time codes, full government identifiers, complete payment-card data, recovery secrets, or internal detection rules in general notes. Link protected evidence through the approved system rather than duplicating it for convenience.'},
      {heading:'Questions the assistant must never use as shortcuts',body:'The assistant should not ask for a password or authentication code, reveal which answers were correct, disclose hidden account details as hints, or request an arbitrary identity document outside policy. It should not treat emotional intensity as proof or lack of urgency as safety. A claimant may be genuine and still unable to satisfy the process. The assistant records the gap and owner rather than improvising a test that attackers can learn or sensitive data can expose.'},
      {heading:'Signals that leave ordinary support',body:'Suspected takeover, changed recovery factors, conflicting names, requests involving another person, repeated failures, attempts to bypass a delay, inaccessible registered channels, sensitive accounts, threats, and evidence outside the documented list require escalation. Stop as well if the support tool exposes more account data than the intake task needs. The assistant should preserve the safe current state and avoid telling the claimant which particular signal triggered review.'},
      {heading:'Communication after an owner decision',body:'The decision owner records the result and approved customer wording. The assistant may deliver that outcome through the authorized channel, but should not explain internal risk scoring or add a personal judgment. A denial or delay may need an appeal or specialist route. A successful recovery may require notifications to existing channels and session review. Those actions belong to the account process, not an improvised support message.'},
      {heading:'Recovery evidence needs a defined lifetime',body:'Identity evidence collected for a recovery decision should not remain in ordinary support history indefinitely. The business should define where protected material is stored, who can open it, when it is deleted, and what minimal decision record remains. The assistant can apply the approved retention label but should not download copies or move them into personal folders. In the fictional cases, duplicate evidence created ambiguity because one copy was later corrected while another stayed attached to the ticket. A controlled reference to the authoritative record reduced that problem and limited unnecessary access.'},
      {heading:'Appeal is different from repeating the same intake',body:'A claimant who cannot complete the standard route may need an appeal, accessibility accommodation, contractual administrator, or specialist investigation. Reopening the same checklist does not create stronger evidence and can disclose the questions through repetition. The assistant should identify the documented alternative, preserve the prior case identifier, and explain what will happen next without promising restoration. The appeal owner needs the original observations, decisions, and communications, not merely a fresh summary that hides failed attempts. Where no alternative exists, the limitation should be stated plainly and escalated as a policy problem.'},
      {heading:'Post-recovery review closes the security loop',body:'Restoring access is not the final administrative step. The accountable owner may need to review active sessions, recent factor changes, contact details, forwarding rules, API tokens, and notifications to registered channels. Which checks apply depends on the service and the suspected event. The assistant can track completion only when assigned a checklist that does not expose restricted security data. A case should not be labeled complete just because a reset link was sent. In the study, separating restoration from follow-up made abandoned sessions and unchanged recovery factors visible.'},
      {heading:'A recovery work sample needs adversarial cases',body:'Combine routine lockouts with incomplete legitimate claims, social engineering, compromised channels, shared accounts, former employees, and malicious repetition. Ask candidates to collect only allowed evidence and prepare owner handoffs. Score data minimization, policy fidelity, channel continuity, risk recognition, and clarity. Track unsafe restoration separately from unnecessary escalation. A candidate should not be rewarded for finishing every case because several examples deliberately lack enough authority.'},
      {heading:'Test the surrounding controls, not only the assistant',body:'Before delegation, the security owner should examine throttling, notification to existing channels, recovery delays, session revocation, evidence deletion, accessibility, appeals, and what happens after a failed attempt. The assistant can follow a process only if the tools and owners support it. If the account platform cannot restrict access or hide internal security data from intake staff, narrow the role instead of expecting discretion to compensate for poor permissions.'},
      {heading:'Study limits and bounded result',body:'The exercise does not test a real identity system, establish an assurance level, or determine legal obligations for a particular service. Risk depends on the account, data, jurisdiction, contracts, and technical design. The bounded result is that a support assistant may collect and route approved recovery evidence while an accountable security or account owner decides identity sufficiency and access restoration. When safe channel continuity or timely owner review is missing, retain the recovery decision internally. The organization should document that service limitation before an urgent case exposes it.'},
    ],
  },
} as const;
