import type { ResearchPost } from './fleet-data';

const published = '2026-09-01';
const image = '/images/aug21-research-evidence-map.png';
const related = [{label:'Research library',href:'/research'},{label:'Executive assistance',href:'/services/executive-assistance'}];
const commonSources = [
  {name:'W3C PROV Overview',url:'https://www.w3.org/TR/prov-overview/'},
  {name:'NIST SP 800-53 Rev. 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'}
];

type Study = {slug:string;title:string;excerpt:string;question:string;unit:string;signal:string;risk:string;method:string;finding:string;boundary:string;tableRows:string[][]};
const studies: Study[] = [
  {slug:'daily-editorial-throughput-without-vanity-metrics',title:'Daily editorial throughput without vanity metrics: what should a small publishing team count?',excerpt:'A desk study of finished units, review states, and correction signals for a daily blog and research workflow.',question:'Which daily measures distinguish finished editorial work from cards that merely moved?',unit:'one article matched to its approved manifest, evidence state, canonical route, and release decision',signal:'first-pass acceptance, correction reason, blocked time, and completed release gates',risk:'using word count or card movement as a substitute for accuracy and publication integrity',method:'The analysis compares a raw activity board with a gate-based manifest across ordinary, corrected, and held articles.',finding:'A count becomes useful only when the finished state is defined and unresolved review is visible.',boundary:'The assistant may maintain the record; the editor decides whether evidence and copy are acceptable.',tableRows:[['Words drafted','Writing volume','Evidence or release readiness'],['Cards moved','Workflow activity','Whether a gate truly passed'],['Accepted units','Defined finished work','Audience or revenue impact'],['Correction reasons','Where instructions failed','Who should approve the fix']]},
  {slug:'citation-traceability-in-daily-research-publishing',title:'Citation traceability in daily research publishing: a claim-to-source record model',excerpt:'A structured analysis of how a daily research team can preserve provenance from question through publication.',question:'What minimum record lets an editor trace a published claim back to its source and interpretation?',unit:'one factual claim linked to a source location, captured context, limitation, reviewer, and decision',signal:'the proportion of claims with openable sources, stated limits, and a recorded approval state',risk:'treating a URL list as proof that every sentence is supported',method:'The study models a claim ledger and tests it against direct support, partial support, conflicting sources, and inaccessible evidence.',finding:'Traceability depends on the relationship between claim and evidence, not the number of links attached.',boundary:'The researcher prepares provenance; the accountable editor approves the public interpretation.',tableRows:[['Source URL','Where evidence was found','Whether the claim follows'],['Claim note','Proposed factual statement','Final editorial wording'],['Limitation','Known scope constraint','Legal or specialist advice'],['Decision state','Review outcome','Future truth of the claim']]},
  {slug:'publication-integrity-controls-for-multi-article-daily-batches',title:'Publication integrity controls for multi-article daily batches',excerpt:'A control review for unique routes, self-canonicals, dates, indexes, and sitemap coverage in a daily content release.',question:'Which checks show that each item in a multi-article batch is a real, independently addressable publication?',unit:'one manifest row with a unique title, slug, canonical, body hash, date, route result, index link, and sitemap entry',signal:'exact agreement between source inventory, production build, route output, and discovery surfaces',risk:'aliases, fallback rendering, duplicate bodies, or a correct-looking index that points to missing content',method:'The analysis follows a batch from source records through static route generation and checks identity at every layer.',finding:'No single page check proves batch integrity; identity, response, metadata, and discoverability must agree.',boundary:'A release checker reports pass or failure but does not invent redirects or deploy a failed batch.',tableRows:[['Unique slug','Route identity','Body uniqueness'],['HTTP 200','Route resolves','Correct article rendered'],['Self-canonical','Declared preferred URL','Index inclusion'],['Body hash','Exact normalized uniqueness','Editorial quality']]},
  {slug:'exception-aging-in-daily-content-operations',title:'Exception aging in daily content operations: when does a blocked item need escalation?',excerpt:'A qualitative model for separating new, waiting, blocked, and overdue editorial exceptions.',question:'How should a daily publishing team read exception age without inventing one universal urgency threshold?',unit:'one exception with arrival time, last action, impact, dependency, promised review window, and next owner',signal:'time beyond the team’s stated review promise, read beside consequence and ownership',risk:'closing, relabeling, or repeatedly touching an item to make the queue appear current',method:'The study compares four queue states across missing evidence, failed builds, approval questions, and late-arriving requests.',finding:'Age is actionable only beside state, consequence, promise, and a named next decision.',boundary:'The assistant maintains status and evidence; the owner sets priorities and resolves consequential exceptions.',tableRows:[['Arrival age','Time since entry','Whether delay is justified'],['Action age','Time since meaningful work','What decision is correct'],['Promise variance','Potential missed window','Remedy or approval'],['Next review','When work returns','Priority across all work']]},
  {slug:'handoff-completeness-across-editorial-time-zones',title:'Handoff completeness across editorial time zones: an evidence-based continuity checklist',excerpt:'A desk study of the records needed to continue daily blog and research work without reconstructing the prior shift.',question:'Which handoff fields let the next editor continue work while preserving uncertainty and decision ownership?',unit:'one dated handoff that names the question, artifact, evidence, completed gate, open issue, next action, owner, and zone',signal:'whether the receiver can locate evidence and take the named next action without guessing',risk:'using “done” or “needs review” as a substitute for a reproducible work state',method:'The analysis tests a minimal handoff against research, fact-check, build, and publication exceptions across two work windows.',finding:'Useful time-zone continuity comes from explicit state and ownership, not from assuming around-the-clock availability.',boundary:'The outgoing assistant records the state; the receiving editor confirms acceptance and retains publication authority.',tableRows:[['Artifact link','Object to inspect','Whether work is correct'],['Completed gate','Last verified state','Approval of the next gate'],['Open question','Known uncertainty','Final interpretation'],['Owner and zone','Who acts and when','Continuous availability']]}
];

export const sep1ResearchPosts: ResearchPost[] = studies.map((s) => ({
  slug:s.slug,title:s.title,excerpt:s.excerpt,published,image,imageAlt:`Evidence ledger illustration for ${s.title}`,
  keyStats:[{value:'1',label:'Reviewable unit defined',source:'Study method'},{value:'4',label:'Operating states compared',source:'Analysis model'},{value:'1',label:'Named owner per exception',source:'Control boundary'}],
  takeaways:[s.finding,'Activity counts must be read beside a defined finished state.','Preparation can be delegated while evidence and publication decisions remain with the accountable owner.'],
  sections:[
    {heading:'Research question and scope',body:`${s.question} This desk study examines ${s.unit}. It addresses a daily blog and research operation such as HireAssistantNearMe, where several items can move through preparation, evidence review, editing, build checks, and release on the same date. It does not measure a live workforce, establish a universal productivity target, or claim that a control improves traffic, sales, or reader trust. The analysis separates recorded facts from operating recommendations and keeps final editorial judgment with a named owner.`},
    {heading:'Method and comparison',body:`${s.method} Each example is read in four states: ready for review, returned for a specific correction, waiting on identified information, or stopped at an authority boundary. The unit of analysis is ${s.unit}. The comparison records ${s.signal}. This is a qualitative control exercise, not an experiment. It is designed to reveal whether another reviewer can reproduce the state from the record rather than relying on memory or a general progress label.`},
    {heading:'Evidence interpretation',body:`The W3C PROV overview provides a model for describing entities, activities, and agents involved in provenance. NIST SP 800-53 supplies broad control language around accountability, access, and system records. These sources support traceable records and bounded permissions, but neither prescribes HireAssistantNearMe’s editorial workflow or proves the performance of a remote assistant. Applied narrowly, the evidence supports keeping the artifact, action, source, and responsible person connected. It does not turn the presence of a log into proof that an editorial decision was correct.`},
    {heading:'Finding and operating model',body:`${s.finding} A practical record should expose the starting input, inspected evidence, latest meaningful action, current state, exception reason, and next named owner. The most useful signal for this study is ${s.signal}. Reviewers should inspect ordinary passes as well as exceptions, because a tidy queue can contain incorrect approvals. Changes to source claims, public wording, canonical identity, legacy content, or release status require the authority assigned in the publishing process rather than an implied permission.`},
    {heading:'Limitations, risks, and role boundary',body:`The main failure risk is ${s.risk}. Timestamps may be wrong, integrations may omit work, and a complete field set may still contain a poor decision. The model does not address every privacy, employment, intellectual-property, security, or accessibility obligation. Local requirements and the sensitivity of each system need separate review. ${s.boundary} Start with representative items, use named accounts, preserve prior states, and stop when evidence conflicts or a final public commitment is required.`},
    {heading:'Conclusion',body:`For this question, the defensible conclusion is narrow: ${s.finding} A small team can test the record with one ordinary item, one incomplete item, and one item that reaches the authority boundary. The reviewer should be able to explain every pass and correction from the stored evidence. If the next person must reconstruct context, the handoff is incomplete. If the record is clear but the decision remains consequential, the workflow is functioning as intended when it routes that decision to the accountable owner.`}
  ],
  tables:[{caption:'Control interpretation table',columns:['Record','What it can show','What it cannot decide'],rows:s.tableRows}],sources:commonSources,related
}));
