import type { ResearchPost } from './fleet-data';

const published='2026-09-07';
const related=[{label:'Research library',href:'/research'},{label:'Content support services',href:'/services/content-support'}];
const studies=[
  {slug:'queue-age-or-item-count-for-daily-editorial-triage',title:'Queue age or item count: which signal should lead daily editorial triage?',excerpt:'A bounded comparison of two common workload signals for a daily blog and research routine.',image:'/images/aug20-research-dispatch-exception-queue.png',question:'Should a small editorial team sort a daily queue by the number of open items or by the age of the oldest unresolved item?',cases:'six constructed queue snapshots with different combinations of volume and age',finding:'Item count described workload, but it hid one old blocked article inside an otherwise small queue. Oldest-item age exposed delay, yet it said little about the work needed to clear a large new batch.',limit:'The snapshots were constructed and no writers, editors, or live publication systems were measured.',sources:[['Atlassian, Work in Progress Limits','https://www.atlassian.com/agile/kanban/wip-limits'],['Google SRE Workbook, Monitoring','https://sre.google/workbook/monitoring/']]},
  {slug:'source-link-placement-and-claim-recheck-effort',title:'Source-link placement and the effort required to recheck a claim',excerpt:'A small editorial comparison of endnotes, section links, and claim-adjacent references.',image:'/images/sep3-research-claim-provenance.png',question:'Where should a research assistant place a source link so an editor can recheck the claim without reconstructing the draft?',cases:'three versions of the same short brief: a bibliography-only version, section-level links, and links beside material claims',finding:'Claim-adjacent links gave the clearest starting point. Bibliographies preserved source names but left the editor to infer which sentence each source supported.',limit:'This was a qualitative document review, not a timed user study, and dense inline citations may reduce readability in other formats.',sources:[['W3C PROV Overview','https://www.w3.org/TR/prov-overview/'],['U.S. GPO Style Manual','https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2016']]},
  {slug:'editorial-correction-labels-and-repeat-error-review',title:'Can plain correction labels make repeat editorial errors easier to review?',excerpt:'A constructed test of whether specific correction reasons produce a more useful weekly publishing review.',image:'/images/sep3-research-correction-reasons.png',question:'Does a short, specific correction label help an editor find repeated failures across a daily publishing batch?',cases:'twelve fictional correction records labeled first with broad statuses and then with cause-specific descriptions',finding:'Broad labels such as "issue" and "fix" could not be grouped reliably. Labels tied to an observed gate, such as date mismatch or missing sitemap member, made repeated failure paths visible.',limit:'The records were fictional, the sample was small, and a label alone cannot establish root cause or assign blame.',sources:[['Google Search Central, Build and Submit a Sitemap','https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap'],['Schema.org datePublished','https://schema.org/datePublished']]},
  {slug:'handoff-cutoff-clarity-in-two-time-zone-publishing',title:'Handoff cutoff clarity in a two-time-zone publishing routine',excerpt:'A narrow comparison of date-only, local-time, and named-instant instructions for daily releases.',image:'/images/aug23-research-timezone-handoff.png',question:'Which written cutoff lets an editor and a Philippines-based remote assistant assign late changes to the same daily release?',cases:'three cutoff instructions applied to four fictional changes near midnight in one working zone',finding:'A named instant with both local displays removed the date ambiguity in every constructed case. A date alone and a clock time without a zone required interpretation.',limit:'The exercise covered two zones and did not test daylight-saving transitions, shift rules, system clock errors, or real deployment delays.',sources:[['W3C Date and Time Formats','https://www.w3.org/TR/NOTE-datetime'],['IANA Time Zone Database','https://www.iana.org/time-zones']]},
  {slug:'mixed-case-sampling-for-assistant-stop-rule-review',title:'Mixed-case sampling for reviewing an assistant stop rule',excerpt:'A qualitative study of what ordinary, incomplete, and authority-boundary examples reveal before a task expands.',image:'/images/sep3-research-least-privilege.png',question:'What kind of sample gives a manager useful evidence that a remote assistant understands when to stop?',cases:'two fictional task sets: five ordinary items and a mixed set containing ordinary, incomplete, conflicting, and authority-boundary items',finding:'The ordinary set tested the happy path. The mixed set also revealed whether the assistant preserved missing facts, exposed conflicts, and routed a decision instead of guessing.',limit:'Fictional examples cannot predict live behavior, measure trustworthiness, or replace access controls, audit logs, and ongoing review.',sources:[['NIST Cybersecurity Framework 2.0 Small Business Quick-Start Guide','https://www.nist.gov/publications/nist-cybersecurity-framework-20-small-business-quick-start-guide'],['FTC, Protecting Personal Information','https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business']]}
] as const;

export const sep7ResearchPosts: ResearchPost[]=studies.map((s,i)=>({
  slug:s.slug,title:s.title,excerpt:s.excerpt,published,image:s.image,imageAlt:`Editor reviewing evidence for ${s.title.toLowerCase()}`,
  keyStats:[{value:String(i===2?12:i===0?6:i===3?4:i===4?2:3),label:'Constructed cases or versions',source:'Study design'},{value:'2',label:'Authoritative context sources',source:'Source review'},{value:'0',label:'Live workers evaluated',source:'Scope'}],
  takeaways:[s.finding,'The result is a workflow observation, not a performance benchmark.','The release owner should test the record in the actual publishing system before changing policy.'],
  sections:[
    {heading:'Research question and scope',body:`${s.question} Hire Assistant Near Me examined ${s.cases}. The setting was a daily blog and research workflow supported by a Philippines-based remote assistant. The unit of review was the handoff record, not the worker. The exercise did not estimate productivity, accuracy rates, search performance, or staffing outcomes.`},
    {heading:'Method',body:`Each constructed case received the same base instruction and acceptance gates. The reviewer recorded what could be decided from the visible entry, what required another source, and where owner approval remained necessary. The comparison was qualitative. It was designed to expose ambiguity in the routine, not to produce a statistically generalizable effect size.`},
    {heading:'Observed result',body:s.finding},
    {heading:'What the sources contribute',body:`The first cited source supplies established guidance relevant to the record or control being studied. The second supplies a separate standard, technical definition, or public-business context. Neither source studies Hire Assistant Near Me, a particular remote assistant, or this constructed comparison. We use them to bound the operating question, not to claim that the observed pattern is universally proven.`},
    {heading:'Scope limits',body:s.limit+' A clear record can still fail when the underlying source is wrong, the reviewer is unavailable, or a later deployment changes the page. Legal, employment, privacy, security, and accessibility obligations require their own qualified review where applicable.'},
    {heading:'Practical implication',body:`Use the finding as a testable routine. Name the source, cutoff, expected output, stop condition, and review owner. Run a small representative batch and preserve returned questions. If the record does not let another person resume the work without guessing, revise the instruction before adding volume or access.`},
    {heading:'Conclusion',body:`This small comparison supports a narrow conclusion: ${s.finding.toLowerCase()} The evidence does not justify a universal policy. A team should repeat the check with its own articles, tools, time zones, and exception history, then record why it kept or changed the routine.`}
  ],
  tables:[{caption:'Evidence and decision boundary',columns:['Element','What this study records','What remains outside scope'],rows:[['Input',s.cases,'Representativeness of all live work'],['Observation',s.finding,'Causal or statistical proof'],['Decision','A routine to test locally','Final policy and permission approval']]}],
  sources:s.sources.map(([name,url])=>({name,url})),related
}));
