import type { ResearchPost } from './fleet-data';

const image = '/images/aug23-research-claim-provenance.png';
const related = [{label:'Research library',href:'/research'},{label:'Daily content operations',href:'/services/content-support'}];

export const sep4ResearchPosts: ResearchPost[] = [
  {
    slug:'source-density-and-editor-review-time-in-daily-research', published:'2026-09-04',
    title:'Source density and editor review time: when do more citations stop helping?',
    excerpt:'A bounded editorial study of whether adding citations makes a remote-assistant research brief easier or harder to verify.', image, imageAlt:'Editor checking a source map beside a research draft',
    keyStats:[{value:'4',label:'Claim types in the trial',source:'Study design'},{value:'3',label:'Brief versions compared',source:'Method'},{value:'1',label:'Named source for each material claim',source:'Acceptance rule'}],
    takeaways:['Citation count is a poor substitute for claim coverage.','A source should sit beside the claim it supports.','Extra links can slow review when their purpose is unclear.'],
    sections:[
      {heading:'Question and scope',body:'Does a research brief become easier to check as its source list grows? This small editorial study tested that question for Hire Assistant Near Me, where a Philippines-based remote assistant may collect evidence before an editor writes a hiring article. The unit was a material claim, not a page or bibliography. Four claim types were used: a published number, an occupational definition, a security recommendation, and an editorial inference. The study compares three constructed brief formats. It does not measure reader trust, search rankings, factual accuracy across the site, or the speed of a particular employee.'},
      {heading:'Method',body:'The first version listed two authoritative sources at the end. The second added several relevant links without mapping them to sentences. The third placed one responsive source beside each factual claim and labeled the remaining recommendation as editorial analysis. The review task was to locate the supporting passage, identify its publisher and period, and decide whether the draft wording stayed within the source. This is a qualitative workflow test, not a timed controlled experiment. The comparison asks which record makes a decision reproducible, not which layout looks more academic.'},
      {heading:'What changed during review',body:'The short bibliography worked for claims the editor already recognized, but it left the relationship between claim and source implicit. The longer list created more opening and scanning without clarifying which link mattered. The mapped version reduced that ambiguity because the editor could start with the cited passage and then inspect method or definitions. It also made one unsupported inference obvious. That inference was not wrong merely because it lacked a citation, but the draft needed to label it as a recommendation rather than borrowed evidence.'},
      {heading:'Evidence behind the approach',body:'The U.S. Government Publishing Office Style Manual provides guidance on clear attribution and reference treatment. W3C PROV describes relationships among entities, activities, and agents, which is useful for keeping a claim connected to its source and researcher. BLS technical notes show why definitions, populations, and periods must travel with statistical statements. These sources support traceable records. They do not establish an ideal citation count or prove that a mapped brief reduces review time in every newsroom.'},
      {heading:'Limitations',body:'The examples were constructed and reviewed as an editorial exercise. They did not include paywalled scholarship, conflicting authorities, translated material, broken links, or charts with multiple derived values. A subject specialist may need to read far beyond the cited passage. Too much inline detail can also make prose hard to read. The study cannot set a universal ratio between claims and citations. It supports a narrower rule: every material sourced claim needs a responsive reference whose purpose the reviewer can understand.'},
      {heading:'Operating implication',body:'Ask the research assistant to prepare a claim map before polishing the bibliography. Each row should contain the proposed sentence, source, exact support, publisher, date or period, definition, and known limitation. If one source supports several claims, the map can reuse it. If five sources merely repeat the same general advice, adding all five may not help. The editor still decides which claims matter, whether the authority is suitable, and how much context belongs in the article.'},
      {heading:'Conclusion',body:'The comparison favors explicit claim coverage over a high citation count. A brief with fewer, well-mapped authoritative sources can be easier to review than a long list whose relationship to the draft is hidden. This finding remains a workflow inference from a small constructed test. Teams should sample their own briefs and record where reviewers lose time: locating support, interpreting definitions, resolving conflict, or deciding whether a sentence is analysis. That local record is better evidence for changing the routine than an arbitrary source target.'}
    ],
    tables:[{caption:'Three source-list patterns',columns:['Pattern','Review benefit','Review cost'],rows:[['Short bibliography','Low scanning load','Claim links may be implicit'],['Long relevant list','Broader context','Purpose of each link may be unclear'],['Claim map','Support is traceable','Requires careful preparation']]}],
    sources:[{name:'U.S. Government Publishing Office Style Manual',url:'https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2016'},{name:'W3C PROV Overview',url:'https://www.w3.org/TR/prov-overview/'},{name:'BLS Technical Notes',url:'https://www.bls.gov/bls/technical-notes.htm'}], related
  },
  {
    slug:'exception-language-in-remote-assistant-handoffs', published:'2026-09-04',
    title:'Exception language in remote-assistant handoffs: which notes are easiest to resume?',
    excerpt:'A qualitative comparison of vague, procedural, and evidence-linked exception notes in daily administrative work.', image:'/images/aug20-research-dispatch-exception-queue.png', imageAlt:'Assistant comparing exception notes in a handoff queue',
    keyStats:[{value:'3',label:'Note styles compared',source:'Study design'},{value:'4',label:'Resume questions tested',source:'Method'},{value:'0',label:'Private records required',source:'Scope'}],
    takeaways:['A useful exception says what was checked.','The next owner and unresolved question belong in the note.','Urgent is not a complete status.'],
    sections:[
      {heading:'Research question',body:'When a remote assistant stops work on an exception, which wording gives the next owner enough context to resume? This study compares three note styles in a fictional daily queue: a broad status label, a description of the attempted procedure, and an evidence-linked record. The resume test asked what item is affected, what source was checked, what remains unknown, and who decides next. No customer, employee, patient, or client records were used. The result is an editorial workflow analysis, not a productivity benchmark.'},
      {heading:'Comparison method',body:'Each style described the same blocked item. The broad note said only that the case was urgent. The procedural note listed actions but omitted the source and decision owner. The evidence-linked note named the item, recorded the last source inspected, preserved the conflicting value, asked one bounded question, and identified the next owner. The evaluator then tried to resume the case using only the note. The trial was intentionally small and cannot estimate average handoff time.'},
      {heading:'Why broad labels failed',body:'Words such as urgent, waiting, done, and issue can be useful queue filters, but they do not explain the underlying state. A manager seeing urgent still has to reopen messages and reconstruct what happened. The procedural note was better because it showed effort, yet it could not establish whether the correct record had been checked. The evidence-linked note carried more context without narrating every click. Its strongest feature was the open question. The owner could answer it directly or send it to the appropriate reviewer.'},
      {heading:'Source context',body:'NIST guidance for small businesses discusses access control, accountability, and incident preparation. W3C provenance concepts describe how records can connect an entity, activity, and responsible agent. The GPO Style Manual supports precise public language. These sources do not prescribe a customer-service handoff format or prove that one note style works in every tool. They support the narrower ideas of traceability, named responsibility, and clear wording used in the comparison.'},
      {heading:'Limits and safety',body:'A fuller note is not always safer. It can expose private information in a broad channel or repeat sensitive material that belongs in a restricted system. Emergency, legal, medical, security, and financial matters may require an immediate route that bypasses the ordinary queue. This study did not test accessibility, translation, speech-to-text, high-volume operations, or crisis response. A business should decide which identifiers may appear in the handoff and where the underlying evidence remains stored.'},
      {heading:'A practical record',body:'The proposed exception record has six fields: item ID, last approved source checked, observed state, unresolved question, next owner, and time recorded with zone. Add a restricted link rather than copying sensitive content. The assistant should describe the condition without diagnosing it. The owner can then answer, redirect, or close the exception. If the same question repeats, improve the upstream example or rule instead of encouraging the assistant to infer authority.'},
      {heading:'Conclusion',body:'Evidence-linked exception notes were easiest to resume in this small comparison because they preserved both the checked source and the unanswered question. That does not justify longer notes by default. The useful record is compact, specific, and safe for its channel. Hire Assistant Near Me teams can test the format on ordinary, incomplete, and authority-boundary cases, then record which fields the next reviewer still had to reconstruct.'}
    ],
    tables:[{caption:'Exception-note comparison',columns:['Style','What it preserves','What remains unclear'],rows:[['Broad label','Queue state','Evidence and next action'],['Procedure log','Attempted steps','Source and authority'],['Evidence-linked note','Source, question, owner','Only the owner decision']]}],
    sources:[{name:'NIST Cybersecurity Basics',url:'https://www.nist.gov/itl/smallbusinesscyber/cybersecurity-basics'},{name:'W3C PROV Overview',url:'https://www.w3.org/TR/prov-overview/'},{name:'GPO Style Manual',url:'https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2016'}], related
  },
  {
    slug:'task-sample-composition-before-remote-assistant-access-expands', published:'2026-09-04',
    title:'Task-sample composition before remote-assistant access expands',
    excerpt:'Why a clean batch of ordinary work is weak evidence for granting broader system permissions.', image:'/images/sep3-research-least-privilege.png', imageAlt:'Manager reviewing ordinary and exception tasks before access approval',
    keyStats:[{value:'3',label:'Case types in the sample',source:'Study design'},{value:'2',label:'Access states compared',source:'Method'},{value:'1',label:'Owner approval gate',source:'Boundary'}],
    takeaways:['Ordinary items do not test stop rules.','Incomplete and sensitive cases belong in training samples.','Access decisions need their own approval record.'],
    sections:[
      {heading:'Question and scope',body:'What should a manager test before widening a remote assistant’s access? This study examines sample composition rather than software configuration. It compares an all-ordinary batch with a mixed batch containing one ordinary item, one incomplete item, and one item that reaches an authority boundary. The setting is Philippines-based remote administrative support for a small business. The study does not test a real worker, assign a security score, or recommend permissions for a particular system.'},
      {heading:'Method',body:'Both constructed samples used the same written task instruction. The evaluator checked whether the work showed accurate preparation, correct treatment of missing information, and a reliable stop before approval authority. The access decision was kept separate from the task-quality review. This matters because finishing the assigned work does not establish a need for more data, publishing rights, payment authority, or recovery access. The exercise is qualitative and offers no statistical estimate of error rates.'},
      {heading:'Why the ordinary batch was incomplete evidence',body:'The ordinary items showed that the assistant could follow the happy path. They did not reveal what would happen when records disagreed or a customer asked for a promise outside the script. The mixed batch exposed both conditions. The assistant’s decision to preserve the discrepancy and route the sensitive request was more informative than another correct routine entry. This does not mean managers should manufacture dangerous situations. Safe, fictional examples can test whether the written stop rule is understandable.'},
      {heading:'What the sources contribute',body:'NIST Cybersecurity Basics recommends controls such as multifactor authentication, backups, updates, and access management. The NIST Cybersecurity Framework 2.0 small-business guide helps organizations organize cybersecurity outcomes, including governance and protection. FTC business guidance provides public context for handling consumer-facing responsibilities. None of these sources specifies a three-case assistant trial or proves that it predicts performance. The sample design is an operating inference based on least access and accountable review.'},
      {heading:'Limitations',body:'A person may handle a fictional edge case differently from a live one. Three examples cannot represent every customer, record, threat, or workload. A correct stop during training can decay if incentives reward speed or managers ignore escalations. The test also cannot replace role-based access configuration, audit logs, legal review, or incident response. Sensitive test data should remain fictional or properly authorized. The result supports a cautious review habit, not a certification of trustworthiness.'},
      {heading:'Decision record',body:'Before access expands, record the new task, the exact permission requested, why the present permission is insufficient, the sample reviewed, the stop behavior observed, the approver, and the removal date or review date. Grant the narrowest role that completes the approved task. Keep owner passwords, recovery codes, broad exports, payments, deletion, and final public actions outside the first access lane unless a separate business decision requires them.'},
      {heading:'Conclusion',body:'A mixed task sample provides more relevant evidence than a clean batch of ordinary work because it tests missing context and authority boundaries. It still does not prove future performance or justify broad access. Treat task quality and permission changes as separate decisions. Managers should revisit both after real work produces enough corrections and exceptions to show where the written process holds and where it needs repair.'}
    ],
    tables:[{caption:'Sample composition and evidence',columns:['Case','What it tests','What it cannot prove'],rows:[['Ordinary','Instruction and routine accuracy','Exception behavior'],['Incomplete','Treatment of missing context','Sensitive judgment'],['Authority boundary','Stop and escalation','Future reliability']]}],
    sources:[{name:'NIST Cybersecurity Basics',url:'https://www.nist.gov/itl/smallbusinesscyber/cybersecurity-basics'},{name:'NIST CSF 2.0 Small Business Quick-Start Guide',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-20-small-business-quick-start-guide'},{name:'FTC Business Guidance',url:'https://www.ftc.gov/business-guidance'}], related
  },
  {
    slug:'publication-cutoff-times-across-editorial-time-zones', published:'2026-09-04',
    title:'Publication cutoff times across editorial time zones: a handoff study',
    excerpt:'A small analysis of whether one named instant reduces ambiguity in distributed daily publishing.', image:'/images/aug23-research-timezone-handoff.png', imageAlt:'Distributed editorial team comparing publication cutoffs across time zones',
    keyStats:[{value:'3',label:'Time expressions compared',source:'Study design'},{value:'2',label:'Working zones used',source:'Method'},{value:'1',label:'Canonical cutoff instant',source:'Acceptance rule'}],
    takeaways:['A zone belongs beside every cutoff.','One canonical instant can have local display times.','Calendar dates alone do not define a distributed deadline.'],
    sections:[
      {heading:'Research question',body:'Which deadline notation creates the least ambiguity when an editor and a Philippines-based remote assistant work in different time zones? The study compares three written instructions: a date with no time, a local time with no zone, and one canonical instant displayed in both working zones. It focuses on the publishing cutoff for a daily article. It does not measure employee scheduling, labor compliance, site uptime, daylight-saving policy, or the performance of a particular team.'},
      {heading:'Method',body:'Each instruction was applied to the same fictional draft handoff. The evaluator tried to determine whether late edits belonged in the current batch, when the final audit should begin, and what timestamp the release record should preserve. UTC and Philippine Time were used only as working examples. The test checked interpretability, not speed. A real team may prefer another canonical zone, but the chosen instant must be explicit and stable in the release record.'},
      {heading:'Observed ambiguity',body:'The date-only instruction failed near midnight because the two workers could be on different calendar dates. The local time without a zone required the reader to guess whose clock applied. The paired display was longer, but both people could map it to the same instant. It also made a late change visible. The editor could decide whether to hold that change rather than quietly assigning it to whichever date appeared on the assistant’s screen.'},
      {heading:'Evidence and standards context',body:'NIST documents use coordinated publication metadata and precise version identifiers for technical material. W3C date and time notes explain the role of time zones and standardized representations on the web. The GPO Style Manual supports clear treatment of dates and times in public writing. These sources support precise time records. They do not prescribe an editorial cutoff for Hire Assistant Near Me or prove that a paired display prevents missed deadlines.'},
      {heading:'Limits',body:'The exercise uses two zones and one daily release. It does not cover rotating shifts, daylight-saving transitions in every jurisdiction, leap seconds, offline work, or systems that store timestamps incorrectly. A clear cutoff can still fail when owners approve late changes informally or deployment takes longer than expected. Employment schedules and local requirements need separate review. The study’s conclusion is about the handoff record, not about how long anyone should work.'},
      {heading:'A release record that can be audited',body:'Write the canonical cutoff as a date, time, and named zone, then show the local equivalent for each active team. Record the draft revision, source freeze, approver, and any change submitted after the cutoff. The assistant can prepare the conversion and flag conflicts. The release owner decides whether to accept, defer, or roll back a late edit. Preserve the exact decision rather than rewriting the earlier timestamp.'},
      {heading:'Conclusion',body:'One canonical instant with local display times was the clearest of the three tested instructions. It reduced guessing about date ownership and created a usable line for late-change review. The finding comes from a small constructed comparison and should be tested in the team’s actual publishing tools. If people still disagree, inspect whether the problem is the timestamp, an unnamed approver, or a process that routinely ignores its cutoff.'}
    ],
    tables:[{caption:'Cutoff notation comparison',columns:['Notation','Reader must infer','Audit value'],rows:[['Date only','Time and zone','Low near midnight'],['Time only','Zone and date context','Unstable'],['Canonical instant plus local display','Nothing about the instant','Clear release boundary']]}],
    sources:[{name:'W3C Date and Time Formats',url:'https://www.w3.org/TR/NOTE-datetime'},{name:'NIST Publications',url:'https://www.nist.gov/publications'},{name:'GPO Style Manual',url:'https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2016'}], related
  },
  {
    slug:'correction-sampling-after-daily-content-publication', published:'2026-09-04',
    title:'Correction sampling after daily content publication: what should an editor recheck?',
    excerpt:'A post-publication sampling model for finding quiet failures without rereading every article from scratch.', image:'/images/sep3-research-correction-reasons.png', imageAlt:'Editor sampling published pages and sorting correction reasons',
    keyStats:[{value:'5',label:'Publication gates sampled',source:'Study design'},{value:'2',label:'Sampling approaches compared',source:'Method'},{value:'1',label:'Named correction owner',source:'Boundary'}],
    takeaways:['A live page can pass HTTP and still have a content error.','Sample both routine and high-risk gates.','Correction reasons should feed the next publishing checklist.'],
    sections:[
      {heading:'Question and scope',body:'After a daily batch goes live, what should an editor sample when a full reread is impractical? This study compares convenience sampling with a gate-based sample for Hire Assistant Near Me content. Five publication gates were used: route response, visible date, structured date, index and sitemap membership, and content identity. The analysis concerns editorial verification. It does not estimate the true error rate, replace accessibility testing, or recommend skipping a required full audit when a release directive calls for one.'},
      {heading:'Method',body:'The convenience approach selected the first routes shown on each index. The gate-based approach selected items that varied by family, image, title length, position, and expected failure mode, then checked all five gates on each selected route. A correction record captured the failed gate, evidence, likely cause, owner, and disposition. The exercise used a constructed release manifest. No claim is made that this sample size has statistical power.'},
      {heading:'What each approach revealed',body:'Convenience sampling was quick and verified that prominent pages loaded. It was weak at finding items on later index pages or routes with unusual metadata. The gate-based approach required more preparation but made the selection reason explicit. It also prevented one successful route from standing in for the whole batch. The useful distinction was not random versus deliberate. It was whether the sample covered materially different ways the release could fail.'},
      {heading:'Source context',body:'Google Search Central documents sitemaps, canonical URLs, and structured data used by publishers. Schema.org defines datePublished for creative works, including articles. W3C provenance concepts support retaining the relationship between a published artifact and the activity that produced it. These sources explain individual publication signals. They do not define a complete editorial quality system or validate the proposed sample design.'},
      {heading:'Limits and required full audits',body:'Sampling can miss a unique defect. Pages may change after the check because of caches, later deployments, third-party systems, or editorial edits. An HTTP 200 does not prove that a page is accurate, readable, indexed, or distinct. A sitemap entry does not prove search inclusion. High-risk claims and explicit campaign requirements may warrant checking every route. The gate-based model is useful only where sampling is permitted and the residual risk is accepted by the release owner.'},
      {heading:'Correction record',body:'For each sampled failure, keep the URL, release SHA, check time, observed value, expected value, evidence, owner, and resolution. Classify the cause only when the record supports it. Useful categories include source data, template rendering, metadata, asset, index assembly, and deployment mismatch. Do not turn the category into blame. The point is to decide which pre-publication check should change and whether the rest of the batch needs a wider audit.'},
      {heading:'Conclusion',body:'A gate-based sample is more informative than checking only the easiest visible routes because it covers different failure paths. It remains a sample and cannot prove that an entire batch is clean. When a directive requires every route to pass, audit every route. In lower-risk maintenance, use correction history to choose cases, preserve the release SHA, and expand the audit when one failure could affect related pages.'}
    ],
    tables:[{caption:'Post-publication sample design',columns:['Gate','Example evidence','Expansion trigger'],rows:[['Route','HTTP response','Any non-200'],['Date','Visible and structured value','Mismatch'],['Discovery','Index and sitemap','Missing member'],['Identity','Title, slug, and body','Collision'],['Asset','Image response and layout','Broken or distorted image']]}],
    sources:[{name:'Google Search Central, Build and Submit a Sitemap',url:'https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap'},{name:'Google Search Central, Canonical URLs',url:'https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls'},{name:'Schema.org datePublished',url:'https://schema.org/datePublished'},{name:'W3C PROV Overview',url:'https://www.w3.org/TR/prov-overview/'}], related
  }
];
