import type { ResearchPost } from './fleet-data';

const published = '2026-09-23';
const checked = 'September 23, 2026';

type Study = {
  slug:string; title:string; excerpt:string; image:string; imageAlt:string; lane:string; serviceHref:string;
  question:string; decision:string; sample:string; finding:string; boundary:string; risks:string;
  sources:readonly (readonly [string,string])[];
};

const studies:readonly Study[] = [
  {
    slug:'recruitment-assistant-candidate-record-retention-boundary',
    title:'Candidate records: when should a recruitment assistant retain, restrict, or delete them?',
    excerpt:'A retention-decision worksheet for applicant files, interview notes, accommodation details, duplicate records, and deletion requests.',
    image:'/images/assistant-elena.jpg', imageAlt:'Recruitment assistant reviewing a candidate record retention worksheet', lane:'Recruitment assistance', serviceHref:'/services/recruitment-assistance',
    question:'How can a small business delegate applicant-record administration while keeping retention policy, legal holds, accommodation information, access exceptions, and deletion approval with accountable owners?',
    decision:'Give the assistant a written record class, approved system, retention trigger, scheduled review date, access group, and disposition owner. The assistant may identify records that reach a rule; the employer or designated privacy, legal, or HR owner decides holds, exceptions, disclosure, and final deletion.',
    sample:'twenty-four fictional applicant records covering active applicants, withdrawals, duplicate profiles, interview notes, an accommodation request, an identity document sent to the wrong folder, a deletion request, and a record subject to a stated hold',
    finding:'A date alone could not justify deletion. A reviewable disposition required the record class, the event that started the retention period, the applicable policy version, any hold, and the owner authorized to act.',
    boundary:'EEOC materials describe federal recordkeeping duties and NIST supplies privacy-risk concepts; neither source decides every jurisdiction, employment relationship, system setting, or fact-specific retention question.',
    risks:'deleting a held record, retaining sensitive information without a purpose, copying accommodation details into a general tracker, treating a duplicate as disposable without checking lineage, or promising that a deletion request has been completed before an authorized owner verifies it',
    sources:[['EEOC, Recordkeeping Requirements','https://www.eeoc.gov/employers/recordkeeping-requirements'],['EEOC, Personnel Records','https://www.eeoc.gov/employers/small-business/3-who-protected-employment-discrimination'],['NIST Privacy Framework','https://www.nist.gov/privacy-framework']]
  },
  {
    slug:'ecommerce-assistant-chargeback-evidence-handoff',
    title:'Chargeback preparation: what evidence can an ecommerce assistant assemble?',
    excerpt:'A source-led handoff for orders, delivery records, customer messages, refund history, deadlines, and merchant decisions.',
    image:'/images/aug20-blog-order-exceptions.png', imageAlt:'Ecommerce assistant assembling a chargeback evidence handoff', lane:'Ecommerce assistance', serviceHref:'/services/ecommerce-assistance',
    question:'Which parts of a disputed ecommerce transaction can a remote assistant prepare without deciding whether to contest the dispute, characterizing the customer dishonestly, or submitting incomplete evidence as the merchant’s position?',
    decision:'The assistant may collect unaltered order, payment, fulfillment, delivery, policy, refund, and communication records from approved systems and index them to the processor deadline. The merchant owner decides the response, representations, remedy, and submission.',
    sample:'twenty fictional disputes involving nondelivery, duplicate billing, an unrecognized descriptor, a promised refund, a partial shipment, conflicting tracking, a subscription cancellation, damaged goods, and evidence received after an internal cutoff',
    finding:'The strongest packet was not the largest. It connected each material assertion to a dated source while preserving contradictory customer messages and unresolved delivery or refund facts for the merchant’s review.',
    boundary:'FTC rules and guidance establish consumer-protection context, while CFPB materials explain a consumer dispute process; processor rules, card-network standards, contracts, and the facts of a particular transaction still control the actual response.',
    risks:'editing a customer message, hiding a promised refund, confusing shipment with delivery, submitting credentials or full payment data, missing a processor deadline, or allowing an assistant’s summary to become an unsupported merchant certification',
    sources:[['FTC, Mail, Internet, or Telephone Order Merchandise Rule','https://www.ftc.gov/legal-library/browse/rules/mail-internet-or-telephone-order-merchandise-rule'],['FTC, Selling on the Internet: Prompt Delivery Rules','https://www.ftc.gov/business-guidance/resources/selling-internet-prompt-delivery-rules'],['CFPB, Disputing a Credit Card Charge','https://www.consumerfinance.gov/ask-cfpb/how-do-i-dispute-a-charge-on-my-credit-card-bill-en-61/']]
  },
  {
    slug:'bookkeeping-assistant-vendor-bank-change-verification',
    title:'Vendor bank-detail changes: where should bookkeeping preparation stop?',
    excerpt:'A dual-channel verification record for payment-detail requests, source documents, known contacts, approvals, and unresolved fraud signals.',
    image:'/images/aug20-blog-invoice-followup.png', imageAlt:'Bookkeeping assistant flagging a vendor bank-detail change for verification', lane:'Bookkeeping administration', serviceHref:'/services/bookkeeping-administration',
    question:'How can a bookkeeping assistant prepare a vendor payment-detail change without authenticating the request through the possibly compromised message, approving a payment, or changing the system of record?',
    decision:'Treat every payment-detail change as a held exception. Preserve the original request, compare it with the approved vendor record, route verification through a pre-established independent channel, and require named approval before any master-data or payment change.',
    sample:'eighteen fictional change requests including a familiar supplier, a lookalike domain, an urgent executive instruction, a changed remittance address, a new overseas account, an attachment-only request, a known-contact callback, and a request arriving after an invoice was approved',
    finding:'Replying to the requesting email did not independently verify it. The recoverable record showed where the trusted contact came from, who performed the check, what was confirmed, which system remained unchanged, and who could approve the next action.',
    boundary:'FBI and CISA materials describe business-email-compromise and phishing risks, and NIST supplies least-privilege guidance. They do not authenticate a vendor, approve a bank account, or replace the company’s bank, accounting, insurance, legal, and payment controls.',
    risks:'calling a number supplied in the suspicious request, altering vendor master data before approval, exposing full bank information in a broad ticket, treating urgency or an executive name as proof, or letting invoice approval silently authorize a different payee account',
    sources:[['FBI, Business Email Compromise','https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/business-email-compromise'],['CISA, Recognize and Report Phishing','https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'],['NIST SP 800-53 Rev. 5, AC-6 Least Privilege','https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final']]
  },
  {
    slug:'project-assistant-dependency-status-expiry-record',
    title:'Project dependencies: when should an assistant treat a status update as expired?',
    excerpt:'A time-aware dependency record for status source, observation time, owner, blocking effect, confidence, and recheck rules.',
    image:'/images/aug21-research-calendar-context.png', imageAlt:'Project assistant reviewing a time-aware dependency status board', lane:'Project coordination', serviceHref:'/services/project-coordination',
    question:'What evidence lets a project assistant report a dependency without presenting an old comment, tentative forecast, or ambiguous task state as a current commitment?',
    decision:'Record the exact source, observed timestamp and named time zone, reporting owner, stated condition, affected work, confidence label, next recheck, and decision owner. Expiry is a business rule, not something the assistant should infer from silence.',
    sample:'twenty-two fictional dependencies across four time zones, including an unchanged dashboard, a tentative delivery date, a superseded chat update, a blocked approval, a vendor estimate, a reopened task, a missing owner, and a status copied into two reports',
    finding:'A green label without provenance became misleading as conditions changed. A status could remain factually copied yet cease to be decision-ready because its observation time, authority, or underlying condition had expired.',
    boundary:'IANA supplies time-zone data and NIST logging guidance explains why timestamps and event context matter. Neither source defines project health, a universal status lifetime, or authority to move a milestone.',
    risks:'dropping the time zone, converting an estimate into a commitment, overwriting a contrary update, allowing copied status to outlive its source, assigning blame from incomplete records, or moving dates and priorities without the accountable owner',
    sources:[['IANA Time Zone Database','https://www.iana.org/time-zones'],['NIST SP 800-92, Guide to Computer Security Log Management','https://csrc.nist.gov/pubs/sp/800/92/final'],['NIST, Cybersecurity Framework 2.0','https://www.nist.gov/cyberframework']]
  },
  {
    slug:'sales-assistant-opt-out-suppression-handoff',
    title:'Sales follow-up opt-outs: what should a suppression handoff preserve?',
    excerpt:'A channel-specific record for opt-out wording, receipt time, contact identity, campaign scope, system updates, and unresolved matches.',
    image:'/images/assistant-daniel.jpg', imageAlt:'Sales assistant recording an opt-out suppression handoff', lane:'Sales administrative support', serviceHref:'/services/sales-administrative-support',
    question:'How can a sales assistant process clear commercial-email opt-outs and route uncertain requests without inventing consent, narrowing a request for convenience, or allowing a later import to restore a suppressed contact?',
    decision:'Preserve the original request, channel, received time, address or identifier, relevant campaign and account, applied rule, systems updated, unmatched duplicates, and owner. Clear routine opt-outs follow the approved suppression procedure; ambiguity, identity conflicts, legal demands, and policy exceptions go to the designated owner.',
    sample:'twenty-six fictional contact events including a standard unsubscribe, a reply saying stop, an alias, duplicate CRM records, a shared mailbox, a bounced address, a request limited to one newsletter, a sales call objection, a later list import, and an account with several contacts',
    finding:'A single suppressed flag was insufficient when identity and channel were unclear. The durable handoff linked the requester’s words to the affected identifiers and preserved scope rather than broadening or narrowing it silently.',
    boundary:'FTC CAN-SPAM guidance addresses commercial email and makes clear that businesses retain responsibility for work done on their behalf. It does not resolve every channel, jurisdiction, privacy request, contract, or identity ambiguity.',
    risks:'requiring unnecessary information before honoring a clear email opt-out, suppressing the wrong person, treating silence as consent, losing the original request, restoring a suppressed record during import, or letting an assistant interpret a broader privacy or legal demand',
    sources:[['FTC, CAN-SPAM Act: A Compliance Guide for Business','https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business'],['FTC, Privacy and Security Guidance','https://www.ftc.gov/business-guidance/privacy-security'],['NIST Privacy Framework','https://www.nist.gov/privacy-framework']]
  }
];

function makePost(s:Study):ResearchPost {
  const sourceNames=s.sources.map(([name])=>name).join('; ');
  return {slug:s.slug,title:s.title,excerpt:s.excerpt,published,image:s.image,imageAlt:s.imageAlt,
    keyStats:[{value:'1',label:'Named decision owner required',source:'Study method'},{value:String(s.sources.length),label:'Authoritative sources checked',source:'Source ledger'},{value:'0',label:'Customer or worker outcomes measured',source:'Study boundary'}],
    takeaways:[s.decision,'Test ordinary items, conflicts, missing information, and stop cases before expanding the lane.','Keep original evidence, analysis, owner decisions, and uncertainty visibly separate.'],
    sections:[
      {heading:'Research question and buyer decision',body:`${s.question} This report addresses that narrow decision for a local business considering ${s.lane.toLowerCase()} from a Philippines-based remote assistant. The operational conclusion is: ${s.decision} The conclusion is source-informed analysis, not a claim that one workflow fits every business, jurisdiction, tool, worker, customer, or transaction. It does not evaluate a Hire Assistant Near Me candidate or promise speed, savings, accuracy, compliance, revenue, or another business result. The useful buying question is not whether an assistant can touch the record. It is whether the role has a defined source, permitted action, stop condition, evidence trail, and available owner for the decisions that remain.`},
      {heading:'Methodology and constructed sample',body:`We performed a qualitative desk review and a bounded walkthrough on ${checked}. The unit of analysis was one task decision within ${s.sample}. Before reviewing each fictional case, we recorded the approved source, permitted verb, minimum evidence, stop rule, owner, and completion state. We then asked whether a second reviewer could reconstruct what was known, what action was allowed, what remained uncertain, and who controlled the next step. The cases deliberately included ordinary work, missing inputs, conflicting records, urgency, sensitive information, and requests outside the proposed role. No customer, applicant, assistant, employee, private account, production system, payment, revenue result, or service outcome was observed. We calculated no rate, benchmark, effect size, statistical significance, or causal relationship. The sample tests whether a proposed instruction is reviewable; it does not estimate how often any condition occurs.`},
      {heading:'What the sources establish',body:`The source set was checked on ${checked}: ${sourceNames}. These primary or authoritative publishers supply definitions, duties, risk concepts, or control guidance within their own stated scope. ${s.boundary} The publishers did not study Hire Assistant Near Me, compare staffing providers, endorse Philippines-based assistance, validate these fictional cases, or guarantee this proposed control. Connecting their material to a remote administrative lane is our analysis. A future editor should reopen each link, confirm that the material remains current and responsive, record a new checked date, and revise any affected conclusion. A working URL is not enough: the source must support the proposition for which it is used, and adjacent guidance must not be stretched into proof of a company-specific result.`},
      {heading:'Finding from the walkthrough',body:`${s.finding} Across the constructed sample, access to a record never created authority to make every decision involving that record. Familiar work changed character when evidence was missing, contradictory, sensitive, late, or tied to an external commitment. A precise stop with a recoverable handoff was more useful than a polished output that concealed an assumption. The owner response path mattered as much as the assistant’s instruction: an escalation rule without an available decision owner moved uncertainty into an aging queue. These observations apply only to the fictional cases. They are hypotheses to test in a protected pilot, not evidence about prevalence, employee performance, customer satisfaction, legal compliance, cost, or commercial value.`},
      {heading:'Define the role with sources and verbs',body:`Write the lane as observable verbs such as view, collect, copy, label, compare, draft, route, change, send, delete, approve, publish, or pay. Attach each permitted verb to an approved source and completion record, then name the owner-held action beside it. A broad title such as ${s.lane.toLowerCase()} cannot show whether a person may alter a field, communicate externally, resolve an exception, or administer access. Examples should include a clean case, a missing-source case, a conflict, sensitive information, urgency, and a request beyond authority. State what to do when an example and the live record differ. The assistant should return uncertainty in a defined format instead of being rewarded for a tidy guess. Role design becomes fairer when quality can be evaluated against supplied evidence rather than unstated owner expectations.`},
      {heading:'Build the minimum evidence handoff',body:`A useful handoff identifies the work item without copying unrelated sensitive information. It records the source location, observation time with a named time zone, last permitted action, exact missing or conflicting fact, decision requested, current owner, and due or recheck time. When a change needs review, preserve the prior and proposed values. Link to the approved system of record instead of building a shadow database in chat or comments. Apply the business’s retention and access rules. Keep credentials, authentication secrets, full payment details, and unrelated personal information out of general notes. Another reviewer should understand the stop without asking the assistant to reconstruct events from memory. The record supports judgment; it does not transfer responsibility to the person who assembled it.`},
      {heading:'Pilot and review method',body:`Start with a small representative batch and deliberately include routine items, incomplete inputs, conflicting records, one urgent request, sensitive information, and an action beyond authority. Freeze the instruction version and review rubric for one comparison window. Score source fidelity, permitted action, correct stop, evidence preservation, and handoff completeness separately. Count false stops as well as unsafe continuation: excessive escalation can make a lane unusable, while proceeding through uncertainty can create larger business risk. Review disagreements at the rule level. Ask whether the approved source, example, wording, permission, system state, or owner response path needs repair before granting broader access. Do not change the rubric halfway through and then present unlike samples as a trend. The purpose is to decide whether this specific lane is ready, not to manufacture a favorable performance story.`},
      {heading:'Risks and safeguards',body:`The principal risks are ${s.risks}. Address them with named accounts, least-privilege permissions, multifactor authentication where available, approved systems of record, examples containing stop cases, and a decision owner available during agreed working hours. Separate correction from blame. A correction log should show the evidence gap and instruction revision rather than encourage quiet rework that erases history. Do not measure success only by volume or response speed. Include unsafe continuations, unnecessary escalations, unresolved queue age, evidence completeness, owner review time, and reversals so one favorable number does not conceal transferred work or risk. Where law, contract, regulated advice, money movement, account security, or sensitive personnel judgment is involved, route the decision to a qualified accountable person.`},
      {heading:'Buyer checklist before hiring',body:`List the recurring work and the systems it touches. Mark actions that create commitments, alter money or access, expose sensitive information, interpret policy, or communicate publicly. Choose which remain with the owner or qualified team member. For the proposed assistant lane, write the input, permitted actions, finished output, stop reasons, evidence fields, expected response window, reviewer, and escalation route. Confirm that the tools can implement the stated permission boundary rather than relying on a policy that broad access makes impossible. Prepare representative practice cases without private data and agree how corrections will be recorded. Ask how a Philippines-based schedule overlaps with the owner who must answer exceptions. If no owner can respond, narrow the lane or change the handoff timing before hiring.`},
      {heading:'Limitations and evidence-led conclusion',body:`This analysis uses public guidance and constructed cases, not field observation. It cannot establish the right policy for a particular jurisdiction, industry, contract, system, transaction, applicant, customer, or worker. Source pages can change, and a general framework cannot verify private facts or replace legal, security, accounting, HR, or other specialist advice. The conclusion is therefore deliberately narrow: ${s.decision} A buyer should test that design with protected records and accountable review before expanding access. If errors cluster around one source, state, or exception, repair the workflow rather than assuming more volume will solve it. If the task cannot be separated from owner judgment or implemented with appropriate permissions, keep it with the accountable team. A smaller, observable lane is a stronger starting brief than a broad promise of assistance.`}
    ],
    tables:[{caption:`${s.lane} decision record`,columns:['State','Assistant output','Owner boundary'],rows:[['Prepared','Source-linked draft or indexed evidence','No implied approval'],['Held','Conflict, missing fact, or risk signal','Named owner decides'],['Completed','Recorded permitted action and evidence','Owner retains policy and exception authority']]}],
    sources:s.sources.map(([name,url])=>({name:`${name} (checked ${checked})`,url})),
    related:[{label:`Review ${s.lane.toLowerCase()} services`,href:s.serviceHref},{label:'Browse the Research library',href:'/research'}]
  };
}

export const sep23Hira94ResearchPosts:readonly ResearchPost[] = studies.map(makePost);
