import type { ResearchPost } from './fleet-data';
const published = '2026-09-11';

const studies = [
 ['reviewer-blind-order-record-audit','Does hiding preparer identity change an order-record review?','A bounded comparison of the same fictional order records reviewed with and without preparer labels.','/images/aug23-research-editor-boundary.png','whether temporarily hiding a preparer label changes completeness and escalation classifications','sixteen fictional order records reviewed in labeled and unlabeled passes during one session','Differences between the two passes identified records for a second review, but did not explain why a classification changed.','The fictional sample used one reviewer and did not measure bias, accuracy, worker performance, or customer outcomes.',[['NIST Human-Centered Cybersecurity','https://www.nist.gov/programs-projects/human-centered-cybersecurity'],['OPM Structured Interviews','https://www.opm.gov/policy-data-oversight/assessment-and-selection/structured-interviews/']],16],
 ['exception-age-bucket-handoff-study','Can exception-age buckets improve a daily handoff?','A constructed queue comparison using received time, last action, waiting reason, and named owner.','/images/sep3-research-correction-reasons.png','whether explicit age buckets make unresolved handoffs easier to locate without implying urgency or fault','twenty fictional exceptions observed across a seven-day simulated window','Age buckets made waiting items easier to locate, while the waiting reason remained necessary to interpret each item.','The exercise observed no live team, service level, customer impact, or outcome from faster review.',[['Project Management Institute Process Groups','https://www.pmi.org/standards/process-groups'],['NIST Privacy Framework','https://www.nist.gov/privacy-framework']],20],
 ['source-snapshot-field-reconstruction-test','Testing field-level reconstruction from a source snapshot','A constructed provenance comparison of URL-only notes with timestamped excerpts and named fields.','/images/aug23-research-source-scope.png','whether a timestamped excerpt and named field help a later reviewer reconstruct a factual handoff','twelve fictional records reviewed in one session with stable, changed, inaccessible, and ambiguous source states','Field names and excerpts reduced reconstruction ambiguity, but a snapshot did not prove that a source was accurate or authoritative.','No archival service, live publication, legal record, or multi-reviewer agreement test was included.',[['W3C PROV-O','https://www.w3.org/TR/prov-o/'],['W3C Data on the Web Best Practices','https://www.w3.org/TR/dwbp/']],12],
 ['stop-rule-disagreement-coding-exercise','How consistently can reviewers code a written stop rule?','A descriptive exercise comparing two independent classifications of fictional assistant-work scenarios.','/images/aug21-research-role-boundary.png','whether concrete examples and counterexamples make a stop rule easier to apply consistently','eighteen fictional scenarios reviewed by two people during a single session','The reviewers agreed more often after examples were added, while mixed-authority cases still required owner interpretation.','The small fictional exercise supports no population estimate, causal effect, legal conclusion, or claim about a real assistant.',[['OPM Assessment Decision Guide','https://www.opm.gov/policy-data-oversight/assessment-and-selection/reference-materials/assessmentdecisionguide.pdf'],['NIST AI Risk Management Framework','https://www.nist.gov/itl/ai-risk-management-framework']],18],
 ['family-manifest-route-diff-observation','Observing route-family errors with a manifest diff','A bounded comparison of Blog and Research manifests against fictional release routes.','/images/sep3-research-topic-distance.png','whether separate expected-route manifests expose omission, duplication, and cross-family placement','seventeen fictional routes examined during one simulated release window','The diff exposed the seeded route-family discrepancies, but did not assess article quality or whether a route should be published.','The routes were constructed, the expected manifest was assumed correct, and no live cache, crawler, redirect, or deployment system was observed.',[['Sitemaps protocol','https://www.sitemaps.org/protocol.html'],['WHATWG HTML Links','https://html.spec.whatwg.org/multipage/links.html']],17],
] as const;

export const sep11ResearchPosts: ResearchPost[] = studies.map((s) => {
 const [slug,title,excerpt,image,question,cases,finding,limitation,sources,count] = s;
 return {slug,title,excerpt,published,image,imageAlt:`Research illustration for ${title.toLowerCase()}`,keyStats:[{value:String(count),label:'Constructed records examined',source:'Study design'},{value:'2',label:'Primary or standards sources reviewed',source:'Source review'},{value:'0',label:'Live workers or search outcomes measured',source:'Scope'}],takeaways:[finding,'The result is a workflow observation, not a causal or performance claim.','Repeat the check on representative live work before changing release policy.'],sections:[{heading:'Research question, scope, population, and observation window',body:`Hire Assistant Near Me asked ${question}. The study used ${cases} for a proper daily blog and research routine. The unit of analysis was one route, record, or draft. We did not evaluate an assistant, editor, customer, or search result.`},{heading:'Methodology',body:'We held the underlying case facts constant, prepared the comparison states named in the study design, and recorded what a reviewer could verify, what remained ambiguous, and which decision required an accountable owner. The analysis was qualitative and descriptive. We calculated no statistical effect, causal relationship, productivity change, or population estimate.'},{heading:'Observed result',body:finding},{heading:'How the sources were used',body:'The references supply protocol, provenance, publishing, or legal context for the fields under review. They do not study Hire Assistant Near Me, validate the fictional sample, or show that the observation transfers to another publishing system.'},{heading:'Inference and causal boundaries',body:'The finding supports a release check worth testing. It does not establish worker quality, legal compliance, accessibility, originality, indexing, ranking, security, or the correct policy for a specific organization.'},{heading:'Limitations',body:`${limitation} Standards and source pages can change, and another reviewer may classify the same evidence differently.`},{heading:'Practical implication',body:'Pilot the control on a small representative batch. Keep the underlying evidence, record disagreements, and require a named publication owner to resolve exceptions before release rules or permissions change.'},{heading:'Conclusion',body:`Within this narrow constructed exercise, ${finding.toLowerCase()} A live test with documented review criteria is still required.`}],tables:[{caption:'Study boundary',columns:['Element','Included','Not established'],rows:[['Input',cases,'Representativeness of all publishing work'],['Observation',finding,'Causal or statistical proof'],['Next decision','A release control to test','Final publication or access policy']]}],sources:sources.map(([name,url])=>({name,url})),related:[{label:'Research library',href:'/research'},{label:'Content support services',href:'/services/content-support'}]};
});
