const published = '2026-09-18';

type Brief = {
  slug: string; title: string; keyword: string; role: string; outcome: string;
  tasks: string; keep: string; tools: string; sample: string; metric: string;
};

const briefs: Brief[] = [
  {slug:'how-to-hire-virtual-executive-assistant-small-business',title:'How to hire a virtual executive assistant for a small business',keyword:'hire virtual executive assistant for small business',role:'virtual executive assistant',outcome:'protect the owner’s attention by preparing calendars, meeting material, follow-ups, and decision queues',tasks:'calendar preparation, inbox triage, meeting agendas, action registers, travel research, and follow-up drafts',keep:'final priorities, commitments, sensitive personnel decisions, money movement, and messages that speak as the executive',tools:'calendar, shared inbox, task board, document workspace, and password manager',sample:'prepare tomorrow’s calendar brief with conflicts, missing links, travel buffers, and decisions needed by 3 p.m.',metric:'briefs ready by the cutoff, avoidable calendar conflicts, returned drafts by reason, and owner review time'},
  {slug:'virtual-receptionist-vs-answering-service-small-business',title:'Virtual receptionist vs. answering service: which fits a small business?',keyword:'virtual receptionist vs answering service',role:'virtual receptionist',outcome:'give callers a consistent first response while keeping promises and judgment with the business',tasks:'answering approved call types, recording messages, routing urgent categories, scheduling within approved rules, and updating a call log',keep:'emergency judgment, clinical or legal advice, refunds, custom quotes, complaint resolution, and any promise outside the approved script',tools:'business phone system, approved scripts, calendar, CRM, and escalation channel',sample:'handle routine new-customer calls during the published window and route exceptions with the recording or complete call note',metric:'calls answered in the agreed window, complete notes, correct routing, abandoned calls, and script exceptions'},
  {slug:'inbox-management-virtual-assistant-job-description',title:'Inbox management virtual assistant job description: scope, rules, and scorecard',keyword:'inbox management virtual assistant job description',role:'inbox management assistant',outcome:'turn a crowded shared inbox into labeled, reviewable queues without hiding decisions in email',tasks:'sorting by approved categories, identifying deadlines, linking related records, drafting routine replies, and maintaining a waiting-for list',keep:'legal notices, personnel matters, security alerts, account recovery, binding commitments, deletions, and novel customer disputes',tools:'shared inbox, CRM, task board, approved templates, and escalation channel',sample:'triage the morning inbox, draft only from approved templates, and deliver an exception list before the owner’s review block',metric:'messages classified by cutoff, overdue threads, reopened items, draft corrections by reason, and unresolved age'},
  {slug:'calendar-management-virtual-assistant-hiring-guide',title:'Calendar management virtual assistant hiring guide for busy owners',keyword:'calendar management virtual assistant',role:'calendar management assistant',outcome:'prepare a workable schedule with complete context while the owner retains priority and attendance decisions',tasks:'checking invitations, collecting agendas and links, applying approved buffers, proposing open slots, and flagging conflicts across time zones',keep:'accepting strategic meetings, moving protected commitments, sharing private attendee details, waiving booking rules, and promising availability',tools:'calendar, scheduling page, video-meeting tool, contact directory, and written scheduling rules',sample:'prepare a three-day calendar audit that identifies double bookings, missing context, travel risk, and decisions for the owner',metric:'meetings with complete context, conflicts found before the cutoff, reschedules caused by admin errors, and owner review minutes'},
  {slug:'crm-data-entry-assistant-hiring-checklist',title:'CRM data entry assistant hiring checklist: accuracy, access, and review',keyword:'CRM data entry assistant hiring checklist',role:'CRM data entry assistant',outcome:'keep customer records usable without allowing silent merges, invented sales progress, or uncontrolled exports',tasks:'updating approved fields, normalizing formats, attaching source records, preparing duplicate candidates, and logging missing information',keep:'merging or deleting records, changing deal stages without evidence, exporting the database, altering permissions, and inventing contact facts',tools:'CRM limited-role account, source inbox or forms, duplicate queue, field dictionary, and audit report',sample:'clean one hundred recent records while leaving every uncertain match in a source-linked review queue',metric:'verified fields updated, corrections by field, duplicate candidates accepted or rejected, unsupported edits, and queue age'},
  {slug:'lead-follow-up-virtual-assistant-hiring-guide',title:'Lead follow-up virtual assistant: a practical hiring and handoff guide',keyword:'lead follow up virtual assistant',role:'lead follow-up assistant',outcome:'make approved, timely contact and preserve the prospect’s response without turning the assistant into an unsupervised salesperson',tasks:'sending approved first touches, recording consent and replies, scheduling qualified conversations, maintaining next-action dates, and stopping outreach when requested',keep:'changing offers, negotiating, making performance claims, overriding consent, deciding qualification exceptions, and sending unapproved mass campaigns',tools:'CRM, approved email or phone channel, scheduling page, template library, and do-not-contact controls',sample:'work yesterday’s opted-in inquiry queue and leave every pricing, fit, or complaint question for the sales owner',metric:'eligible leads attempted, replies recorded, meetings scheduled, opt-outs honored, overdue next actions, and correction reasons'},
  {slug:'customer-service-virtual-assistant-small-business-guide',title:'Customer service virtual assistant guide for small businesses',keyword:'customer service virtual assistant small business',role:'customer service assistant',outcome:'resolve documented routine questions quickly and move true exceptions to a named owner with full context',tasks:'answering policy-based questions, checking order or account status, documenting troubleshooting already attempted, tagging themes, and escalating exceptions',keep:'refund exceptions, safety issues, legal threats, account ownership disputes, policy changes, public crisis responses, and unsupported promises',tools:'help desk, knowledge base, order or account view, approved macros, and urgent escalation channel',sample:'resolve routine status questions from the approved knowledge base and create complete handoffs for every exception',metric:'first responses in the service window, complete resolutions, reopened tickets, escalation accuracy, and macro corrections'},
  {slug:'bookkeeping-support-virtual-assistant-task-list',title:'Bookkeeping support virtual assistant task list with clear financial boundaries',keyword:'bookkeeping support virtual assistant tasks',role:'bookkeeping support assistant',outcome:'prepare complete financial records for review without transferring payment authority or accounting judgment',tasks:'collecting invoices and statements, matching source documents, categorizing items from written rules, maintaining missing-document lists, and preparing reconciliation questions',keep:'releasing payments, changing bank details, signing filings, giving tax advice, resolving unexplained differences, and approving journal entries',tools:'document portal, restricted accounting-system role, receipt inbox, vendor master read access, and exception register',sample:'prepare the month-end document packet and list every missing receipt, duplicate invoice, and unmatched transaction for the bookkeeper',metric:'documents matched by cutoff, unresolved items by age, corrections by category, duplicate flags, and reviewer time'},
  {slug:'real-estate-transaction-coordinator-assistant-guide',title:'Real estate transaction coordinator assistant: scope and hiring guide',keyword:'real estate transaction coordinator assistant',role:'real estate transaction coordination assistant',outcome:'keep dates, documents, and handoffs visible while licensed professionals retain advice, negotiation, and compliance decisions',tasks:'maintaining a milestone tracker, requesting approved documents, recording receipt, preparing status summaries, scheduling permitted appointments, and flagging missing signatures',keep:'interpreting contracts, giving legal advice, negotiating terms, representing licensure, changing deadlines, and declaring a file compliant',tools:'transaction platform, document workspace, calendar, approved request templates, and broker escalation route',sample:'prepare a source-linked file status showing completed milestones, missing documents, approaching dates, and questions for the responsible agent',metric:'milestones updated from evidence, missing items found early, incorrect status changes, overdue requests, and agent review time'},
  {slug:'ecommerce-virtual-assistant-operations-guide',title:'Ecommerce virtual assistant operations guide: orders, catalog, and support',keyword:'ecommerce virtual assistant operations',role:'ecommerce operations assistant',outcome:'keep routine catalog, order, and support queues moving without granting uncontrolled store or payment authority',tasks:'checking order exceptions, preparing product-data updates, documenting returns, answering approved status questions, and reconciling inventory discrepancies for review',keep:'issuing exception refunds, changing prices, publishing unsupported claims, selecting substitutions, editing payment settings, and deleting products or orders',tools:'store staff account, help desk, shipping portal, product source sheet, and exception queue',sample:'prepare the daily order exception report with source events, customer wording, permitted next step, and decisions required',metric:'orders cleared under policy, catalog corrections, reopened cases, incorrect edits, exception age, and owner decisions outstanding'},
  {slug:'medical-office-virtual-assistant-administrative-scope',title:'Medical office virtual assistant: define a safe administrative scope',keyword:'medical office virtual assistant administrative scope',role:'medical office administrative assistant',outcome:'support documented scheduling and records workflows while clinical judgment and privacy governance stay with the practice',tasks:'collecting patient-supplied administrative information, scheduling under written rules, checking referral document presence, routing messages, and maintaining nonclinical work queues',keep:'triage, diagnosis, treatment advice, interpreting results, changing prescriptions, disclosing records outside the approved process, and deciding emergencies',tools:'practice-approved systems with role-based access, scheduling rules, message categories, privacy training, and an immediate clinical escalation route',sample:'prepare the referral completeness queue without judging medical necessity, urgency, diagnosis, or treatment',metric:'administrative records complete, messages routed to the approved role, access exceptions, scheduling corrections, and unresolved queue age'},
  {slug:'law-firm-virtual-assistant-administrative-scope',title:'Law firm virtual assistant: administrative scope, safeguards, and scorecard',keyword:'law firm virtual assistant administrative scope',role:'law firm administrative assistant',outcome:'prepare organized intake and matter records while lawyers retain advice, privilege judgments, conflicts decisions, and legal deadlines',tasks:'collecting caller-supplied facts, indexing documents, scheduling under approved rules, formatting from templates, maintaining request lists, and preparing status summaries',keep:'giving legal advice, promising representation, deciding conflicts, interpreting deadlines, changing substantive legal text, and disclosing matter information',tools:'firm-approved matter system, secure document workspace, scheduling rules, template library, and attorney escalation channel',sample:'prepare an intake packet that preserves the caller’s own words and routes every legal or conflicts question to the responsible lawyer',metric:'packets complete by cutoff, source links present, misrouted sensitive records, corrections by reason, and attorney review time'},
];

const officialSources = [
  {name:'NIST Cybersecurity Framework 2.0 Small Business Quick-Start Guide',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-20-small-business-quick-start-guide',note:'Official risk-management context for small and medium-sized businesses.'},
  {name:'FTC, Protecting Personal Information: A Guide for Business',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business',note:'Official guidance on understanding, limiting, protecting, and disposing of business information.'},
  {name:'CISA, Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication',note:'Official account-security guidance used for sign-in planning.'},
  {name:'IRS, Independent contractor defined',url:'https://www.irs.gov/businesses/small-businesses-self-employed/independent-contractor-defined',note:'Official U.S. classification overview; businesses should apply the rules to their facts.'},
] as const;

export const sep18BlogPosts = briefs.map((b, index) => {
  const paragraphs = [
    `Hiring a ${b.role} works best when the role is defined around an observable business outcome: ${b.outcome}. “Help with everything” is not a usable job description. It prevents candidates from judging fit and prevents the owner from reviewing quality. Start with one queue, one cutoff stated with a time zone, one accountable reviewer, and examples of both acceptable work and work that must stop.`,
    `A practical first scope can include ${b.tasks}. Break that list into units someone can count and inspect. For each unit, name the trigger, approved source, expected output, due time, and destination. The assistant should never need to guess which record is current or whether an attractive shortcut is permitted. If the source is missing or inconsistent, the output is an exception note, not an invented answer.`,
    `The owner or qualified professional should retain ${b.keep}. Put these exclusions beside the task list rather than hiding them in a policy folder. A boundary is useful only when the assistant can recognize the moment it applies, pause without penalty, preserve the evidence already checked, and route a bounded question to a named person who will answer it.`,
    `Use ${b.tools}. Create a named account for the assistant and begin with the narrowest role that supports the first workflow. Keep account recovery, permission administration, bulk export, destructive actions, and unrelated records out of the starting scope. Multifactor authentication and a password manager reduce dependence on shared credentials, but they do not replace a written access review and a prompt offboarding checklist.`,
    `A representative paid work sample is more useful than a trivia test. Ask the candidate to ${b.sample}. Provide redacted material, a clear deadline, and the same stop rules the live role will use. Review whether the candidate followed the source trail, preserved uncertainty, wrote a useful escalation, and communicated before the cutoff. Do not use live customer credentials or sensitive production data for a hiring exercise.`,
    `On the first day, walk through an ordinary item, an incomplete item, a conflicting-source item, and a sensitive exception. Ask the assistant to explain which source controls, what they would record, where they would stop, and who receives the question. Then let the assistant complete a small supervised batch. Correct the instruction and example when a reasonable person could interpret the rule more than one way.`,
    `A daily handoff should separate ready work, items waiting on the business, items waiting on a customer or outside party, and closed items. Each row needs a source, owner, next action, and timestamp. This structure makes workload visible without treating motion as completion. It also prevents an old item from appearing current merely because somebody edited a note or moved it between columns.`,
    `For the first thirty days, review ${b.metric}. Counts need definitions: a “completed” item should satisfy the written output rule, not merely have activity. Sample the source trail as well as the final wording. Group corrections by cause—missing source, unclear instruction, access problem, skill gap, or owner delay—so the response fixes the real constraint instead of blaming every exception on speed.`,
    `Philippines-based remote staffing can cover online work during agreed hours, but “near me” does not mean physical local coverage. Separate errands, on-site custody, walk-in reception, paper originals, and locally licensed work before candidate matching. If the workflow mixes remote preparation with a local step, name both owners and define the handoff rather than implying the remote assistant can perform work that requires presence.`,
    `Before expanding the role, review a representative week and change one variable at a time. Add an adjacent task only when the existing queue is traceable, exceptions reach the right owner, access remains appropriate, and review time is sustainable. More volume is not proof that the system works. A controlled expansion has a new example, permission decision, stop rule, and rollback plan.`,
    `Worker classification, privacy, professional duties, and record-retention obligations depend on the business, jurisdiction, relationship, and data involved. A staffing provider can help shape and recruit for the role, but it should not be presented as legal, tax, clinical, or security advice. Have the appropriate professional review requirements that apply to the actual arrangement before sensitive work begins.`,
    `Bring this role brief to a hiring conversation: the outcome, recurring units, hours and time zone, approved systems, access limits, examples, reviewer, escalation route, and thirty-day measures. Hire Assistant Near Me recruits and hires assistants in the Philippines for remote work. The clearest next step is not choosing a résumé from a vague list; it is giving the staffing team a role that a candidate can understand and an owner can manage.`,
  ];
  const headings = ['Define the outcome before the title','Turn duties into inspectable work units','Write the authority boundary','Plan access before granting it','Use a representative work sample','Train on ordinary and exceptional cases','Make the daily handoff visible','Review a 30-day scorecard','Separate remote and local work','Expand one controlled step at a time','Review legal and privacy obligations','Bring a complete brief to the hiring call'];
  return {
    slug:b.slug, mainKeyword:b.keyword, title:b.title,
    excerpt:`Define the duties, access limits, work sample, first-month scorecard, and owner decisions for a Philippines-based ${b.role}.`,
    published, richPublished:true, minutes:12, image:['/images/assistant-maya.jpg','/images/assistant-daniel.jpg','/images/assistant-elena.jpg'][index%3], imageAlt:`Philippines-based ${b.role} working from a documented task queue`,
    sourceBody:`Publication date: September 18, 2026.\n\n${paragraphs.join('\n\n')}`,
    takeaways:[`Start the ${b.role} with one measurable workflow.`,`Keep ${b.keep} with the accountable owner.`,`Use named, limited access and a visible exception queue.`],
    detail:{
      revision:`${published}-${b.slug}-r1`, directAnswer:paragraphs.slice(0,2),
      bodyLinks:[{href:'/services',label:'compare assistant service lanes'},{href:'/compare/local-vs-remote-assistant',label:'separate local and remote work'},{href:'/contact-us',label:'prepare a role brief'}],
      sections:headings.map((heading,n)=>({heading,paragraphs:[paragraphs[n]]})),
      decisionRows:[{need:`Recurring ${b.role} preparation`,fit:'Philippines-based remote assistant',reason:'The work is online, documented, and reviewable.'},{need:'Physical presence or custody',fit:'Local employee or vendor',reason:'The task cannot be completed through approved online systems.'},{need:'Judgment, commitment, or sensitive exception',fit:'Owner or qualified professional',reason:`This includes ${b.keep}.`}],
      planningNumbers:[{value:'1 queue',label:'Starting scope',note:'One repeatable work family.'},{value:'4 cases',label:'Training sample',note:'Ordinary, incomplete, conflicting, and sensitive.'},{value:'1 owner',label:'Escalation route',note:'A named person who answers stopped items.'},{value:'30 days',label:'Review point',note:'Keep, narrow, repair, or add one adjacent duty.'}],
      scripts:[{title:'Candidate work sample',text:`Using redacted material, ${b.sample}. Link each source, preserve missing facts, and stop at the written boundary.`},{title:'Daily handoff',text:`Report ready items, waiting items, stopped exceptions, and decisions needed. Include the source, owner, next action, and time zone.`}],
      scenario:{title:`A controlled first week for a ${b.role}`,intro:'Use a small, mixed batch to test the instructions, source trail, communication, and review rhythm.',steps:[{step:'1',title:'Confirm the unit',body:`Choose one unit from ${b.tasks}.`},{step:'2',title:'Confirm access',body:`Grant only the required view in ${b.tools}.`},{step:'3',title:'Run four cases',body:'Include ordinary, incomplete, conflicting, and boundary cases.'},{step:'4',title:'Review evidence',body:'Check the source and decision trail, not only the finished wording.'},{step:'5',title:'Repair one rule',body:'Update the example or stop rule before increasing volume.'}]},
      faqs:[{question:`What should a ${b.role} do first?`,answer:`Begin with one documented lane such as ${b.tasks}. Keep the batch small enough for daily review.`},{question:'What should remain with the owner?',answer:`Keep ${b.keep} with the accountable owner or qualified professional.`},{question:'Can this role perform local, in-person work?',answer:'No. Hire Assistant Near Me offers assistants recruited and hired in the Philippines for remote work.'},{question:'How should access begin?',answer:`Use a named account with only the permissions required in ${b.tools}, then review access when duties change.`},{question:'How should the first month be judged?',answer:`Review ${b.metric}. Define each measure before work begins.`}],
      relatedLinks:[{href:'/services',label:'Compare remote assistant service lanes'},{href:'/compare/local-vs-remote-assistant',label:'Compare local and remote task fit'},{href:'/blog/virtual-assistant-security-checklist',label:'Plan account and access safeguards'},{href:'/contact-us',label:'Build a Philippines-based role brief'}],
      sources:officialSources,
    }
  };
});
