const published = '2026-09-11';

const briefs = [
  ['letterpress-studio-proof-queue-assistant','Run a proof queue for a small letterpress studio','letterpress proof assistant','Assemble copy and production notes while the printer keeps design, price, production, and delivery decisions.','/images/aug20-blog-inbox-triage.png','item ID, customer copy and stock request, customer wording, supplied photos, service history, drop-off date, and missing facts','the printer or shop owner','changing copy, recommending work, quoting a price, or promising completion'],
  ['independent-bookbinder-repair-intake-assistant','Prepare book-repair intake records without guaranteeing placement','bookbinding intake assistant','Create a source-linked intake record while the bookbinder keeps condition, treatment, value, and turnaround judgments.','/images/aug21-blog-content-briefs.png','order ID, intended use, requested size, supplied place names, source files, revision note, due-date request, and owner','the bookbinder','verifying condition claims, prescribing treatment, approving artwork, or promising delivery'],
  ['community-radio-guest-release-assistant','Track guest releases for a community radio program','radio release assistant','Maintain a complete guest-release register while the producer keeps consent interpretation, editorial, access, and broadcast decisions.','/images/aug20-blog-source-ledger.png','project ID, release version and signature status, riding goals in the customer words, component notes, photographs, open questions, and reviewer','the producer','interpreting measurements, making ingredient or health claims, selecting materials, or approving a build'],
  ['custom-kite-maker-order-assistant','Reconcile custom-kite orders without making safety promises','kite order assistant','Organize customer specifications and order evidence while the kite maker keeps design, material, safety, price, and delivery decisions.','/images/aug21-blog-interview-notes.png','job ID, model and colors requested, dimensions as supplied, photographs, known history, observed loose pieces in customer wording, and owner','the kite maker','approving a design, selecting treatment, valuing the object, or authorizing transport'],
  ['historical-map-dealer-catalog-assistant','Prepare catalog records for a historical map dealer','map catalog assistant','Assemble source-linked catalog fields while the map specialist keeps attribution, authenticity, condition, valuation, and sales claims.','/images/aug20-blog-listing-admin.png','loan ID, title as printed, inventory ID, checkout date, planned return, condition photos, stated use, and workshop owner','the map dealer or specialist','attributing an undated work, judging safety, allowing alteration, or assessing damage'],
  ['mobile-bicycle-repair-routing-assistant','Build a daily route sheet for a mobile bicycle-repair service','mobile repair routing assistant','Prepare a bounded route sheet while the mechanic keeps diagnosis, service, safety, price, and schedule commitments.','/images/aug20-blog-order-exceptions.png','request ID, member record, address and requested window, quantity, catalog status, collection date, stated purpose, and owner','the mechanic or dispatcher','diagnosing a fault, recommending a variety, making a substitution, or giving cultivation advice'],
  ['independent-pottery-class-waitlist-assistant','Maintain a pottery-class waitlist with clear stop rules','pottery class waitlist assistant','Keep enrollment facts current while the studio owner keeps placement, accessibility, refund, safety, and capacity decisions.','/images/calendar-assistant.jpg','booking ID, learner name and class ID, customer concern in their words, supplied photographs, requested window, delivery method, and reviewer','the studio owner or instructor','guaranteeing placement, specifying repair, selecting hair, or promising turnaround'],
  ['specialty-tea-club-shipment-assistant','Reconcile specialty tea-club shipment exceptions','tea club shipment assistant','Join order and carrier evidence in one queue while the merchant keeps substitution, suitability, refund, and customer-commitment decisions.','/images/aug20-blog-calendar-conflicts.png','request ID, order ID and subscription tier, age range as supplied, preferred dates, access needs, topic request, contact route, and owner','the tea merchant','substituting goods, operating equipment, approving access, or making a weather call'],
  ['independent-luthier-parts-register-assistant','Maintain a parts register for an independent luthier','luthier records assistant','Create a traceable parts record while the luthier keeps compatibility, condition, material, repair, and purchasing judgments.','/images/aug20-blog-reminder-queues.png','request ID, part number, quantity, measurements as listed, customer question, inventory timestamp, requested hold, and owner','the luthier','guaranteeing placement, confirming compatibility, changing price, or granting a hold'],
  ['neighborhood-museum-image-request-assistant','Triage image-use requests for a neighborhood museum','museum image request assistant','Prepare complete image-use request packets while museum staff keep rights, privacy, attribution, fee, and publication decisions.','/images/aug20-blog-order-exceptions.png','order ID, costume ID and performer identifier and intended use, payment-status label, packing record, carrier event, customer wording, exception, and owner','the collections or rights manager','clearing rights, discussing medical suitability, substituting a product, or authorizing a refund'],
  ['artisan-soap-workshop-wholesale-assistant','Prepare wholesale-order handoffs for an artisan soap workshop','soap wholesale assistant','Assemble buyer and order facts while the workshop owner keeps formulation, claims, pricing, credit, substitution, and fulfillment decisions.','/images/aug23-research-claim-provenance.png','account ID and SKU quantity, participant name, consent-form version, signature date, stated restrictions, file location, review date, and owner','the workshop owner','making ingredient or health claims, changing restrictions, releasing recordings, or deciding a redaction'],
  ['small-dance-company-costume-loan-assistant','Track costume loans for a small dance company','costume loan assistant','Maintain a reviewable costume custody record while production staff keep fit, alteration, safety, damage, and replacement decisions.','/images/aug20-research-record-provenance.png','costume ID and performer identifier, image filename, capture date, view label, scale presence, photographer, source folder, and reviewer','the wardrobe manager','judging fit or safety, prescribing treatment, approving handling, or changing the official condition record'],
] as const;

export const sep11BlogPosts = briefs.map((b, i) => {
  const [slug,title,mainKeyword,excerpt,image,fields,owner,stop] = b;
  const p = [
    `Give the ${mainKeyword} one bounded daily queue. The assistant assembles evidence from approved records; ${owner} makes decisions that affect the customer, object, schedule, or business.`,
    `For each item, record ${fields}. Keep the customer's wording when it carries uncertainty, and attach a source another reviewer can reopen.`,
    `The written stop rule matters: pause before ${stop}. Mark the unresolved question instead of turning a guess into a clean-looking record.`,
    `Set a daily cutoff with a named time zone. Requests received later remain in the next queue unless ${owner} records a different priority.`,
    `Grant access only to the queue and folders required for this task. Account recovery, deletion, payments, permission changes, and unrestricted exports stay with the owner.`,
    `Train on three cases: an ordinary request, an incomplete request, and one that reaches the stop rule. Corrections should point to the exact field or source that was misunderstood.`,
    `Review complete handoffs, returned records, open exceptions, and owner review time after the first week. Expand only if the evidence trail and escalation path still hold up during routine work.`
  ];
  return {slug,mainKeyword,title,excerpt,published,richPublished:true,minutes:8+(i%3),image,imageAlt:`Assistant preparing a ${mainKeyword} handoff`,sourceBody:`Publication date: September 11, 2026.\n\n${p.join('\n\n')}`,takeaways:['Use one source-linked daily queue.',`Keep decisions with ${owner}.`,`Stop before ${stop}.`],detail:{revision:`${published}-${slug}-r1`,directAnswer:p.slice(0,2),bodyLinks:[{href:'/services',label:'assistant services'},{href:'/research',label:'research library'}],sections:['Define the work unit','Keep the source trail','Write the stop rule','Name the daily cutoff','Limit account access','Train with real exceptions','Review before expanding'].map((heading,n)=>({heading,paragraphs:[p[n],p[(n+1)%p.length]]})),decisionRows:[{need:'Record preparation',fit:'Remote assistant',reason:'Uses approved inputs to prepare a reviewable record.'},{need:'Judgment or commitment',fit:'Named owner',reason:`Remains with ${owner}.`},{need:'Missing or conflicting fact',fit:'Exception route',reason:'Preserves uncertainty for review.'}],planningNumbers:[{value:'1 queue',label:'Starting scope',note:mainKeyword},{value:'3 cases',label:'Training set',note:'Ordinary, incomplete, and stopped.'},{value:'1 owner',label:'Decision path',note:owner},{value:'Sep 11',label:'Publication date',note:'September 11, 2026.'}],scripts:[{title:'Daily assignment',text:`Prepare today's ${mainKeyword} queue from approved records. Record ${fields}.`},{title:'Exception note',text:`I stopped because this request may require ${stop}. The checked source and open question are linked.`}],scenario:{title:`First-week ${mainKeyword} review`,intro:'Use a small representative set.',steps:[{step:'1',title:'Confirm sources',body:'Name the approved records and cutoff.'},{step:'2',title:'Prepare the record',body:`Record ${fields}.`},{step:'3',title:'Hold uncertainty',body:'Leave missing or conflicting facts visible.'},{step:'4',title:'Escalate',body:`Send judgment to ${owner}.`},{step:'5',title:'Repair the instruction',body:'Turn a correction into a precise example.'}]},faqs:[{question:'Can the assistant make the final decision?',answer:`No. That remains with ${owner}.`},{question:'What if a source is incomplete?',answer:'Record the gap and ask a bounded question with the source attached.'},{question:'When should access expand?',answer:'Only after reviewed work and a separate permission decision.'}],relatedLinks:[{href:'/services',label:'Review assistant service lanes'},{href:'/research',label:'Browse the research library'}],sources:[{name:'NIST Cybersecurity Framework 2.0 Small Business Quick-Start Guide',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-20-small-business-quick-start-guide',note:'Access and risk-management context.'},{name:'FTC, Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business',note:'Business information-handling context.'}]}};
});
