const published = '2026-09-10';

const briefs = [
  ['clock-repair-shop-estimate-intake-assistant-routine','Prepare clock-repair estimates without diagnosing the movement','clock repair intake assistant','Build a complete intake record while the horologist keeps diagnosis, treatment, price, and completion-date decisions.','/images/aug20-blog-inbox-triage.png','item ID, clock type as described, customer wording, supplied photos, service history, drop-off date, and missing facts','the horologist or shop owner','identifying the fault, recommending work, quoting a price, or promising completion'],
  ['independent-mapmaker-custom-order-assistant-routine','Keep custom map orders clear for an independent cartographer','cartography order assistant','Turn customer files and revision notes into a traceable order packet without making geographic or design judgments.','/images/aug21-blog-content-briefs.png','order ID, intended use, requested size, supplied place names, source files, revision note, due-date request, and owner','the cartographer','verifying geographic claims, choosing a projection, approving artwork, or promising delivery'],
  ['bicycle-frame-builder-fit-note-assistant-routine','Organize bicycle frame-builder fit notes without giving fit advice','frame builder admin assistant','Prepare a source-linked customer packet while the builder retains fit, geometry, material, and safety decisions.','/images/aug20-blog-source-ledger.png','project ID, measurements exactly as supplied, riding goals in the customer words, component notes, photographs, open questions, and reviewer','the frame builder','interpreting measurements, prescribing geometry, selecting materials, or approving a build'],
  ['stained-glass-studio-repair-intake-assistant-routine','A repair-intake routine for a stained-glass studio','stained glass admin assistant','Record condition and customer requests consistently while the craftsperson decides treatment, handling, and price.','/images/aug21-blog-interview-notes.png','job ID, object description, dimensions as supplied, photographs, known history, observed loose pieces in customer wording, and owner','the stained-glass craftsperson','assessing structural condition, selecting treatment, valuing the object, or authorizing transport'],
  ['independent-theater-prop-loan-assistant-routine','Track prop loans for an independent theater workshop','theater prop admin assistant','Maintain a reviewable loan record while production staff retain suitability, safety, alteration, and damage decisions.','/images/aug20-blog-listing-admin.png','loan ID, production, item ID, checkout date, planned return, condition photos, stated use, and workshop owner','the props master or workshop manager','approving use, judging safety, allowing alteration, or assessing damage'],
  ['specialty-seed-library-request-assistant-routine','Triage requests for a specialty seed library','seed library admin assistant','Organize member requests and inventory facts while qualified staff control availability, substitutions, and growing advice.','/images/aug20-blog-order-exceptions.png','request ID, member record, variety requested, quantity, catalog status, collection date, stated purpose, and owner','the seed librarian or program manager','confirming viability, recommending a variety, making a substitution, or giving cultivation advice'],
  ['violin-bow-rehair-booking-assistant-routine','Prepare violin-bow rehair bookings without making condition claims','bow workshop booking assistant','Collect booking and handling facts while the archetier retains condition, repair, material, and turnaround decisions.','/images/calendar-assistant.jpg','booking ID, bow description, customer concern in their words, supplied photographs, requested window, delivery method, and reviewer','the archetier or workshop owner','assessing condition, specifying repair, selecting hair, or promising turnaround'],
  ['small-observatory-visit-request-assistant-routine','Sort visit requests for a small observatory','observatory visit assistant','Prepare group and accessibility details while observatory staff keep weather, equipment, safety, and program decisions.','/images/aug20-blog-calendar-conflicts.png','request ID, group size, age range as supplied, preferred dates, access needs, topic request, contact route, and owner','the observatory coordinator','confirming viewing conditions, operating equipment, approving access, or making a weather call'],
  ['architectural-salvage-hold-request-assistant-routine','Run a hold-request queue for an architectural salvage yard','salvage inventory assistant','Keep item and customer facts together while yard staff retain condition, compatibility, price, and reservation authority.','/images/aug20-blog-reminder-queues.png','request ID, item number, quantity, measurements as listed, customer question, inventory timestamp, requested hold, and owner','the yard manager','assessing condition, confirming compatibility, changing price, or granting a hold'],
  ['independent-perfumer-sample-order-assistant-routine','Reconcile sample orders for an independent perfumer','perfume order admin assistant','Track order and shipping evidence while the perfumer retains formulation, suitability, substitution, and refund decisions.','/images/aug20-blog-order-exceptions.png','order ID, sample SKUs, payment-status label, packing record, carrier event, customer wording, exception, and owner','the perfumer or shop owner','recommending a scent, discussing medical suitability, substituting a product, or authorizing a refund'],
  ['oral-history-archive-consent-record-assistant-routine','Maintain consent records for a community oral-history archive','oral history archive assistant','Prepare an auditable consent register while the archive owner retains interpretation, access, redaction, and publication decisions.','/images/aug23-research-claim-provenance.png','interview ID, participant name, consent-form version, signature date, stated restrictions, file location, review date, and owner','the archivist or project director','interpreting consent, changing restrictions, releasing recordings, or deciding a redaction'],
  ['ceramics-conservation-photo-index-assistant-routine','Index conservation photographs without making treatment claims','conservation records assistant','Create a reliable photo register while the conservator retains condition assessment, treatment, and handling decisions.','/images/aug20-research-record-provenance.png','object ID, image filename, capture date, view label, scale presence, photographer, source folder, and reviewer','the objects conservator','diagnosing deterioration, prescribing treatment, approving handling, or changing the official condition record'],
] as const;

export const sep10BlogPosts = briefs.map((b, i) => {
  const [slug,title,mainKeyword,excerpt,image,fields,owner,stop] = b;
  const p = [
    `Give the ${mainKeyword} one bounded daily queue. The assistant assembles evidence from approved records; ${owner} makes decisions that affect the customer, object, schedule, or business.`,
    `For each item, record ${fields}. Keep the customer's wording when it carries uncertainty, and attach a source another reviewer can reopen.`,
    `The written stop rule matters: pause before ${stop}. Mark the unresolved question instead of turning a guess into a clean-looking record.`,
    `Set a daily cutoff with a named time zone. Requests received later remain in the next queue unless ${owner} records a different priority.`,
    `Grant access only to the queue and folders required for this task. Account recovery, deletion, payments, permission changes, and unrestricted exports stay with the owner.`,
    `Train on three cases: an ordinary request, an incomplete request, and one that reaches the stop rule. Corrections should point to the exact field or source that was misunderstood.`,
    `Review complete handoffs, returned records, open exceptions, and owner review time after the first week. Expand only if the evidence trail and escalation path still hold up during routine work.`
  ];
  return {slug,mainKeyword,title,excerpt,published,richPublished:true,minutes:8+(i%3),image,imageAlt:`Assistant preparing a ${mainKeyword} handoff`,sourceBody:`Publication date: September 10, 2026.\n\n${p.join('\n\n')}`,takeaways:['Use one source-linked daily queue.',`Keep decisions with ${owner}.`,`Stop before ${stop}.`],detail:{revision:`${published}-${slug}-r1`,directAnswer:p.slice(0,2),bodyLinks:[{href:'/services',label:'assistant services'},{href:'/research',label:'research library'}],sections:['Define the work unit','Keep the source trail','Write the stop rule','Name the daily cutoff','Limit account access','Train with real exceptions','Review before expanding'].map((heading,n)=>({heading,paragraphs:[p[n],p[(n+1)%p.length]]})),decisionRows:[{need:'Record preparation',fit:'Remote assistant',reason:'Uses approved inputs to prepare a reviewable record.'},{need:'Judgment or commitment',fit:'Named owner',reason:`Remains with ${owner}.`},{need:'Missing or conflicting fact',fit:'Exception route',reason:'Preserves uncertainty for review.'}],planningNumbers:[{value:'1 queue',label:'Starting scope',note:mainKeyword},{value:'3 cases',label:'Training set',note:'Ordinary, incomplete, and stopped.'},{value:'1 owner',label:'Decision path',note:owner},{value:'Sep 10',label:'Publication date',note:'September 10, 2026.'}],scripts:[{title:'Daily assignment',text:`Prepare today's ${mainKeyword} queue from approved records. Record ${fields}.`},{title:'Exception note',text:`I stopped because this request may require ${stop}. The checked source and open question are linked.`}],scenario:{title:`First-week ${mainKeyword} review`,intro:'Use a small representative set.',steps:[{step:'1',title:'Confirm sources',body:'Name the approved records and cutoff.'},{step:'2',title:'Prepare the record',body:`Record ${fields}.`},{step:'3',title:'Hold uncertainty',body:'Leave missing or conflicting facts visible.'},{step:'4',title:'Escalate',body:`Send judgment to ${owner}.`},{step:'5',title:'Repair the instruction',body:'Turn a correction into a precise example.'}]},faqs:[{question:'Can the assistant make the final decision?',answer:`No. That remains with ${owner}.`},{question:'What if a source is incomplete?',answer:'Record the gap and ask a bounded question with the source attached.'},{question:'When should access expand?',answer:'Only after reviewed work and a separate permission decision.'}],relatedLinks:[{href:'/services',label:'Review assistant service lanes'},{href:'/research',label:'Browse the research library'}],sources:[{name:'NIST Cybersecurity Framework 2.0 Small Business Quick-Start Guide',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-20-small-business-quick-start-guide',note:'Access and risk-management context.'},{name:'FTC, Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business',note:'Business information-handling context.'}]}};
});
