type Brief = {
  slug: string; title: string; keyword: string; excerpt: string; lane: string;
  result: string; stop: string; intake: string; check: string; cadence: string;
};

const published = '2026-09-01' as const;
const briefs: Brief[] = [
  { slug:'daily-priority-brief-before-the-owner-logs-in', title:'Build a daily priority brief before the owner logs in', keyword:'daily priority brief remote assistant', excerpt:'Turn overnight messages, deadlines, and blocked work into one short decision brief without deciding the owner’s priorities.', lane:'daily priority briefing', result:'a ranked draft brief with evidence links', stop:'choosing business priorities or promising a response', intake:'the approved inbox labels, calendar, and open-work register', check:'whether every priority has a source, deadline, owner, and requested decision', cadence:'at the end of the assistant’s agreed morning review window' },
  { slug:'daily-content-brief-intake-routine', title:'A daily content brief intake routine for a remote assistant', keyword:'daily content brief routine', excerpt:'Convert scattered topic requests into complete editorial inputs while keeping claims and publication choices with the editor.', lane:'content brief intake', result:'a ready, incomplete, or escalated brief queue', stop:'selecting claims, approving sources, or publishing', intake:'approved topic requests, audience notes, and editorial templates', check:'whether the audience, question, format, deadline, and reviewer are explicit', cadence:'before the daily editorial planning meeting' },
  { slug:'source-link-health-check-before-publishing', title:'Check source links before publishing without rewriting the evidence', keyword:'source link check publishing assistant', excerpt:'Use a bounded prepublication pass to catch broken, redirected, or mismatched citations and return evidence questions to the editor.', lane:'source-link verification', result:'a citation status ledger', stop:'replacing evidence or deciding that a claim remains supported', intake:'the draft citation list and approved source copies', check:'the response status, destination title, publication context, and claim-to-source match', cadence:'after copy edit and before final editorial approval' },
  { slug:'daily-blog-production-board-that-shows-real-status', title:'Run a daily blog production board that shows real status', keyword:'daily blog production board', excerpt:'Define production states that distinguish drafting, evidence review, approval, and publication instead of treating every card as nearly done.', lane:'blog production tracking', result:'an auditable board with one next owner per article', stop:'approving copy or moving work past an unmet gate', intake:'the editorial calendar, draft links, review notes, and publishing checklist', check:'whether the displayed state matches the latest completed gate', cadence:'at each scheduled handoff, not continuously' },
  { slug:'research-question-triage-for-a-daily-publishing-team', title:'Triage research questions for a daily publishing team', keyword:'research question triage routine', excerpt:'Sort research requests by answerability, evidence needs, and decision owner before anyone starts collecting links.', lane:'research question triage', result:'a scoped question queue with acceptance tests', stop:'answering ambiguous questions or choosing a commercial conclusion', intake:'editor questions, audience needs, and the approved research scope', check:'whether each question names its population, period, terms, output, and reviewer', cadence:'once before research begins and again only when scope changes' },
  { slug:'editorial-fact-check-handoff-without-silent-edits', title:'Create an editorial fact-check handoff without silent edits', keyword:'editorial fact check handoff', excerpt:'Record claim checks, conflicts, and corrections so writers can see what changed and editors retain final authority.', lane:'fact-check handoff', result:'a claim-by-claim verification note', stop:'silently rewriting meaning or approving disputed language', intake:'the frozen review draft, source register, and style rules', check:'whether each factual claim has a status, citation, note, and named resolver', cadence:'after substantive editing and before publication approval' },
  { slug:'daily-refresh-watchlist-for-evergreen-articles', title:'Keep a daily refresh watchlist for evergreen articles', keyword:'evergreen article refresh watchlist', excerpt:'Monitor dated claims and fragile links without turning every source change into an unreviewed article update.', lane:'evergreen refresh monitoring', result:'a dated review watchlist', stop:'changing live claims, dates, or recommendations', intake:'the approved evergreen inventory and claim-expiry rules', check:'whether the trigger affects a cited fact, a reader instruction, or only page formatting', cadence:'during one bounded daily monitoring pass' },
  { slug:'publication-checklist-for-canonical-date-and-index', title:'Use a publication checklist for canonical, date, and index integrity', keyword:'article publication checklist canonical date', excerpt:'Give a remote assistant a repeatable release check for URL identity, visible dates, structured data, indexes, and sitemap entries.', lane:'publication integrity review', result:'a route-level pass or exception record', stop:'inventing redirects, changing legacy URLs, or bypassing a failed check', intake:'the approved manifest, built site, and expected canonical routes', check:'HTTP status, self-canonical, visible date, JSON-LD date, index link, and sitemap link', cadence:'after the production build and before deployment approval' },
  { slug:'duplicate-content-preflight-for-daily-articles', title:'Run a duplicate-content preflight for daily articles', keyword:'duplicate content preflight articles', excerpt:'Compare titles, slugs, canonicals, and normalized bodies before release while preserving distinct editorial intent.', lane:'duplicate-content preflight', result:'a collision report with content hashes', stop:'merging articles or assigning a shared canonical', intake:'the new manifest and the existing content inventory', check:'exact identifiers, normalized body hashes, repeated openings, and overlapping reader questions', cadence:'before the batch is committed for deployment' },
  { slug:'daily-editorial-exception-queue-that-gets-answered', title:'Build a daily editorial exception queue that gets answered', keyword:'editorial exception queue routine', excerpt:'Route missing evidence, unclear ownership, and failed release checks to a named decision window instead of hiding them in comments.', lane:'editorial exception routing', result:'a small queue with decision-ready context', stop:'resolving policy, evidence, legal, or publication questions', intake:'failed checklist items and reviewer comments from approved systems', check:'whether every exception states impact, evidence, owner, deadline, and safe next step', cadence:'at a fixed editor review window each publishing day' },
  { slug:'end-of-day-publishing-reconciliation-routine', title:'Reconcile the publishing day before the team signs off', keyword:'end of day publishing reconciliation', excerpt:'Match the approved manifest to live-ready routes and carry unresolved work forward without falsely reporting publication.', lane:'end-of-day publishing reconciliation', result:'a signed-off manifest and carryover list', stop:'claiming a route is live without evidence or deploying it', intake:'the approved daily manifest, build output, and release-check results', check:'whether every planned item is passed, explicitly held, or assigned for correction', cadence:'after final checks and before the daily handoff' },
  { slug:'daily-research-log-for-claims-sources-and-decisions', title:'Maintain a daily research log for claims, sources, and decisions', keyword:'daily research log assistant', excerpt:'Preserve the path from question to source note to editor decision so tomorrow’s work does not restart from memory.', lane:'research log maintenance', result:'a dated evidence and decision ledger', stop:'interpreting specialist evidence or marking an unresolved claim verified', intake:'approved questions, source notes, claim checks, and editor decisions', check:'whether each entry separates source fact, researcher note, limitation, and final decision', cadence:'at every material research handoff' }
];

const sources = [
  { name:'HireAssistantNearMe services', url:'https://hireassistantnearme.com/services', note:'Role-scope and managed staffing context.' },
  { name:'HireAssistantNearMe research library', url:'https://hireassistantnearme.com/research', note:'Evidence-handling and workflow research.' }
];

const paragraphs = (b: Brief) => [
  `${b.title} works best as a narrow operating lane. The assistant begins with ${b.intake} and prepares ${b.result}. The assignment has a visible finish and does not transfer authority for ${b.stop}. That separation matters in a daily publishing routine because a polished board or document can look complete while an evidence, approval, or release decision is still open.`,
  `Write the intake rule before the work starts. For ${b.lane}, name the approved systems, fields, cutoff, output location, and reviewer. The assistant should record missing inputs rather than reconstruct them from memory or search beyond the permitted workspace. An item that arrives after the cutoff belongs to the next pass unless the role brief contains a specific escalation rule.`,
  `The central quality check is ${b.check}. Record the result beside the item, with a link to the evidence a reviewer can open. A checkbox without the inspected value is weak evidence. When two records disagree, preserve the conflict and ask a focused question; do not quietly select the version that makes the queue easier to close.`,
  `Use three training examples: one ordinary case, one incomplete case, and one case that reaches the stop rule. The reviewer explains why each state is correct and returns corrections against the written instruction. This creates a fair daily routine for a Philippines-based remote assistant without assuming constant coverage or independent editorial judgment.`,
  `Run the lane ${b.cadence}. The handoff should state the time zone, last item inspected, completed count, exception count, and next named owner. Counts describe flow, not accuracy or business impact. A reviewer should sample ordinary passes as well as failures because a clean exception queue can still hide incorrect approvals.`,
  `Keep permissions proportional to preparation. Read or draft access may be sufficient even when the surrounding system supports publication, deletion, account administration, or customer communication. Use named accounts and preserve history. Any new system, data class, communication channel, or final-action permission belongs in a separately reviewed scope change.`,
  `Improve the routine from returned work. Group corrections by missing input, unclear example, access problem, unsupported assumption, or owner delay. Change one instruction at a time and inspect the next sample. The goal is not to eliminate every exception; it is to make ordinary work finishable and consequential uncertainty visible to the person who can decide it.`
];

export const sep1BlogPosts = briefs.map((b) => {
  const copy = paragraphs(b);
  return {
    slug:b.slug, mainKeyword:b.keyword, title:b.title, excerpt:b.excerpt, published, richPublished:true, minutes:9,
    sourceBody:`Publication date: September 1, 2026.\n\n${copy.join('\n\n')}`,
    takeaways:[`Define ${b.lane} as one finishable lane.`,`Require ${b.result} at handoff.`,`Check ${b.check}.`,`Stop before ${b.stop}.`],
    detail:{ revision:`${published}-${b.slug}-r1`, directAnswer:[copy[0],copy[1]], bodyLinks:[{href:'/services',label:'assistant services'},{href:'/research',label:'research library'}], sections:[
      {heading:'Set the lane and finish line',paragraphs:[copy[0],copy[1]]},{heading:'Inspect the evidence',paragraphs:[copy[2],copy[3]]},{heading:'Make the handoff observable',paragraphs:[copy[4],copy[2]]},{heading:'Limit access to the task',paragraphs:[copy[5],copy[1]]},{heading:'Review exceptions without guessing',paragraphs:[copy[3],copy[6]]},{heading:'Improve one rule at a time',paragraphs:[copy[6],copy[4]]},{heading:'Close the daily routine',paragraphs:[copy[4],copy[5]]}
    ], decisionRows:[{need:b.lane,fit:'Remote preparation lane',reason:`Produces ${b.result} from approved inputs.`},{need:b.stop,fit:'Named owner',reason:'Requires accountable authority.'},{need:'Missing or conflicting input',fit:'Exception queue',reason:'Preserve the gap for review.'},{need:'New access or final action',fit:'Separate scope',reason:'Review permission before expansion.'}], planningNumbers:[{value:'1 lane',label:'Starting scope',note:b.lane},{value:'3 cases',label:'Training sample',note:'Ordinary, incomplete, and escalated.'},{value:'1 owner',label:'Decision path',note:'Name the reviewer.'},{value:'Sep 1',label:'Publication date',note:'September 1, 2026.'}], scripts:[{title:'Assignment',text:`Prepare ${b.result} from ${b.intake}. Stop before ${b.stop}.`},{title:'Handoff',text:`I checked ${b.check}. Open exceptions name the evidence and next owner.`}], scenario:{title:`Pilot ${b.lane}`,intro:'Use a representative sample before widening the lane.',steps:[{step:'1',title:'Accept',body:'Confirm the approved input and cutoff.'},{step:'2',title:'Prepare',body:`Create ${b.result}.`},{step:'3',title:'Check',body:`Inspect ${b.check}.`},{step:'4',title:'Escalate',body:`Stop before ${b.stop}.`},{step:'5',title:'Review',body:'Record one specific correction before the next pass.'}]}, faqs:[{question:`What is the output of ${b.lane}?`,answer:`The output is ${b.result}.`},{question:'What remains with the owner?',answer:`The owner retains ${b.stop} and final publication authority.`},{question:'How should missing information be handled?',answer:'Record the gap, source, impact, and named decision owner.'},{question:'Does this require continuous coverage?',answer:`No. Run it ${b.cadence}, within agreed working hours.`},{question:'When should access expand?',answer:'Only after a reviewed sample and a separate permission decision.'}], relatedLinks:[{href:'/services',label:'Review assistant service lanes'},{href:'/research',label:'Browse the research library'},{href:'/contact-us',label:'Discuss a bounded role'}], sources }
  };
});
