type Brief = { slug:string; title:string; keyword:string; excerpt:string; lane:string; output:string; input:string; boundary:string; check:string; rhythm:string };

const published = '2026-09-02' as const;
const briefs: Brief[] = [
  {slug:'morning-editorial-inbox-sort-for-daily-publishing',title:'Sort the editorial inbox before daily publishing begins',keyword:'editorial inbox sorting routine',excerpt:'Turn overnight editorial messages into a reviewable queue without answering evidence or publication questions for the editor.',lane:'editorial inbox sorting',output:'a labeled queue with one requested next action',input:'approved editorial inboxes and the current production board',boundary:'answering a source dispute or approving publication',check:'sender, article, deadline, requested action, and decision owner',rhythm:'once before the morning editorial handoff'},
  {slug:'assign-one-review-owner-to-every-daily-article',title:'Assign one review owner to every daily article',keyword:'daily article review owner',excerpt:'Prevent ambiguous approvals by recording who owns evidence, copy, and release decisions at each article gate.',lane:'review ownership',output:'an owner map for every open article',input:'the approved manifest and reviewer schedule',boundary:'substituting an available person for the accountable reviewer',check:'each gate has one named owner and a response window',rhythm:'when the manifest is opened and whenever ownership changes'},
  {slug:'prepare-a-writer-handoff-from-an-approved-research-note',title:'Prepare a writer handoff from an approved research note',keyword:'research to writer handoff',excerpt:'Package an approved question, evidence record, and limitations for drafting while preserving the researcher’s uncertainty.',lane:'research-to-writer handoff',output:'a linked writing packet with explicit limitations',input:'the approved question, claim ledger, and source notes',boundary:'turning a limitation into a stronger claim',check:'question, audience, supported claims, exclusions, citations, and reviewer',rhythm:'after research approval and before drafting starts'},
  {slug:'track-draft-versions-without-losing-editor-decisions',title:'Track draft versions without losing editor decisions',keyword:'editorial draft version control',excerpt:'Keep daily article revisions connected to review notes so a later draft does not silently restore rejected wording.',lane:'draft version tracking',output:'a dated version log with decisions attached',input:'approved draft storage and reviewer comments',boundary:'accepting or rejecting substantive edits',check:'version, author, change reason, decision, and current review state',rhythm:'at each substantive handoff'},
  {slug:'run-a-prepublication-title-and-slug-collision-check',title:'Run a prepublication title and slug collision check',keyword:'title slug collision check',excerpt:'Compare new article identities with the full content inventory before routes are built or indexed.',lane:'article identity preflight',output:'a collision report covering titles, slugs, and canonicals',input:'the new manifest and existing article inventory',boundary:'renaming approved work without editor confirmation',check:'exact and normalized title, slug, route, and canonical matches',rhythm:'after titles are approved and before the production build'},
  {slug:'record-source-access-dates-in-a-daily-claim-ledger',title:'Record source access dates in a daily claim ledger',keyword:'source access date claim ledger',excerpt:'Preserve when evidence was inspected and what version supported a claim without implying the source remains unchanged.',lane:'source access logging',output:'a dated claim-to-source record',input:'approved citations and captured source context',boundary:'claiming a source is current beyond the inspection date',check:'claim, source location, access date, relevant passage, and limitation',rhythm:'when a source first supports a claim and when it is rechecked'},
  {slug:'separate-copy-edits-from-factual-corrections',title:'Separate copy edits from factual corrections',keyword:'copy edit factual correction workflow',excerpt:'Route style changes and evidence changes through different review paths so factual meaning is never altered silently.',lane:'edit classification',output:'a change log labeled style, clarity, fact, or scope',input:'the frozen draft, style guide, and claim ledger',boundary:'approving a factual correction from copy context alone',check:'whether meaning, number, attribution, scope, or conclusion changed',rhythm:'during copy edit and again before final approval'},
  {slug:'prepare-alt-text-review-using-approved-site-assets',title:'Prepare alt-text review using approved site assets',keyword:'article alt text review routine',excerpt:'Check that an existing approved image and its text alternative fit the article without creating or sourcing new artwork.',lane:'approved-asset accessibility review',output:'an asset reference and concise alt-text draft',input:'the approved site asset library and article context',boundary:'adding new assets or making final accessibility approval',check:'asset path, intended meaning, surrounding caption, redundancy, and reviewer',rhythm:'before the article enters release review'},
  {slug:'hold-late-breaking-edits-behind-a-release-gate',title:'Hold late-breaking edits behind a release gate',keyword:'late breaking edit release gate',excerpt:'Keep last-minute changes visible and reviewable instead of letting urgency bypass evidence and build checks.',lane:'late-edit control',output:'a release exception with changed text and affected checks',input:'the approved release candidate and incoming change request',boundary:'merging or publishing an unapproved late change',check:'requester, reason, changed claims, reviewer, build impact, and deadline',rhythm:'whenever a change arrives after the release candidate is frozen'},
  {slug:'verify-index-links-against-the-approved-daily-manifest',title:'Verify index links against the approved daily manifest',keyword:'daily article index link verification',excerpt:'Match blog and research landing pages to the release manifest so every new canonical route is discoverable in the right library.',lane:'index coverage verification',output:'a manifest-to-index comparison with exceptions',input:'the approved manifest and built blog and research indexes',boundary:'moving an article between content types or inventing an alias',check:'content type, title, href, canonical destination, and response',rhythm:'after the production build and before release sign-off'},
  {slug:'write-an-end-of-shift-editorial-continuity-note',title:'Write an end-of-shift editorial continuity note',keyword:'editorial shift handoff note',excerpt:'Give the next work window enough evidence to continue daily publishing without guessing what “almost done” means.',lane:'editorial continuity handoff',output:'a dated note with last verified state and next owner',input:'the production board, claim ledger, and check results',boundary:'reporting an unverified gate as complete',check:'artifact, completed gate, open question, next action, owner, and time zone',rhythm:'at the agreed end of each editorial work window'},
  {slug:'audit-the-live-ready-manifest-before-deployment-handoff',title:'Audit the live-ready manifest before deployment handoff',keyword:'deployment handoff article manifest audit',excerpt:'Reconcile source records, build routes, metadata, indexes, and sitemap entries without deploying the site.',lane:'deployment manifest audit',output:'a passed manifest or a precise hold list',input:'the approved batch, production build, and route evidence',boundary:'deploying, changing infrastructure, or waiving a failed control',check:'unique identity, body hash, 200 response, self-canonical, date, index, and sitemap',rhythm:'once after all scoped fixes pass the production build'}
];

const sources = [{name:'HireAssistantNearMe research library',url:'https://hireassistantnearme.com/research',note:'Workflow evidence and control context.'},{name:'HireAssistantNearMe services',url:'https://hireassistantnearme.com/services',note:'Bounded assistant role context.'}];

export const sep2BlogPosts = briefs.map((b, index) => {
  const p = [
    `${b.title} is a bounded support routine, not a transfer of editorial authority. Start with ${b.input} and finish with ${b.output}. The assistant stops before ${b.boundary}. This makes the status useful to a daily publishing team because the next reviewer can inspect an artifact instead of relying on a broad progress label.`,
    `Write the lane as an observable instruction. For ${b.lane}, identify the source systems, cutoff, output location, acceptable example, and named reviewer. Record missing context as an exception. Do not rebuild absent information from memory or widen the search beyond the approved workspace merely to close the queue.`,
    `The required check is ${b.check}. Store the inspected value or link beside the result. When two records disagree, keep both values and route the conflict to the person who owns the decision. A clean checkbox is not evidence when another reviewer cannot reproduce what was inspected.`,
    `Use an ordinary item, an incomplete item, and an authority-boundary item for training. Correct the written rule after reviewing those examples. This keeps the routine fair for a Philippines-based remote assistant and avoids assuming continuous availability, specialist judgment, or permission to publish.`,
    `Run this routine ${b.rhythm}. Each handoff states the time zone, last record inspected, completed count, exceptions, and next owner. Counts describe flow only. Review a sample of passes as well as failures, since incorrect approvals may otherwise disappear from an empty exception queue.`,
    `Limit access to what ${b.lane} needs. Prefer named accounts, read access, drafts, and preserved history. Publishing, deletion, payments, account recovery, sensitive disclosures, and new data sources require their own approval. A role expansion should be explicit rather than inferred from a successful batch.`,
    `Improve the process from returned work. Classify corrections as missing input, unclear example, access problem, unsupported assumption, or owner delay. Change one rule, test the next representative sample, and retain the before-and-after record. The goal is a dependable daily routine that exposes consequential uncertainty to the accountable editor.`
  ];
  return {slug:b.slug,mainKeyword:b.keyword,title:b.title,excerpt:b.excerpt,published,richPublished:true,minutes:8 + (index % 3),sourceBody:`Publication date: September 2, 2026.\n\n${p.join('\n\n')}`,takeaways:[`Define ${b.lane} as one reviewable lane.`,`Require ${b.output}.`,`Check ${b.check}.`,`Stop before ${b.boundary}.`],detail:{revision:`${published}-${b.slug}-r1`,directAnswer:[p[0],p[1]],bodyLinks:[{href:'/services',label:'assistant services'},{href:'/research',label:'research library'}],sections:[{heading:'Define the finish line',paragraphs:[p[0],p[1]]},{heading:'Make evidence reproducible',paragraphs:[p[2],p[3]]},{heading:'Use a dated handoff',paragraphs:[p[4],p[2]]},{heading:'Keep permissions narrow',paragraphs:[p[5],p[1]]},{heading:'Route exceptions clearly',paragraphs:[p[3],p[6]]},{heading:'Repair the written rule',paragraphs:[p[6],p[4]]},{heading:'Close the routine',paragraphs:[p[4],p[5]]}],decisionRows:[{need:b.lane,fit:'Remote preparation',reason:`Produces ${b.output}.`},{need:b.boundary,fit:'Named owner',reason:'Requires accountable authority.'},{need:'Missing or conflicting input',fit:'Exception queue',reason:'Preserves uncertainty for review.'},{need:'New access or public action',fit:'Separate approval',reason:'Requires explicit permission.'}],planningNumbers:[{value:'1 lane',label:'Starting scope',note:b.lane},{value:'3 cases',label:'Training sample',note:'Ordinary, incomplete, and stopped.'},{value:'1 owner',label:'Decision path',note:'Name the accountable reviewer.'},{value:'Sep 2',label:'Publication date',note:'September 2, 2026.'}],scripts:[{title:'Assignment',text:`Prepare ${b.output} from ${b.input}. Stop before ${b.boundary}.`},{title:'Handoff',text:`I checked ${b.check}. Open exceptions name the evidence and next owner.`}],scenario:{title:`Pilot ${b.lane}`,intro:'Test a representative sample before widening the role.',steps:[{step:'1',title:'Accept',body:'Confirm input and cutoff.'},{step:'2',title:'Prepare',body:`Create ${b.output}.`},{step:'3',title:'Check',body:`Inspect ${b.check}.`},{step:'4',title:'Escalate',body:`Stop before ${b.boundary}.`},{step:'5',title:'Review',body:'Record one correction for the next pass.'}]},faqs:[{question:`What does ${b.lane} produce?`,answer:`It produces ${b.output}.`},{question:'What stays with the owner?',answer:`The owner retains ${b.boundary} and final publication authority.`},{question:'How are missing inputs handled?',answer:'Record the source, gap, impact, and named decision owner.'},{question:'Does the routine require continuous coverage?',answer:`No. Run it ${b.rhythm}, inside agreed hours.`},{question:'When should access expand?',answer:'Only after reviewed work and a separate permission decision.'}],relatedLinks:[{href:'/services',label:'Review assistant service lanes'},{href:'/research',label:'Browse the research library'},{href:'/contact-us',label:'Discuss a bounded role'}],sources}};
});
