const published = '2026-09-22';

type Brief = {
  slug: string; title: string; keyword: string; role: string; outcome: string;
  tasks: string; keep: string; tools: string; sample: string; metric: string;
};

const briefs: Brief[] = [
  {slug:'social-media-virtual-assistant-job-description',title:'Social media virtual assistant job description: scope, approvals, and scorecard',keyword:'social media virtual assistant job description',role:'social media assistant',outcome:'turn approved ideas and assets into a dependable publishing queue without giving away brand or crisis decisions',tasks:'formatting approved captions, scheduling posts, applying campaign tags, collecting routine comments, updating the content calendar, and preparing performance summaries',keep:'brand strategy, public apologies, crisis replies, legal claims, paid-budget changes, account recovery, and final approval of sensitive posts',tools:'limited social-platform roles, content calendar, approved asset library, review queue, and escalation channel',sample:'prepare one week of posts from an approved brief and flag every missing asset, unsupported claim, and sensitive reply',metric:'posts ready by cutoff, approval returns by reason, publishing errors, unanswered exceptions, and owner review time'},
  {slug:'virtual-assistant-for-marketing-agency-hiring-guide',title:'Virtual assistant for a marketing agency: hiring guide and task boundaries',keyword:'virtual assistant for marketing agency',role:'marketing agency assistant',outcome:'keep campaign administration and client handoffs organized while strategists retain recommendations and client commitments',tasks:'assembling status reports, checking asset receipt, maintaining campaign trackers, formatting approved briefs, scheduling internal reviews, and recording client feedback',keep:'strategy, budget allocation, performance promises, contract changes, creative approval, access administration, and client conflict resolution',tools:'project board, reporting dashboards with view access, shared drive, approved templates, and client-specific communication rules',sample:'build a source-linked weekly status packet for two fictional clients and separate completed work, blocked work, and decisions needed',metric:'reports delivered by cutoff, missing assets found, unsupported status changes, overdue decisions, and strategist review minutes'},
  {slug:'appointment-setting-virtual-assistant-small-business',title:'Appointment-setting virtual assistant for a small business: a practical role plan',keyword:'appointment setting virtual assistant small business',role:'appointment-setting assistant',outcome:'move eligible inquiries into the right calendar slots without making sales, pricing, or qualification promises',tasks:'contacting opted-in inquiries, using approved screening questions, offering permitted times, recording replies, sending confirmations, and maintaining a no-contact list',keep:'changing qualification rules, negotiating price, promising availability, overriding consent, handling complaints, and deciding urgent or sensitive exceptions',tools:'CRM, approved phone or email channel, scheduling page, call script, consent fields, and escalation queue',sample:'work a redacted inquiry list, schedule only records that satisfy the written rule, and document every stop reason',metric:'eligible records attempted, accurate appointments, no-contact requests honored, reschedules caused by admin errors, and exception age'},
  {slug:'project-coordinator-virtual-assistant-hiring-guide',title:'Project coordinator virtual assistant: hiring guide, workflow, and scorecard',keyword:'project coordinator virtual assistant',role:'project coordination assistant',outcome:'make owners, dates, dependencies, and missing inputs visible without transferring delivery authority',tasks:'updating approved task states, requesting status from named owners, preparing meeting agendas, recording decisions, maintaining dependency lists, and issuing routine reminders',keep:'committing scope, changing deadlines, assigning accountability, approving deliverables, evaluating staff, spending budget, and concealing missed work',tools:'project board, calendar, meeting notes, document workspace, written status definitions, and escalation channel',sample:'reconstruct a small project board from redacted notes and produce a handoff that distinguishes facts, assumptions, and decisions needed',metric:'tasks updated from evidence, stale items surfaced, missing owners, incorrect status changes, and manager review time'},
  {slug:'recruiting-virtual-assistant-job-description',title:'Recruiting virtual assistant job description: sourcing, scheduling, and boundaries',keyword:'recruiting virtual assistant job description',role:'recruiting assistant',outcome:'keep candidate administration timely and consistent while hiring judgments stay with accountable people',tasks:'posting approved role copy, organizing applications, checking objective requirements, scheduling interviews, sending approved updates, and maintaining candidate records',keep:'inventing screening criteria, making selection decisions, promising employment, negotiating compensation, collecting unnecessary sensitive data, and changing approved role terms',tools:'applicant tracking system with limited access, scheduling tool, approved templates, role scorecard, and recruiter escalation route',sample:'process a redacted candidate set against explicit minimum requirements and route every ambiguous case without guessing',metric:'applications processed by cutoff, scheduling accuracy, candidates awaiting response, correction reasons, and recruiter review time'},
  {slug:'podcast-virtual-assistant-hiring-guide',title:'Podcast virtual assistant hiring guide: production admin without editorial guesswork',keyword:'podcast virtual assistant hiring guide',role:'podcast production assistant',outcome:'move episodes from approved recording to release with assets, credits, links, and approvals intact',tasks:'organizing recordings, preparing transcript corrections, collecting guest details, formatting show notes, scheduling approved files, and maintaining the release checklist',keep:'editorial position, factual approval, music licensing decisions, guest disputes, public corrections, sponsorship promises, and final publication authority',tools:'media workspace, transcript editor, publishing platform with limited role, source ledger, asset checklist, and approval queue',sample:'prepare a fictional episode packet from recording notes and flag unclear names, claims, rights, links, and edit instructions',metric:'packets complete by cutoff, transcript corrections, missing rights evidence, publication errors, and editor review time'},
  {slug:'sales-administrative-assistant-remote-role-guide',title:'Remote sales administrative assistant: role guide, handoffs, and scorecard',keyword:'remote sales administrative assistant',role:'sales administrative assistant',outcome:'keep opportunity records and follow-up logistics current without turning administration into unauthorized selling',tasks:'updating evidence-backed CRM fields, preparing meeting briefs, sending approved reminders, maintaining proposal inputs, recording next actions, and assembling pipeline summaries',keep:'forecast judgment, discounts, contract terms, qualification exceptions, revenue promises, account ownership changes, and messages that commit the salesperson',tools:'restricted CRM role, calendar, proposal workspace, approved templates, field dictionary, and sales-manager escalation queue',sample:'prepare tomorrow’s sales meeting briefs and leave disputed stages, missing consent, and commercial questions for the named owner',metric:'records current from evidence, overdue next actions, unsupported stage changes, template corrections, and seller review time'},
  {slug:'property-management-virtual-assistant-hiring-guide',title:'Property management virtual assistant: hiring guide and remote-work boundaries',keyword:'property management virtual assistant hiring guide',role:'property management assistant',outcome:'organize tenant, vendor, and maintenance administration while local response, legal duties, and approval remain with the property team',tasks:'logging resident-supplied requests, collecting approved details, scheduling permitted vendor windows, maintaining document checklists, sending routine notices from templates, and preparing open-item summaries',keep:'emergency judgment, legal notices without approval, lease interpretation, vendor selection, repair authorization, entry decisions, refunds, and handling keys or physical property',tools:'property platform with limited permissions, approved templates, vendor directory, maintenance queue, and immediate local escalation route',sample:'triage a fictional request queue into routine, incomplete, urgent-review, and local-action lanes without diagnosing a repair',metric:'requests logged by cutoff, correct routing, missing information, unauthorized commitments, unresolved age, and manager review time'},
  {slug:'insurance-agency-virtual-assistant-administrative-scope',title:'Insurance agency virtual assistant: define a safe administrative scope',keyword:'insurance agency virtual assistant administrative scope',role:'insurance agency administrative assistant',outcome:'prepare complete service and renewal records while licensed advice and coverage decisions stay with authorized staff',tasks:'collecting customer-supplied information, checking document presence, scheduling reviews, preparing renewal lists, recording carrier messages, and routing policy-service requests',keep:'explaining coverage, recommending products, binding or changing policies, interpreting exclusions, quoting outside approved systems, signing forms, and deciding complaints',tools:'agency-approved systems with role-based access, document portal, renewal tracker, approved scripts, and licensed-agent escalation channel',sample:'prepare a redacted renewal-review packet and identify missing documents and customer questions without interpreting coverage',metric:'packets complete by cutoff, requests routed correctly, unsupported statements, access exceptions, and licensed-agent review time'},
  {slug:'online-course-virtual-assistant-hiring-guide',title:'Online course virtual assistant: hiring guide for learner and launch support',keyword:'online course virtual assistant hiring guide',role:'online course assistant',outcome:'keep learner administration, lesson assets, and launch checklists moving while the creator retains teaching and offer decisions',tasks:'uploading approved lessons, checking links and captions, answering documented access questions, maintaining learner queues, scheduling approved announcements, and preparing launch status reports',keep:'changing curriculum, promising outcomes, grading subjective work, altering prices, issuing exception refunds, giving professional advice, and publishing unapproved claims',tools:'learning platform staff role, help desk, approved knowledge base, asset register, launch board, and escalation channel',sample:'audit a fictional module for missing files, broken links, caption gaps, inconsistent titles, and decisions needed before release',metric:'lessons ready by cutoff, access cases resolved under policy, broken assets, reopened tickets, and creator review time'},
  {slug:'construction-administrative-virtual-assistant-role',title:'Construction administrative virtual assistant: role scope and hiring checklist',keyword:'construction administrative virtual assistant',role:'construction administrative assistant',outcome:'keep office-side project records organized while site observation, safety, estimating, and contractual decisions remain local',tasks:'indexing approved documents, maintaining submittal and request logs, collecting vendor paperwork, scheduling office meetings, preparing status summaries, and flagging missing acknowledgments',keep:'site safety decisions, field verification, interpreting plans, approving changes, selecting vendors, certifying work, committing cost or schedule, and controlling originals',tools:'project document system, shared drive, log templates, calendar, vendor checklist, and project-manager escalation route',sample:'build a source-linked register from redacted project emails and separate received facts from missing approvals and field questions',metric:'records indexed by cutoff, missing approvals found, incorrect versions, unsupported status changes, and project-manager review time'},
  {slug:'content-operations-virtual-assistant-job-description',title:'Content operations virtual assistant job description: workflow, QA, and limits',keyword:'content operations virtual assistant job description',role:'content operations assistant',outcome:'move approved content through an auditable production queue without inventing facts or bypassing editorial approval',tasks:'preparing briefs from approved notes, formatting drafts, checking required fields, maintaining source links, coordinating asset status, scheduling approved articles, and recording corrections',keep:'topic strategy, factual sign-off, legal review, expert attribution, unsupported claims, silent substantive edits, publication exceptions, and deletion of source history',tools:'editorial board, content system with limited role, source ledger, style guide, asset library, and editor escalation queue',sample:'prepare one redacted article package and distinguish copy fixes, factual questions, missing sources, and publication blockers',metric:'packages ready by cutoff, source gaps found, corrections by cause, unauthorized edits, blocked-item age, and editor review time'},
];

const officialSources = [
  {name:'NIST Cybersecurity Framework 2.0 Small Business Quick-Start Guide',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-20-small-business-quick-start-guide',note:'Official risk-management context for small and medium-sized businesses.'},
  {name:'FTC, Protecting Personal Information: A Guide for Business',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business',note:'Official guidance on limiting, protecting, and disposing of business information.'},
  {name:'CISA, Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication',note:'Official account-security guidance used for access planning.'},
  {name:'IRS, Independent contractor defined',url:'https://www.irs.gov/businesses/small-businesses-self-employed/independent-contractor-defined',note:'Official U.S. worker-classification overview; businesses should apply the rules to their facts.'},
] as const;

export const sep22BlogPosts = briefs.map((b, index) => {
  const paragraphs = [
    `A ${b.role} is a sensible remote hire when the work has a repeatable input, an approved system, and an accountable reviewer. The role should produce an observable result: ${b.outcome}. A broad request to “help wherever needed” hides the decisions that still belong to the business. Start with one work family, a cutoff stated with a time zone, and examples of both acceptable output and work that must stop.`,
    `A useful first scope can include ${b.tasks}. Convert that list into inspectable units. Every unit needs a trigger, approved source, expected output, destination, due time, and named reviewer. If a source is missing or two records conflict, the assistant should preserve what was checked and open an exception. Filling a gap from memory may look fast, but it makes the record less reliable.`,
    `The business should retain ${b.keep}. Put those limits in the daily instructions and the work sample, not only in a policy document. The assistant needs to recognize the boundary, stop without penalty, record the evidence already reviewed, and send one bounded question to a person who can answer it. A stop rule without an available owner simply creates a hidden backlog.`,
    `Plan the role around ${b.tools}. Give the assistant a named account and the narrowest permissions that support the starting queue. Keep permission administration, account recovery, bulk export, destructive actions, and unrelated folders outside the initial role. Multifactor authentication helps protect sign-in, while a password manager avoids casual credential sharing; neither replaces an access inventory and prompt offboarding.`,
    `Use a representative paid exercise before widening access. Ask the candidate to ${b.sample}. Supply redacted material, the actual field definitions, a deadline, and the same escalation rules used in live work. Review source discipline, written judgment, and communication rather than rewarding a candidate for guessing through missing information. Never use live customer credentials or sensitive production records in a hiring test.`,
    `Train with four cases: one ordinary item, one incomplete item, one conflicting-source item, and one item outside the role. Ask which source controls, what should be recorded, where work stops, and who receives the question. Then run a small supervised batch. When a reasonable person could read an instruction two ways, repair the instruction and example before measuring the worker.`,
    `The daily handoff should show ready work, work waiting on the business, work waiting on an outside party, stopped exceptions, and closed items. Each row needs a source, owner, next action, and timestamp. This structure separates movement from completion and prevents an old unresolved item from looking current merely because someone moved it or edited a note.`,
    `For the first thirty days, review ${b.metric}. Define each measure before the first batch. A completed item should satisfy the written output rule, not merely contain activity. Sample the source trail as well as the final wording. Group corrections by cause—missing source, unclear instruction, access problem, skill gap, or owner delay—so the response addresses the system that produced the error.`,
    `Hire Assistant Near Me recruits and hires assistants in the Philippines for remote work. “Near me” describes a search for dependable support, not physical local coverage. Separate errands, walk-in reception, custody of originals, site observation, and locally licensed work before matching candidates. When a workflow has both remote preparation and a local step, name both owners and define the handoff.`,
    `Expand only after reviewing a representative week. Add one adjacent duty when the original queue is traceable, exceptions reach the right owner, access remains appropriate, and review time is sustainable. The new duty needs its own approved source, example, permission decision, stop rule, and rollback path. More volume does not prove the operating model is safe or useful.`,
    `Privacy, worker classification, record retention, professional duties, marketing rules, and customer communications depend on the business and jurisdiction. The NIST and CISA sources below offer general security planning; the FTC discusses protecting business information; the IRS explains factors relevant to U.S. worker classification. None of those sources decides the requirements for a particular arrangement.`,
    `Bring a complete role brief to the hiring conversation: the outcome, recurring units, hours and time zone, approved systems, access limits, representative examples, reviewer, escalation route, and first-month measures. That brief lets a candidate understand the job and lets the owner inspect the result. It also gives the staffing team something concrete to recruit against instead of treating the title as the scope.`,
  ];
  const headings = ['Define the result before the title','Turn duties into inspectable units','Write the authority boundary','Plan access before granting it','Test the actual work','Train on ordinary and exceptional cases','Make the daily handoff visible','Use a 30-day scorecard','Separate remote and local work','Expand one controlled step at a time','Review legal and privacy obligations','Bring a complete brief to the hiring call'];
  return {
    slug:b.slug, mainKeyword:b.keyword, title:b.title,
    excerpt:`Plan the duties, access, work sample, stop rules, and first-month scorecard for a Philippines-based ${b.role}.`,
    published, richPublished:true, minutes:12,
    image:['/images/assistant-maya.jpg','/images/assistant-daniel.jpg','/images/assistant-elena.jpg'][index%3],
    imageAlt:`Philippines-based ${b.role} reviewing a documented remote-work queue`,
    sourceBody:`Publication date: September 22, 2026.\n\n${paragraphs.join('\n\n')}`,
    takeaways:[`Start the ${b.role} with one measurable workflow.`,`Keep ${b.keep} with the accountable owner.`,`Use named, limited access and a visible exception queue.`],
    detail:{
      revision:`${published}-${b.slug}-r1`, directAnswer:paragraphs.slice(0,2),
      bodyLinks:[{href:'/services',label:'compare assistant service lanes'},{href:'/compare/local-vs-remote-assistant',label:'separate local and remote work'},{href:'/contact-us',label:'prepare a role brief'}],
      sections:headings.map((heading,n)=>({heading,paragraphs:[paragraphs[n]]})),
      decisionRows:[{need:`Recurring ${b.role} preparation`,fit:'Philippines-based remote assistant',reason:'The work is online, documented, and reviewable.'},{need:'Physical presence or custody',fit:'Local employee or vendor',reason:'The task cannot be completed through approved online systems.'},{need:'Judgment, commitment, or sensitive exception',fit:'Owner or qualified professional',reason:`This includes ${b.keep}.`}],
      planningNumbers:[{value:'1 queue',label:'Starting scope',note:'One repeatable work family.'},{value:'4 cases',label:'Training sample',note:'Ordinary, incomplete, conflicting, and boundary cases.'},{value:'1 owner',label:'Escalation route',note:'A named person who answers stopped items.'},{value:'30 days',label:'Review point',note:'Keep, narrow, repair, or add one duty.'}],
      scripts:[{title:'Candidate work sample',text:`Using redacted material, ${b.sample}. Link each source, preserve missing facts, and stop at the written boundary.`},{title:'Daily handoff',text:'Report ready items, waiting items, stopped exceptions, and decisions needed. Include the source, owner, next action, and time zone.'}],
      scenario:{title:`A controlled first week for a ${b.role}`,intro:'Use a small mixed batch to test instructions, source trails, communication, and review rhythm.',steps:[{step:'1',title:'Confirm the unit',body:`Choose one unit from ${b.tasks}.`},{step:'2',title:'Confirm access',body:`Grant only the required view in ${b.tools}.`},{step:'3',title:'Run four cases',body:'Include ordinary, incomplete, conflicting, and boundary cases.'},{step:'4',title:'Review evidence',body:'Check the source and decision trail, not only the finished wording.'},{step:'5',title:'Repair one rule',body:'Update the example or stop rule before increasing volume.'}]},
      faqs:[{question:`What should a ${b.role} do first?`,answer:`Begin with one documented lane such as ${b.tasks}. Keep the batch small enough for daily review.`},{question:'What should remain with the owner?',answer:`Keep ${b.keep} with the accountable owner or qualified professional.`},{question:'Can this role perform local, in-person work?',answer:'No. Hire Assistant Near Me offers assistants recruited and hired in the Philippines for remote work.'},{question:'How should access begin?',answer:`Use a named account with only the permissions required in ${b.tools}, then review access whenever duties change.`},{question:'How should the first month be judged?',answer:`Review ${b.metric}. Define each measure before work begins.`}],
      relatedLinks:[{href:'/services',label:'Compare remote assistant service lanes'},{href:'/compare/local-vs-remote-assistant',label:'Compare local and remote task fit'},{href:'/blog/virtual-assistant-security-checklist',label:'Plan account and access safeguards'},{href:'/contact-us',label:'Build a Philippines-based role brief'}],
      sources:officialSources,
    }
  };
});
