type Brief = {
  slug: string; title: string; keyword: string; excerpt: string; image: string;
  situation: string; record: string; owner: string; mistake: string; cadence: string;
};

const published = '2026-09-04' as const;

const briefs: Brief[] = [
  { slug:'dental-recall-list-preparation-without-clinical-advice', title:'Prepare a dental recall list without giving clinical advice', keyword:'dental recall assistant', excerpt:'A practical routine for checking approved recall records while the dental team keeps every care and patient-contact decision.', image:'/images/calendar-assistant.jpg', situation:'a dental office has overdue recall records mixed with recent appointments and unresolved chart notes', record:'patient ID, last completed visit, recall status, preferred contact route, source screen, and open question', owner:'the dentist or authorized practice manager', mistake:'treating a software flag as a clinical instruction', cadence:'once each morning before the practice reviews outreach' },
  { slug:'home-service-estimate-follow-up-queue-without-price-promises', title:'Build a home-service estimate follow-up queue without price promises', keyword:'estimate follow up assistant', excerpt:'Keep estimate status and customer questions visible without letting a remote assistant alter scope, price, or arrival commitments.', image:'/images/aug20-blog-reminder-queues.png', situation:'a home-service company has sent estimates that now sit across email, field software, and handwritten call notes', record:'customer, property, estimate number, sent date, stated next step, customer reply, and estimator owner', owner:'the estimator or service manager', mistake:'turning a follow-up message into a discount or scheduling promise', cadence:'at the agreed follow-up window on business days' },
  { slug:'law-firm-document-request-index-before-attorney-review', title:'Index a law firm document request before attorney review', keyword:'legal document request assistant', excerpt:'Organize received files and missing-item questions while lawyers retain interpretation, privilege, and response authority.', image:'/images/aug20-blog-source-ledger.png', situation:'a law firm receives client files under inconsistent names and through more than one approved channel', record:'matter ID, request item, received filename, source, received time, possible duplicate, and review state', owner:'the assigned attorney or authorized legal staff member', mistake:'deciding that a document satisfies a legal request', cadence:'after each authorized intake window' },
  { slug:'shopify-return-reason-review-before-policy-decisions', title:'Review Shopify return reasons before changing policy', keyword:'Shopify returns assistant', excerpt:'Turn approved return records into a useful issue summary without judging eligibility or changing store policy.', image:'/images/aug20-blog-listing-admin.png', situation:'an ecommerce owner sees returns rising but the reason notes contain spelling variants, blank fields, and customer comments', record:'order ID, product, recorded reason, customer wording, refund state, policy version, and exception owner', owner:'the store owner or returns lead', mistake:'rewriting a customer reason to make the data look tidy', cadence:'in a weekly sample and before any policy meeting' },
  { slug:'property-management-lease-renewal-date-watch-with-stop-rules', title:'Watch lease renewal dates with clear stop rules', keyword:'lease renewal assistant', excerpt:'Prepare a dated renewal watchlist while terms, notices, negotiations, and legal questions stay with property staff.', image:'/images/aug21-blog-calendar-repair.png', situation:'a property manager needs advance notice of lease dates without delegating lease interpretation', record:'property, unit, lease source, displayed end date, notice field, conflicting copy, and manager decision date', owner:'the property manager or qualified legal reviewer', mistake:'calculating a notice deadline when the lease language is unclear', cadence:'on the manager-set calendar and whenever an approved lease copy changes' },
  { slug:'accounting-client-month-end-file-chase-without-tax-guidance', title:'Run a month-end client file chase without giving tax guidance', keyword:'accounting file collection assistant', excerpt:'Track requested records and polite reminders while accountants decide sufficiency, classification, and tax treatment.', image:'/images/aug20-blog-invoice-followup.png', situation:'an accounting practice is waiting on bank statements, receipts, and answers from several clients near month end', record:'client ID, requested item, request date, approved channel, response, file location, and accountant question', owner:'the assigned accountant or bookkeeper', mistake:'telling a client that a record is acceptable for tax purposes', cadence:'at the firm-approved reminder intervals' },
  { slug:'agency-client-approval-log-before-campaign-launch', title:'Keep a client approval log before an agency campaign launch', keyword:'client approval tracking assistant', excerpt:'Preserve exact approvals, versions, and open questions so campaign launch authority remains with the client and agency lead.', image:'/images/aug21-blog-content-briefs.png', situation:'an agency has copy, creative, targeting notes, and scattered client replies moving toward one launch', record:'asset ID, version, approval wording, approver, channel, timestamp, restriction, and launch owner', owner:'the agency lead named in the campaign plan', mistake:'reading a casual positive comment as final approval', cadence:'after each approved feedback window and again before launch review' },
  { slug:'veterinary-prescription-refill-intake-with-clinical-boundaries', title:'Prepare veterinary refill intake with clinical boundaries', keyword:'veterinary refill assistant', excerpt:'Collect complete refill requests while veterinarians retain prescribing, urgency, and animal-care decisions.', image:'/images/aug20-blog-inbox-triage.png', situation:'a veterinary clinic receives refill requests by phone and portal with missing pet or medication details', record:'client ID, patient name, requested medication text, supplied dose, remaining amount, pharmacy, callback route, and clinical owner', owner:'the veterinarian or authorized clinic employee', mistake:'suggesting a dose or implying that a refill will be approved', cadence:'during the clinic-defined intake periods' },
  { slug:'construction-change-order-source-packet-before-cost-approval', title:'Assemble a construction change-order source packet before cost approval', keyword:'construction change order assistant', excerpt:'Gather the drawings, request history, and quoted figures while project leaders keep scope, safety, and spending decisions.', image:'/images/aug20-blog-vendor-onboarding.png', situation:'a small contractor has a proposed change discussed across site notes, email, and supplier quotations', record:'project, request origin, drawing or photo link, quote version, stated schedule effect, unresolved conflict, and approver', owner:'the project manager or authorized company officer', mistake:'presenting an unverified quote as an approved project cost', cadence:'when a change request enters the formal review queue' },
  { slug:'real-estate-open-house-lead-notes-before-agent-outreach', title:'Clean open-house lead notes before agent outreach', keyword:'open house lead assistant', excerpt:'Prepare readable, source-linked lead records while the licensed agent controls advice, representation, and follow-up claims.', image:'/images/aug20-blog-crm-cleanup.png', situation:'an agent returns from an open house with sign-in entries, shorthand notes, and consent fields that do not always agree', record:'lead ID, supplied contact details, property, visit time, original note, consent state, duplicate candidate, and agent owner', owner:'the licensed real estate agent or brokerage lead', mistake:'inventing buying intent from a brief conversation note', cadence:'after the event and before the agent approves outreach' },
  { slug:'saas-customer-health-note-preparation-without-renewal-promises', title:'Prepare SaaS customer health notes without making renewal promises', keyword:'SaaS customer success assistant', excerpt:'Summarize approved account signals for review while customer-success leaders own risk labels, concessions, and commitments.', image:'/images/aug21-blog-interview-notes.png', situation:'a SaaS team needs a current account brief before a renewal meeting but product use, tickets, and meeting notes live in separate tools', record:'account, reporting period, cited usage field, unresolved ticket, last customer statement, contract date, and account owner', owner:'the customer-success manager or account executive', mistake:'turning low activity into an unsupported churn prediction', cadence:'before the scheduled account review' },
  { slug:'nonprofit-volunteer-background-check-status-with-privacy-limits', title:'Track volunteer background-check status with privacy limits', keyword:'volunteer screening assistant', excerpt:'Maintain a minimum-data status queue while designated nonprofit leaders handle screening results and placement decisions.', image:'/images/aug21-blog-task-fit.png', situation:'a nonprofit coordinates volunteers for several programs and needs to know which approved screening steps remain open', record:'volunteer ID, program, consent recorded, vendor status, submitted date, result available flag, restriction, and authorized reviewer', owner:'the designated screening lead', mistake:'copying sensitive result details into a general volunteer tracker', cadence:'only through the approved screening workflow and review schedule' }
];

const sources = [
  { name:'NIST Cybersecurity Basics', url:'https://www.nist.gov/itl/smallbusinesscyber/cybersecurity-basics', note:'Account access and data-protection context.' },
  { name:'U.S. Bureau of Labor Statistics, Secretaries and Administrative Assistants', url:'https://www.bls.gov/ooh/office-and-administrative-support/secretaries-and-administrative-assistants.htm', note:'Occupational context for administrative support.' }
];

export const sep4BlogPosts = briefs.map((b, index) => {
  const opening = `The useful part of this job is preparation. ${b.situation}. A Philippines-based remote assistant can organize the approved records and return a clear queue. ${b.owner} still decides what the information means and what happens next.`;
  const evidence = `For each item, capture ${b.record}. Keep the original wording or file link close to the summary. If two sources disagree, show both. A blank field should stay blank until the named owner supplies or verifies it.`;
  const boundary = `The common failure is ${b.mistake}. Write that stop rule into the assignment, then include a realistic example. The assistant should flag the item, explain what is missing in one sentence, and move on to work that is ready.`;
  const handoff = `Run the routine ${b.cadence}. The handoff should say where the assistant stopped, which records changed, what needs review, and which item is oldest. That is enough for the owner to resume the work without replaying an entire inbox or chat thread.`;
  const access = `Start with the smallest practical view of the source system. Use a named account when the tool supports one. Exporting a full customer list, changing permissions, deleting records, publishing messages, moving money, or using recovery credentials needs separate approval.`;
  const review = `Review a mixed sample rather than checking only the exceptions. Include one ordinary item, one incomplete item, and one item that reached the authority boundary. Record the correction in plain language and change the instruction only when the new rule is specific enough to test.`;
  const ending = `After a week, look at returned items and owner time, not just completed rows. A short queue can be useful if it exposes the right questions. A large queue can be misleading when the assistant quietly filled gaps. Keep the lane narrow until the evidence record and stop rule work reliably.`;
  const paragraphs = [opening, evidence, boundary, handoff, access, review, ending];
  const headings = ['Define the actual queue','Keep the source beside the summary','Write the stop rule plainly','Make the handoff easy to resume','Limit access to the task','Review a mixed sample','Decide from the returned work'];
  return {
    slug:b.slug, mainKeyword:b.keyword, title:b.title, excerpt:b.excerpt, published, richPublished:true,
    minutes:8 + (index % 3), image:b.image, imageAlt:`Remote assistant preparing ${b.keyword} records for owner review`,
    sourceBody:`Publication date: September 4, 2026.\n\n${paragraphs.join('\n\n')}`,
    takeaways:[`Build one queue for ${b.keyword}.`,`Record ${b.record}.`,`Keep the decision with ${b.owner}.`,`Stop before ${b.mistake}.`],
    detail:{
      revision:`${published}-${b.slug}-r1`, directAnswer:[opening,evidence],
      bodyLinks:[{href:'/services',label:'assistant services'},{href:'/research',label:'research library'}],
      sections:headings.map((heading,i)=>({heading,paragraphs:[paragraphs[i],paragraphs[(i+3)%paragraphs.length]]})),
      decisionRows:[{need:'Record preparation',fit:'Remote assistant',reason:'Uses approved sources and produces a reviewable queue.'},{need:'Meaning or approval',fit:'Named owner',reason:`Stays with ${b.owner}.`},{need:'Missing evidence',fit:'Exception',reason:'The assistant records the gap instead of guessing.'},{need:'More access',fit:'Separate review',reason:'Permissions should not expand silently.'}],
      planningNumbers:[{value:'1 queue',label:'Starting scope',note:b.keyword},{value:'3 cases',label:'Training sample',note:'Ordinary, incomplete, and stopped.'},{value:'1 owner',label:'Decision route',note:b.owner},{value:'Sep 4',label:'Publication date',note:'September 4, 2026.'}],
      scripts:[{title:'Assignment',text:`Prepare the approved ${b.keyword} queue. Capture ${b.record}.`},{title:'Escalation',text:`I stopped because this item may involve ${b.mistake}. The source and open question are attached.`}],
      scenario:{title:`A first pass for ${b.keyword}`,intro:'Use a small, varied batch before opening the full queue.',steps:[{step:'1',title:'Confirm',body:'Check the source, cutoff, and permitted account.'},{step:'2',title:'Prepare',body:`Capture ${b.record}.`},{step:'3',title:'Compare',body:'Keep conflicting values visible.'},{step:'4',title:'Stop',body:`Route judgment to ${b.owner}.`},{step:'5',title:'Revise',body:'Turn one correction into a clearer written rule.'}]},
      faqs:[{question:'Can the assistant make the final decision?',answer:`No. The final decision stays with ${b.owner}.`},{question:'What happens when information is missing?',answer:'The queue records the missing field, source checked, and next owner.'},{question:'Should access grow after a good first batch?',answer:'Only after a separate review of the new task and permission.'},{question:'Where are assistants hired?',answer:'Hire Assistant Near Me recruits and hires assistants in the Philippines for remote work.'}],
      relatedLinks:[{href:'/services',label:'Compare remote assistant service lanes'},{href:'/research',label:'Read source-backed staffing research'}], sources
    }
  };
});
