type Brief = { slug:string; title:string; keyword:string; excerpt:string; image:string; scene:string; fields:string; owner:string; stop:string; rhythm:string };

const published = '2026-09-07' as const;
const briefs: Brief[] = [
  {slug:'architecture-rfi-register-assistant-routine',title:'An RFI register routine for a small architecture studio',keyword:'architecture RFI assistant',excerpt:'A daily way to log incoming project questions without letting an assistant interpret drawings or issue design direction.',image:'/images/aug20-blog-source-ledger.png',scene:'An architecture studio receives requests for information by email, project portals, and meeting notes. A question can look answered in one place while the official response is still open elsewhere',fields:'project number, RFI number, exact question, sender, received time, drawing reference supplied by the sender, current status, and architect owner',owner:'the project architect',stop:'interpreting a drawing, choosing a specification, or describing a draft as issued',rhythm:'at the morning inbox review and once before the studio closes'},
  {slug:'independent-bookstore-special-order-desk-assistant-routine',title:'A calmer special-order desk for an independent bookstore',keyword:'bookstore special order assistant',excerpt:'Organize customer requests, distributor lookups, and arrival notes while the bookseller keeps purchasing and refund decisions.',image:'/images/aug20-blog-order-exceptions.png',scene:'A neighborhood bookstore takes special-order requests at the counter, over the phone, and through email. Titles, editions, and customer expectations are easy to mix up',fields:'request ID, customer contact route, title as requested, author, ISBN if supplied, edition note, distributor checked, quoted status, and bookseller owner',owner:'the store buyer or bookseller on duty',stop:'promising availability, ordering inventory, or changing a refund term',rhythm:'after each approved lookup window and before customer callbacks'},
  {slug:'commercial-cleaning-site-walk-note-assistant-routine',title:'Turn commercial cleaning site-walk notes into a reviewable scope',keyword:'commercial cleaning bid assistant',excerpt:'Prepare a clean site-walk record without letting a remote assistant set labor assumptions, safety terms, or a bid price.',image:'/images/aug21-blog-interview-notes.png',scene:'A commercial cleaning company finishes a site walk with room counts, photos, access notes, and questions spread across several devices',fields:'prospect, site, room or zone, observed surface, frequency requested, access window stated by the prospect, photo link, open question, and estimator owner',owner:'the estimator or operations manager',stop:'calculating labor, judging a hazard, or turning an observation into a contractual promise',rhythm:'the same business day while the site-walk context is still fresh'},
  {slug:'community-theater-rehearsal-conflict-assistant-routine',title:'Sort community theater rehearsal conflicts without recasting the show',keyword:'theater scheduling assistant',excerpt:'Keep availability changes and unresolved conflicts visible while the director and stage manager retain artistic and personnel decisions.',image:'/images/calendar-assistant.jpg',scene:'A community theater has cast availability arriving through forms, texts, and email as rehearsals approach. One casual message can affect several scenes',fields:'production, person, role or crew area, affected rehearsal, original availability source, new message, conflict status, and stage-manager owner',owner:'the stage manager or director',stop:'changing the call sheet, excusing an absence, or making a casting decision',rhythm:'once after the response cutoff and again before the call sheet is approved'},
  {slug:'funeral-home-family-document-intake-assistant-routine',title:'A careful document-intake routine for a funeral home',keyword:'funeral home intake assistant',excerpt:'Track received forms and missing administrative details with restraint while licensed staff handle arrangements and family guidance.',image:'/images/aug20-blog-inbox-triage.png',scene:'A funeral home may receive identification, authorization forms, and service preferences through restricted channels during a difficult week for a family',fields:'case ID, document name, approved source, received time, readable status, missing field noted without interpretation, restricted file link, and licensed staff owner',owner:'the funeral director or authorized employee',stop:'giving arrangement advice, discussing legal sufficiency, or copying sensitive details into a general tracker',rhythm:'only during the firm\'s approved intake windows'},
  {slug:'museum-group-visit-question-queue-assistant-routine',title:'Build a museum group-visit question queue that staff can answer',keyword:'museum group visit assistant',excerpt:'Collect dates, access questions, and group details while museum staff keep capacity, accommodation, and pricing decisions.',image:'/images/aug20-blog-content-calendar.png',scene:'A small museum receives school, senior, and tour-group inquiries that arrive before calendars and staffing are fully confirmed',fields:'inquiry ID, organization, requested date and time, group size supplied, age range if volunteered, access question in the sender\'s words, contact route, and visitor-services owner',owner:'the visitor-services manager',stop:'confirming a slot, interpreting an accommodation need, or quoting an unapproved rate',rhythm:'each weekday before the visitor-services review'},
  {slug:'pet-grooming-rebooking-queue-assistant-routine',title:'A pet-grooming rebooking queue that leaves care calls with the groomer',keyword:'pet grooming booking assistant',excerpt:'Prepare follow-up records from completed appointments without recommending services or promising a safe schedule.',image:'/images/aug20-blog-reminder-queues.png',scene:'A grooming shop wants to follow up after visits, but pet notes, owner preferences, and future timing may not agree',fields:'client ID, pet name, completed appointment date, service recorded, owner-stated preference, groomer note link, contact permission, open question, and groomer owner',owner:'the groomer or shop manager',stop:'recommending a service interval, assessing an animal, or guaranteeing an appointment',rhythm:'after completed visits at the shop-approved follow-up time'},
  {slug:'solar-consultation-roof-record-assistant-routine',title:'Prepare a solar consultation roof-record packet without making savings claims',keyword:'solar consultation assistant',excerpt:'Gather customer-supplied property details and files while specialists retain design, eligibility, production, and savings judgments.',image:'/images/aug23-research-source-scope.png',scene:'A solar company needs a usable intake packet before a consultation, yet utility files, roof photos, and property notes often arrive separately',fields:'lead ID, property address as supplied, utility document period, photo link, roof note in the customer\'s words, ownership field, missing item, and consultant owner',owner:'the qualified solar consultant',stop:'estimating production, claiming eligibility, reading structural condition, or promising savings',rhythm:'before the consultant\'s scheduled preparation window'},
  {slug:'wedding-photographer-shot-request-assistant-routine',title:'Organize wedding shot requests without promising the photographer\'s coverage',keyword:'wedding photographer assistant',excerpt:'Turn scattered client notes into a source-linked review list while the photographer controls feasibility, timing, and creative decisions.',image:'/images/aug21-blog-content-briefs.png',scene:'A wedding photographer receives family names, venue rules, and requested moments through questionnaires and follow-up messages',fields:'event ID, requested moment in the client\'s words, named people, location supplied, timing note, source message, possible conflict, and photographer owner',owner:'the lead photographer',stop:'guaranteeing a shot, changing the timeline, or making a creative commitment',rhythm:'after questionnaire updates and before the final planning call'},
  {slug:'industrial-parts-quote-document-assistant-routine',title:'Keep industrial parts quote documents tied to the right request',keyword:'industrial parts quote assistant',excerpt:'Index part numbers, revisions, and supplier files without letting an assistant confirm fit, equivalence, or purchase terms.',image:'/images/aug20-blog-vendor-onboarding.png',scene:'An industrial distributor receives drawings, part numbers, and revised quote files under similar email subjects',fields:'request ID, customer part number, manufacturer number as supplied, revision, quantity requested, file link, supplier response date, discrepancy, and sales engineer owner',owner:'the sales engineer or authorized buyer',stop:'confirming interchangeability, technical fit, lead time, price, or an order',rhythm:'after each supplier response and before quote review'},
  {slug:'landscaping-seasonal-service-request-assistant-routine',title:'Sort seasonal landscaping requests before the route plan changes',keyword:'landscaping service request assistant',excerpt:'Prepare a property-by-property request list while field leaders decide safety, scope, price, and route changes.',image:'/images/aug20-blog-support-escalations.png',scene:'A landscaping company gets seasonal requests alongside weather delays and existing service notes. A short customer email may not describe the actual field condition',fields:'customer ID, property, request in original wording, photo link if supplied, current service plan reference, preferred contact route, open question, and field owner',owner:'the crew leader or service manager',stop:'diagnosing plant or site conditions, changing a route, or quoting work',rhythm:'before the daily dispatch review'},
  {slug:'music-school-makeup-lesson-assistant-routine',title:'A makeup-lesson queue for a busy music school',keyword:'music school scheduling assistant',excerpt:'Reconcile absence messages and teacher availability while school staff keep policy exceptions and teaching decisions.',image:'/images/aug21-blog-calendar-repair.png',scene:'A music school handles student absences, teacher changes, room limits, and makeup rules across a crowded weekly calendar',fields:'student ID, teacher, original lesson, absence source and time, policy version, offered availability from approved calendars, unresolved conflict, and school owner',owner:'the studio manager or teacher named by policy',stop:'granting an exception, assessing lesson progress, or confirming a time outside approved availability',rhythm:'after the absence cutoff and before the next scheduling block'}
];

const sources = [
  {name:'NIST Cybersecurity Basics',url:'https://www.nist.gov/itl/smallbusinesscyber/cybersecurity-basics',note:'Practical context for accounts, access, and business data.'},
  {name:'U.S. Small Business Administration, Manage Your Business',url:'https://www.sba.gov/business-guide/manage-your-business',note:'General operating context for small businesses.'}
];

export const sep7BlogPosts = briefs.map((b,index) => {
  const opening = `${b.scene}. A Philippines-based remote assistant can make the next review less messy by preparing one dated record. ${b.owner} still decides what the facts mean and what the business will do.`;
  const evidence = `The working row should contain ${b.fields}. Preserve the sender's wording where nuance matters. Link to the approved source instead of pasting private material into a broad channel.`;
  const boundary = `Put one blunt stop rule beside the template: the assistant must pause before ${b.stop}. A useful exception note names the affected item, the last source checked, the unanswered question, and the person who owns the answer.`;
  const cadence = `Run this check ${b.rhythm}. Mark the cutoff with a time zone. New information that arrives later belongs in the next pass unless the named owner asks for a documented update.`;
  const access = `Give the assistant only the folders, views, and fields needed for this queue. Keep recovery credentials, exports, deletion, payment, public messages, and permission changes with the account owner. Review access when the task changes.`;
  const review = `Check the first batch line by line. Include an ordinary record, an incomplete one, and one that reaches the stop rule. Note why anything came back. A correction such as "use the latest numbered attachment" is more useful than "be careful."`;
  const close = `After a week, compare clean handoffs with returned questions and owner review time. Do not expand the lane because the tracker looks full. Expand only when the sources remain easy to trace and the exceptions reach the right person without guesswork.`;
  const ps=[opening,evidence,boundary,cadence,access,review,close];
  const hs=['Start with the real inbox','Build a record someone else can check','Make the stopping point obvious','Choose a daily cutoff','Keep access proportional','Review awkward cases too','Decide from the handoff'];
  return {slug:b.slug,mainKeyword:b.keyword,title:b.title,excerpt:b.excerpt,published,richPublished:true,minutes:8+(index%3),image:b.image,imageAlt:`A remote assistant preparing a ${b.keyword} record for owner review`,sourceBody:`Publication date: September 7, 2026.\n\n${ps.join('\n\n')}`,takeaways:[`Use one dated ${b.keyword} queue.`,`Keep the source beside every material field.`,`Route decisions to ${b.owner}.`,`Stop before ${b.stop}.`],detail:{revision:`${published}-${b.slug}-r1`,directAnswer:[opening,evidence],bodyLinks:[{href:'/services',label:'assistant services'},{href:'/research',label:'research library'}],sections:hs.map((heading,i)=>({heading,paragraphs:[ps[i],ps[(i+2)%ps.length]]})),decisionRows:[{need:'Record preparation',fit:'Remote assistant',reason:'Produces a source-linked queue from approved inputs.'},{need:'Business judgment',fit:'Named owner',reason:`Remains with ${b.owner}.`},{need:'Missing or conflicting facts',fit:'Exception route',reason:'Preserves the gap and asks a bounded question.'},{need:'Broader system access',fit:'Separate approval',reason:'A completed batch does not grant more authority.'}],planningNumbers:[{value:'1 queue',label:'First scope',note:b.keyword},{value:'3 cases',label:'Review sample',note:'Ordinary, incomplete, and stopped.'},{value:'1 owner',label:'Decision route',note:b.owner},{value:'Sep 7',label:'Publication date',note:'September 7, 2026.'}],scripts:[{title:'Daily assignment',text:`Prepare today's ${b.keyword} queue from approved sources. Record ${b.fields}.`},{title:'Exception note',text:`I stopped at this item because it may require ${b.stop}. The last checked source and open question are linked.`}],scenario:{title:`First-week check for ${b.keyword}`,intro:'Use a small mixed batch before opening the full workload.',steps:[{step:'1',title:'Confirm the cutoff',body:'Name the source systems, review time, and time zone.'},{step:'2',title:'Prepare the row',body:`Capture ${b.fields}.`},{step:'3',title:'Preserve conflicts',body:'Show both supplied values and link to their sources.'},{step:'4',title:'Stop cleanly',body:`Send judgment to ${b.owner}.`},{step:'5',title:'Improve one rule',body:'Turn a real correction into a testable example.'}]},faqs:[{question:'Can the assistant make the final decision?',answer:`No. The final decision stays with ${b.owner}.`},{question:'What if a field is missing?',answer:'Leave it visibly open, record the source checked, and route the question.'},{question:'When should access expand?',answer:'Only after a separate review of the added task, data, and permission.'},{question:'Where does Hire Assistant Near Me recruit?',answer:'The service recruits and hires assistants in the Philippines for remote work.'}],relatedLinks:[{href:'/services',label:'Review remote assistant service lanes'},{href:'/research',label:'Read the research library'}],sources}};
});
