const published = '2026-09-09';

const briefs = [
  ['piano-technician-service-history-assistant-routine','A service-history routine for an independent piano technician','piano technician admin assistant','Turn tuning notes, access details, and follow-up requests into a dependable service record without letting admin work become technical diagnosis.','/images/aug20-blog-crm-cleanup.png','instrument location, make, last service date, customer wording, access note, requested window, and technician owner','the piano technician','diagnosing an instrument, specifying a repair, or promising a service interval'],
  ['pottery-studio-kiln-queue-assistant-routine','Keep a community pottery studio kiln queue reviewable','pottery studio admin assistant','Organize firing requests and missing labels while trained studio staff retain kiln-loading, firing, and safety decisions.','/images/aug20-blog-order-exceptions.png','member ID, clay body as stated, glaze note, piece count, shelf location, submitted date, and studio reviewer','the studio manager or kiln technician','judging material compatibility, loading a kiln, or approving a firing'],
  ['arborist-site-visit-intake-assistant-routine','Prepare arborist site visits without guessing at tree risk','arborist scheduling assistant','Build a source-linked visit packet from customer facts while the arborist owns risk assessment, scope, and treatment advice.','/images/aug20-blog-inbox-triage.png','job ID, address, tree location, customer wording, supplied photos, access constraints, preferred window, and arborist owner','the certified arborist or crew lead','assessing hazard, recommending treatment, or promising emergency priority'],
  ['independent-optician-frame-order-exception-routine','An exception routine for an independent optician’s frame orders','optician order admin assistant','Separate carrier, supplier, and customer-status facts while qualified staff retain prescription, fit, and clinical decisions.','/images/aug20-blog-order-exceptions.png','order ID, frame SKU, supplier confirmation, carrier event, promised date source, open exception, and optician owner','the dispensing optician or practice owner','interpreting a prescription, advising on fit, or changing a clinical order'],
  ['makerspace-tool-orientation-record-assistant-routine','Maintain makerspace tool-orientation records without granting access','makerspace membership assistant','Prepare auditable orientation records while authorized staff decide competency, tool access, and safety restrictions.','/images/aug21-blog-publishing-checklists.png','member ID, tool, session date, instructor, checklist version, recorded outcome, restriction note, and access owner','the authorized instructor or shop manager','certifying competency, enabling access, or waiving a safety requirement'],
  ['small-marina-slip-inquiry-assistant-routine','Triage slip inquiries for a small marina','marina inquiry assistant','Collect vessel and availability questions in one queue while marina staff retain fit, safety, pricing, and berth assignments.','/images/aug20-blog-listing-admin.png','inquiry ID, vessel dimensions as supplied, requested dates, utilities requested, customer questions, missing facts, and dockmaster owner','the dockmaster or marina manager','confirming fit, assigning a slip, setting price, or giving navigation advice'],
  ['letterpress-studio-proof-approval-assistant-routine','A proof-approval trail for a letterpress studio','letterpress project assistant','Preserve proof versions and client wording so the printer can act on a clear approval record without hidden design changes.','/images/aug21-blog-content-briefs.png','job ID, proof version, delivery timestamp, client response, requested correction, approval state, and printer owner','the printer or studio lead','altering artwork, approving color, changing stock, or releasing production'],
  ['dog-training-school-class-roster-assistant-routine','Prepare a dog-training class roster without making behavior judgments','dog training admin assistant','Assemble enrollment and logistics facts while trainers retain suitability, behavior, safety, and training decisions.','/images/calendar-assistant.jpg','registration ID, class, handler contact route, dog details as supplied, vaccination-document status, stated concern, and trainer owner','the qualified trainer or program lead','assessing behavior, determining class suitability, or giving training advice'],
  ['mobile-sauna-booking-readiness-assistant-routine','A booking-readiness routine for a mobile sauna operator','mobile sauna booking assistant','Check site and schedule inputs before owner review without promising feasibility, safety, or final arrival timing.','/images/aug20-blog-calendar-conflicts.png','booking ID, address, requested window, access description, surface description, utility notes, missing input, and operator owner','the operator or logistics lead','confirming site suitability, making a safety decision, or promising setup timing'],
  ['independent-publisher-rights-request-assistant-routine','Track rights and permissions requests for an independent publisher','publishing rights admin assistant','Create a complete request register while the rights owner retains licensing interpretation, pricing, and permission decisions.','/images/aug20-blog-source-ledger.png','request ID, requester, work, edition, material requested, territory and term as stated, source files, and rights owner','the publisher or rights manager','interpreting a contract, quoting a fee, or granting permission'],
  ['beekeeping-supply-store-backorder-assistant-routine','Run a backorder follow-up queue for a beekeeping supply store','beekeeping store support assistant','Keep supplier and customer facts visible while the owner controls substitutions, stock promises, and husbandry advice.','/images/aug20-blog-support-escalations.png','order ID, SKU, supplier status, carrier status, customer request, last update, proposed next contact, and owner','the store owner or inventory lead','recommending a product, promising stock, authorizing a substitution, or giving beekeeping advice'],
  ['dance-costume-rental-return-assistant-routine','A return-condition handoff for a dance costume rental shop','costume rental admin assistant','Document returns consistently while shop staff retain damage, cleaning, fee, and inventory decisions.','/images/aug21-blog-interview-notes.png','rental ID, item IDs, return time, supplied checklist, photographs, stated issue, missing pieces, and shop reviewer','the costume manager or shop owner','assessing damage, setting a fee, selecting treatment, or returning an item to inventory'],
] as const;

export const sep9BlogPosts = briefs.map((b, i) => {
  const [slug,title,mainKeyword,excerpt,image,fields,owner,stop] = b;
  const p = [
    `${title} starts with a deliberately small lane: one dated queue assembled from records the business already approves. The assistant prepares the evidence; ${owner} makes the consequential decision.`,
    `For every item, record ${fields}. Copy material wording rather than polishing away uncertainty, and link the source that a reviewer can reopen.`,
    `Write the stop rule into the assignment: pause before ${stop}. A visible gap is useful; an invented answer is not.`,
    `Choose one daily cutoff and state its time zone. Items received later stay visible for the next pass unless ${owner} documents a different handling decision.`,
    `Limit access to the queue and source folders needed for this routine. Payments, account recovery, deletion, permission changes, and unrestricted exports remain outside the lane.`,
    `During the first review, include a straightforward item, an incomplete item, and an item that triggers the stop rule. Record corrections as examples tied to the exact field or source that caused confusion.`,
    `After several passes, compare complete handoffs, returned items, unresolved exceptions, and owner review time. Widen the lane only when its evidence and escalation path still work under ordinary pressure.`
  ];
  return {slug,mainKeyword,title,excerpt,published,richPublished:true,minutes:8+(i%3),image,imageAlt:`Remote assistant preparing a ${mainKeyword} handoff`,sourceBody:`Publication date: September 9, 2026.\n\n${p.join('\n\n')}`,takeaways:['Keep one source-linked daily queue.',`Route decisions to ${owner}.`,`Stop before ${stop}.`],detail:{revision:`${published}-${slug}-r1`,directAnswer:p.slice(0,2),bodyLinks:[{href:'/services',label:'assistant services'},{href:'/research',label:'research library'}],sections:['Set one bounded lane','Preserve the source record','Make the stop rule explicit','Use a dated cutoff','Restrict access','Train with mixed cases','Review before expanding'].map((heading,n)=>({heading,paragraphs:[p[n],p[(n+2)%p.length]]})),decisionRows:[{need:'Record preparation',fit:'Remote assistant',reason:'Uses approved sources to create a reviewable handoff.'},{need:'Judgment or commitment',fit:'Named owner',reason:`Remains with ${owner}.`},{need:'Missing or conflicting facts',fit:'Exception route',reason:'Preserves uncertainty instead of guessing.'}],planningNumbers:[{value:'1 queue',label:'Initial scope',note:mainKeyword},{value:'3 cases',label:'Training sample',note:'Ordinary, incomplete, and stopped.'},{value:'1 owner',label:'Decision path',note:owner},{value:'Sep 9',label:'Publication date',note:'September 9, 2026.'}],scripts:[{title:'Daily assignment',text:`Prepare today's ${mainKeyword} queue from approved sources. Record ${fields}.`},{title:'Exception note',text:`I stopped because this item may require ${stop}. The checked source and open question are linked.`}],scenario:{title:`First-week ${mainKeyword} review`,intro:'Test the routine on a small representative batch.',steps:[{step:'1',title:'Confirm inputs',body:'Name approved sources and the cutoff.'},{step:'2',title:'Prepare',body:`Record ${fields}.`},{step:'3',title:'Hold gaps',body:'Keep missing or conflicting facts visible.'},{step:'4',title:'Escalate',body:`Route judgment to ${owner}.`},{step:'5',title:'Repair the rule',body:'Turn one correction into a specific example.'}]},faqs:[{question:'Can the assistant make the final decision?',answer:`No. That remains with ${owner}.`},{question:'What happens when a fact is missing?',answer:'The assistant records the gap and sends a bounded, source-linked question.'},{question:'When should permissions expand?',answer:'Only after reviewed work and a separate access decision.'}],relatedLinks:[{href:'/services',label:'Review assistant service lanes'},{href:'/research',label:'Browse the research library'}],sources:[{name:'NIST Cybersecurity Framework 2.0 Small Business Quick-Start Guide',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-20-small-business-quick-start-guide',note:'Risk and access-management context.'},{name:'FTC, Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business',note:'Business information-handling context.'}]}};
});
